psychopy/hardware/joystick/pyglet_input/app/win32.py
An Incorrect pyglet package name was causing the below issue which using Joystick on windows.
from psychopy.hardware import joystick
File "<input>", line 1, in <module>
File "C:\Program Files\PsychoPy2\lib\site-packages\psychopy-1.81.02-py2.7.egg\psychopy\hardware\joystick\__init__.py", line 36, in <module>
import pyglet_input
File "C:\Program Files\PsychoPy2\lib\site-packages\psychopy-1.81.02-py2.7.egg\psychopy\hardware\joystick\pyglet_input\__init__.py", line 163, in <module>
from directinput import get_devices, get_joysticks
File "C:\Program Files\PsychoPy2\lib\site-packages\psychopy-1.81.02-py2.7.egg\psychopy\hardware\joystick\pyglet_input\directinput.py", line 6, in <module>
import app
File "C:\Program …
=> BF : ImportError cannot import name types while using Joystick on Windows

psychopy/iohub/client/__init__.py
The iohub connection class clearEvents() method now clears both the
global iohub event buffer and all device level event buffers by default.
Previously, io.clearEvents('all') was used to achieve this.
To only clear the iohub global event buffer and leave device level event
buffers intact, now use:
io.clearEvents(device_label=None)
=> ENH: iohub clearEvents() default behaviour

psychopy/tools/monitorunittools.py, psychopy/tools/versionchooser.py
Using addUnitTypeConversion() raised a NameError because there were typos in two variable names.
useVersion() raised ScriptError with message but there is no ScriptError in Python and NameError was raised with a default message instead. This made the raise only useful to exit the function but not to message back what was wrong. This was fixed by replacing ScriptError with RuntimeError.
Both were found by pylint.
=> Fix errors in addUnitTypeConversion() and useVersion()

psychopy/app/builder/builder.py, psychopy/app/builder/components/_base.py, psychopy/app/builder/experiment.py
This change definitely addresses issue #792; it completely fixes both the minimal example, and the original
post to the users list.
I think this change is conceptually right (i.e., code for a start value means that start times are not always known, and hence are not safe to treat as non-slip friendly).
But I'm not certain that *everything* is right. Please review (as always).
=> BF: code startVal should not be nonSlipSafe; hopefully closes #792

buildWinDistributions.bat
The copy command fails with a syntax failure because /I is not a valid parameter. Probably this line remained while the command was changed to copy from xcopy...
=> Deleted the /I switch in copy

psychopy/app/builder/components/_base.py
- app would crash if trying to calculate duration when startTime==None (== using code for start). app would fail to reopen because trying to reload the offending file.
- allow nonSlip in cases where the end time is known (relative to start of routine)
=> BF: component nonSlip and duration

docs/source/builder/components/sound.rst
I just saw that the documentation for the "Volume" parameter is missing. I was guessing (and there is a tool tip) what it is supposed to mean. I just wasn't sure whether, e.g., the value can be outside the range and will be clipped etc. Maybe someone can improve on this.
Best,
Axel
=> Update sound.rst: Volume parameter missing

psychopy/web.py
issue = reports of socket.timeout() if flaky internet access
attempted fix: ignore all exceptions (= return False instead of crash)
=> RF: web.haveInternetAccess() occasionally errored; hopefully fixes #741

psychopy/data.py
Currently, PsychoPy cannot import conditions files which have fields which contain commas, even when those fields are surrounded by quotes, which is a common CSV convention.
To fix this, the TrialHandler now imports conditions files using the pandas csv_reader rather than numpy's recfromcsv
NB this works for Coder BUT Builder's loop dialog still fails to deal with csv files which contain quoted commas. That GUI aspect needs to be updated in a similar fashion but I'm not sure how.
i.e. at this stage, data.py can deal with these csv files, but Builder users can't select them.
=> BF: import csv files containing quoted commas

docs/source/builder/components/sound.rst
Hi Jon and others,
It seems there were some name changes; that's why the links were broken. I changed "~psychopy.sound.Sound" to "~psychopy.sound.SoundPyo". If somebody could confirm that this fixes the problem, I would also fix some other broken links in the same manner: Keyboard --> Event, Microphone --> AudioCapture, Mouse --> mouse.
Cheers,
Axel
=> DOC: Broken link from Builder to Coder Sound documentation

docs/source/builder/components/keyboard.rst, docs/source/builder/components/microphone.rst, docs/source/builder/components/mouse.rst
The links from Builder to the Coder API (under "see also") did not show for Keyboard, Microphone, Mouse. It seems some name changes were responsible. I hope everything works now. Keyboard is pointing to Mouse now because both are handled in the API on one page (psychopy.event alone does not work). Maybe somebody can check.
Best,
Axel
=> DOC: Fixed broken links for Keyboard, Microphone, Mouse

docs/source/_templates/layout.html
As discussed in #824. This was very easy to implement, and as far I can tell from building the docs on my machine everything works fine. I guess we may want to change some page titles for the main landing pages, e.g. the main/root page is now titled 'Home -- PsychoPy vX.X.X', we could change this and other "main" pages so they have PsychoPy at the start, e.g. "Psychopy Home".
If there's anything I should be checking in terms of the docs building correctly, let me know.
=> Docs: start HTML title with current page

docs/source/builder/components/sound.rst
For now, I just deleted the "mp3" support for sound, since it doesn't seem to work and most people found out the hard that they have to use "wav" or other. If there is a more detailed story about this issue (mp3 use possible under conditions 1-x, for example), which should also be part of the documentation, let me know and I can take care of it.
Cheers,
Axel
=> DOC: Deleted mp3 support for sound

psychopy/iohub/devices/eyetracker/hw/tobii/eyetracker.py
For some reason, in 1.82, when iohub calls win.close() on the full
screen window created for tobii calibration graphics, the window does
not actually close.
Work around is to minimize() the full screen window before calling
close, then it closes the window fine and the experiment window is
visible as expected.
=> BF: Tobii calibration window not closing in 1.82

psychopy/data.py
Fixes #814. I think the fix for this is pretty straightforward, we just fill in the `extraInfo`
values along with the rest while looping through the header. I've changed the tests
against `None` to use `is` rather than `!=` since I was changing those sections
anyway, but if people want to suggest any other improvements I'm happy to
include them.
=> BF: Don't overwrite extraInfo variables in TrialHandler.saveAsWideText() (#814)

psychopy/data.py
ExperimentHandler.saveWideText is now set to False before
dumping the pickle in ExperimentHandler.saveAsPickle().
This way, the wide text file is not automatically created
again when working with unpickled .psydat files.
=> BF: Diable saveWideText before pickling

psychopy/info.py
When win == False, you can't ask to manipulate win properties like setting win.autoLog = False.
=> RunTimeInfo window bug fix

docs/source/api/sound.rst, docs/source/general/prefs.rst, docs/source/recipes/addCustomModules.rst
Hello,
I added documentation for some options in the "General Settings" that were missing. I had a couple of questions related to that:
* sound.rst: In the first paragraph, it says: "This can be set on a per-experiment basis by importing preferences, and setting the audioLib preference to use." I couldn't find any current documentation that could be linked. It would be good to know how exactly this can be done on a per-experiment basis (and not just the general settings).
* prefs.rst: I would restructure the document to reflect the sequence of tabs in the "General Settings" dialog, but I still feel uneasy about this without an OK from the core team.
* prefs.rst: Documentation for options in most other tabs are missing, but, again, I wanted to ask for an OK before I proceed with this. The …
=> DOC: Added Preferences documentation and related links

psychopy/visual/movie2.py
+ OpenCV Video player is created once for life of MovieStim2 instance,
instead of being recreated for each movie load.
+ removed [:] from line:
..., self._numpy_frame = self._video_stream.retrieve()
+ removed setFPS(), movie always should play at fps indicated in video
file
=> BF: Memory leak in moviestim2

docs/source/general/prefs.rst
Dear all,
I have restructured the help section on Preferences to reflect the order of tabs and options in the current dialog and also added missing options. There were a few options documented in the prefs.rst file that weren't available anymore in the dialog itself. But I'm not sure if there are some options that would only appear on certain systems. The options I deleted were (with help text):
"App" settings:
runScripts:
Don't ask. ;-) Just leave this option as 'process' for now!
allowModuleImports (only used by win32):
Allow modules to be imported at startup for analysis by source assistant. This will
cause startup to be slightly slower but will speedup the first analysis of a script.
"Coder" settings:    
analysisLevel:
If using the source assistant, how much depth should PsychoPy try …
=> DOC: Restructured help for preferences dialog and added options

psychopy/tests/test_data/test_ExperimentHandler.py
As Jeremy [pointed out](https://github.com/psychopy/psychopy/commit/6b293561edcd778d6de925662cb3c573b9a59d74#commitcomment-9915433), the keys in experimental condition specifications should consist of ASCII characters only, because at least the Builder creates variable names from the keys, and the test might yield misleading results in the future.
=> BF: Condition keys should be in ASCII

psychopy/event.py, psychopy/gamma.py, psychopy/tests/test_Installation.py, psychopy/tests/test_misc/test_event.py, psychopy/visual/window.py
Motivation: testing PsychoPy mouse code & experiments, maybe use in actual experiments
Current description:
- fully backwards compatible
- want an emulation mode that sets mouse RT as a side effect
- very fast (< 10^-5s), effectively as fast as before; profiling revealed a 250ms delay
for the first mention of pyglet.window.mouse.LEFT MIDDLE RIGHT
- move import pyglet.window.mouse.LEFT etc earlier to avoid 250ms first-mention
delay; don't want that to happen during an experiment trial
- RF to allow for multiple buttons at once via a single integer code
Still to-do:
- add a proper API in psychopy.hardware.emulator?
- emulation of click coordinates x, y; they can be given here but no effect (merely logged)
=> misc small commits

.travis.yml
idea: test all new code to this standard, even if we don't immediately move to pyglet 1.2 for the app
=> ENH: use pyglet 1.2.x for testing on travis-ci

psychopy/iohub/client/__init__.py, psychopy/tests/test_iohub/test_event_get_and_clear.py
Fixed bug in an iohub test case reported by Jeremy.
=> BF: tests.test_iohub global event buffer only clear

psychopy/gamma.py
I searched the code base and found one other instance of the screen.id, so updated that one for pyglet1.2 as well
=> FF: pyglet1.2.1 adjustment to gamma.py

psychopy/parallel/__init__.py
* During import, warnings are thrown if on a Mac or Windows drivers could not be found
* Added __init__ for ParallelPort, so that informative warning is thrown during instance creation
=> BF: ParallelPort Class gives informative warnings

psychopy/gui.py
psychopy.gui.Dlg.addField() can't calculate width of Japanese Kanji characters.
Following image shows a code to reproduce this issue.
psychopy.gui.Dlg.addText() correctly calculates width of Kanji using GetTextExtent() (line 75).
addField() should also use GetTextExtent(), I think.
=> FIX: improve display of Kanji characters on psychopy.gui.Dlg

psychopy/monitors/MonitorCenter.py
- locale.str() needs a number, so ensure it gets one
=> BF: MonitorCenter value are sometimes None

psychopy/data.py
Switching to pandas for reading in .csv conditions files unintentionally broke the ability to deal with non-ASCII character content. By now explicitly setting the default encoding parameter to UTF-8, we restore that ability (.xlsx files unaffected: they already deal with Unicode OK).
=> Allow non-ASCII characters in .csv condition files

docs/source/changelog.rst, psychopy/CHANGELOG.txt, psychopy/visual/ratingscale.py
- changes the text displayed during run-time
- value from .getRating() remains as a proportion
=> NF: allow ratingscale display to support min:sec

psychopy/data.py, psychopy/event.py
In the TrialHandlerExt class used for noncounterbalanced designs, the saved data for each of the conditions can be repeated for different numbers of times. This requires us to organize the data for each condition in a single row for saving in excel/csv format. Due to a typo failing to transposing the mask array, the masking was improper for unsaved blocks. This has been fixed now.
=> BF: TrialHandlerExt - ensure proper masking of data for uncompleted blocks

psychopy/event.py
This function binds the mouse to a window (and makes the cursor invisible). The use-case would be a multi-monitor setting where the participants need to click to respond. Without using a function like this, the cursor can be moved out of the region of the experiment.
=> Function to set mouse exclusivity for a window in Pyglet

docs/source/resources/resources.rst
Now points to the recent and elaborate version of the PsychoPy crash course.
=> DOCS: updated GestaltReVision PsychoPy course link

psychopy/data.py
If ExperimentHandler's saveAsWideText() function was called with the file name "stdout" (to write to sys.stdout instead of a real file), the standard output was closed afterwards. This was fixed by only closing the used file object if it is not the standard output object.
Also replaced a print statement with call to logging function for consistency.
=> BF: Fix closed stdout after ExperimentHandler save

psychopy/app/builder/builder.py
Addresses this issue:
https://github.com/psychopy/psychopy/issues/909
i.e. Builder loop dialogs should now show the full (absolute or relative) path to a conditions file, rather than displaying an abbreviated version (which was created to ensure the filename would always be visible). i.e. now when a path is long, one might have to move the insertion point through the field to see the filename, but the text representation of the path will match the actual path.
=> ENH: Stop abbreviating condition file path as displayed in loop dialog

psychopy/visual/movie2.py
New versions of VLC player (64 vlc on OSX) seem to need a VLC_PLUGIN_PATH environment variable in order to create the vlc.Instance() or you can get an error that the plugins can't be found
=> FF: merge conflict bringin in fix for latest vlc player

psychopy/visual/vlc.py
I am trying to install PsychoPy on PortablePython (http://portablepython.com/) for my student who want to learn PsychoPy using a Windows PC in a University computer room. My student doesn't have privileges to install software on them.  Most of demos in psychopy/demos/coder/stimuli work fine simply copying site-packages directory of the StandAlone PsychoPy to Portable Python, but MovieStim2.py doesn't work because VLC Media Player is not installed on the PC.
In order to run MovieStim2.py without installing VLC Media Player to the PC, I installed Porable VLC Media Player (http://portableapps.com/apps/music_video/vlc_portable) and Portable Python together on an USB memory. Then I modified lines 139-140 of psychopy/visual/vlc.py to search for Porable VLC Media Player if VLC Media Player is …
=> ENH: supporting Portable VLC Media Player

psychopy/visual/aperture.py
Hello again!
When trying to define more complicated apertures to use with (e.g.) ElementArrayStims I ran into frustrations. Here, I added a feature to Aperture allowing to use an image with transparency (I tested with a PNG file) as the basis for the aperture shape.
I tried to change the parameters as little as possible so that I reused the shape parameter. I hope that this does not break anything (I check whether the filename string leads to a real file on disk like in SimpleImage).
One open question would be whether these calls during the _reset need to be disabled again after the draw():
```python
GL.glEnable(GL.GL_ALPHA_TEST)
GL.glAlphaFunc(GL.GL_GREATER,0)
```
Any comments on that?
Also I hope that was not too bold to include my name in the author list of the file... :)
This is a …
=> NF: Apertures can be defined using image files with transparency

psychopy/app/builder/builder.py, psychopy/app/builder/validators.py
Following errors are fixed.
* Exception is raised when "Save as" button of the Conditions Editor is clicked (lines 2718 and 2723 of builder.py).
* "Avoid 'this', 'these' ... " message is not translated (line 56 of validators.py).
* Exception is raised when conditions file that contains unicode characters in its name cannot be opened (line 3114 of builder.py).
=> FIX: fix errors in validating values in Builder dialogs.

psychopy/app/builder/builder.py
For the debug log message the variable name was logged instead of its contents.
Dropping ".py" files on Builder raised an AttributeError instead of opening them in Coder (found by pylint).
The warning log message was incomplete because ".py" files are also accepted.
=> BF: Fix not opening files after drop on Builder and related log messages

psychopy/app/builder/builder.py
If the "Screen" setting in the "Experiment Settings" dialog was set to an unsupported text value, the dialog could not be opened again after closing it. Values which could not be converted to integers raised a ValueError in int() and values which could be converted but were smaller 1 raised a ValueError in wx.Display(). Both cases were fixed by adding additional checks and using the default value (first screen) if needed.
The change also fixed not updating the "Window size" field if the window setting was toggled while an unsupported "Screen" value was set above.
=> BF: Fix locking out of Builder Experiment Settings

psychopy/app/coder/coder.py, psychopy/app/preferencesDlg.py, psychopy/app/psychopyApp.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec
Idea: allow execution of code without the possibility of either the subject or experimenter inadvertently typing something that would end up in the script. See #943 
1) -x option: Use the PsychoPy app to invoke StandAlone python to execute a .py script passed as an argument.
2) User pref: make Coder files read-only
Other use cases for -x option = programmatic invoking of python scripts using StandAlone's python (Craig Stark, users' list)
=> ENH: allow code execution without editing (2 ways)

createInitFile.py, psychopy/__init__.py
Following the lead of other `check_output` calls to git, this redirects `stderr` so that warnings are suppressed.
=> Suppress git warning if not in repository

psychopy/app/builder/components/keyboard.py, psychopy/app/builder/components/movie.py, psychopy/demos/coder/stimuli/MovieStim.py, psychopy/sound.py, psychopy/tests/test_app/test_builder/componsTemplate.txt, psychopy/visual/window.py, setupApp.py
moviepy is now available (and is the default!) in Builder. Making it default so quickly may seem strange but the other options have been such a pain that I think it's worth it!
Keyboard now has the option to sync with screen refresh, which should be turned on (default) if the stimulus of interest is a visual stimulus. If turned off then the RT clock starts before the screen has refreshed (i.e before the stimulus is visible) so RT's were ~0.5 screen refreshes longer than they should be.
=> making MovieStim3 (moviepy) more visible/accessible and better timing for keyboard.RT

psychopy/visual/window.py
Allow for a with statement that implicitly closes a `Window` at the end of the block, e.g.
with visual.Window(...) as w:
[Perform experiment]
[w is now closed]
=> ENH: Add context manager to visual.Window

CONTRIBUTING.md
Hi, it's my first time contributing to a repo - I am excited to use PsychoPy and eventual make a "real" contribution to the open source code base.
Happy to start a conversation here regarding more information to add to `CONTRIBUTING.md` (pep8? code style? etc.)
[It's nice to have this file](https://github.com/blog/1184-contributing-guidelines) because anytime you open a PR on github it automatically displays a big yellow bar with "Have you read the contributing guidelines?" and a link to the file.
=> Bubbled some contribution guidelines to root of repo

psychopy/visual/movie3.py
Not entirely sure what it was but something to do with the textures not being (re)set correctly when the movie frame is being drawn
=> BF: fix issue with MovieStim3 when combined with ShapeStim derivatives

psychopy/app/builder/components/__init__.py
The Builder would not start if the most recent Pillow version (3.0) was installed in my Python environment. Turned out that the method `Image.tostring()` was removed from Pillow, and `Image.tobytes()` should be used instead.
This PR restores support for recent Pillow versions while maintaining PIL compatibility (e.g. for standalone).
=> Restore Pillow support

psychopy/tests/test_misc/memory_usage.py
- useful from the command line
- too unstable at present for travis-ci, so use a filename that pytest will not auto-detect
- some things do not pass, so skip them for now (placeholder tests)
- need pyo compiled with patch for leak (pyo commit, Oct 26 2015) or sound will fail
=> TESTS / WIP: proof of concept for memory leakage testing

psychopy/data.py
``StairHandler.__init__()`` used to check if the `stepSizes` argument was a
float or an int, and treated it as array-like otherwise. However, this would
fail e.g. for NumPy types like np.float32.
We now try to treat `stepSizes` as array-like without prior checking, and catch
exceptions if that fails.
=> BF: Make StairHandler work with stepSizes other than float, int

psychopy/contrib/tesselate.py, psychopy/demos/coder/stimuli/filled_shapes.py, psychopy/visual/shape2.py
Close to being a drop-in replacement for ShapeStim.
Known backwards-incompatibilities (might be others too):
- no dynamic updating of individual vertices. 
to see: convert coder demo shapes.py to use ShapeStim2.
- a fix: rewrite the Shape2.vertices property to call tesselate, etc; fast enough with few verts. might be worth doing that regardless, just to pull the setVertices logic out of __init__
=> ENH: ShapeStim2 handles lines

psychopy/visual/window.py
Since multiFlip() turned out to behave erratically, its use is discouraged.
This commit adds docstrings with respective warnings, improves the argument
sanity checking, and allows the user to supply non-integers as the number of desired
flips, which will then be rounded and emit a warning.
Closes #867.
=> RF/DOC: Discourage use of multiFlip()

psychopy/app/builder/builder.py
We stopped abbreviating condition file paths with #913. `builder.getApprev()` is
an orphan function since then and not used anymore. I verified that this code is
not called in any other part of PsychoPy anymore, and removed it.
=> RF: Remove `getAbbrev()`

psychopy/data.py, psychopy/tests/test_data/test_stairs.py
**THIS IS WORK-IN-PROGRESS, PLEASE READ COMMENTS BELOW AND DO NOT MERGE YET**
QUEST intensity scaling was removed. This is a backward-incompatible change, as it removes the `stepType` keyword argument from `QuestHandler.__init__()`. This closes #1006.
This PR increases the test coverage of all except the Psi staircase methods. Particularly, it
* adds a test for log steps in the `StairHandler`,
* adds a test for the `QuestHandler`,
* introduces a base class `_BaseTestStairHandler` that implements a `simulate()` method for simplified testing,
* completely reworks `makeBasicResponseCycles()` to create simulated response cycles of arbitrary lengths.
Closes #1007 for the time being.
=> [WIP] ENH: Improve staircase test coverage, fix QUEST

psychopy/visual/ratingscale.py, psychopy/visual/text.py
Reduces the impact of pyglet memory leak for text, and is faster when there's no change. This is quite useful when setting text every frame via Builder.
Such a check seems useful for slow and or leaky things, much less expected benefit for fast and clean things, like setting .pos. Would be good to do such a check in ShapeStim, to avoid redundant tesselation.
=> ENH: set text only if it changed

psychopy/app/builder/experiment.py
This has been removed. The cost is that we won't be forwards compatible
with experiments from Builder 1.60.01 any more, but these are very old!
=> FF: new xml read/write doesn't support getparent

psychopy/data.py, psychopy/tests/test_data/test_StairHandlers.py
This PR changes the behavior of `data.StairHandler` such that it emits a warning when increasing the number of reversals if the `stepSizes` parameter requires more reversals than requested via the `nReversals` paramter.
Also adds new tests for staircase handlers, and improves older tests.
=> [RF/TEST] Improved user feedback in `StairHandler`, more tests

psychopy/data.py
`data.PsiHandler.__init__()`'s keyword argument `TwoAFC` does not match the naming schemes chosen in all other parts of PsychoPy. This PR renames the argument to `twoAFC`. This change is not backward-compatible, but given the novelty of the Psi method in PsychoPy, this should affect very few users, if any.
`contrib.psi.PsiObject.__init__()` takes several keyword arguments, which were only passed as positional arguments by `data.PsiHandler` so far. This PR changes `PsiHandler` such that it now passes the respective parameters as keywords. This change is fully backward-compatible.
=> PsychoPy'ify PsiHandler API, Make use of PsiObject keyword arguments in PsiHandler

psychopy/app/builder/components/cedrusBox.py, psychopy/app/builder/components/ioLabs.py, psychopy/app/builder/components/keyboard.py, psychopy/app/locale/ja_JP/LC_MESSAGE/messages.po, psychopy/tests/test_app/test_builder/componsTemplate.txt
Suggesting via a tooltip that users refer to a variable in Builder as
“thisTrial.correctAns” will often lead to inscrutable bugs in loops
called anything other than “trials”. The prefix is redundant anyway, so
this suggestion now removed and replaced with the unprefixed variable.
NB What are the implications for the translated versions of these
English tooltip strings?
=> DOC: Correcting (sometimes) erroneous (English) tooltips

psychopy/visual/gamma.py
gamma.py looks for the Carbon framework in the wrong place under OS X 10.11. The framework binary was moved from
/System/Library/Carbon.framework/Carbon
to
/System/Library/Frameworks/Carbon.framework/Carbon
Additionally gamma.py only calls the CGSetDisplayTransferByTable(,,,,). This function was moved to the CoreGraphics framework.
Therefore, my suggestion is that gamma.py should try to load the CoreGraphics framework first and should use the Carbon framework only as fallback.
I implemented better exception handling additionally to pull request #1084
=> BF OSError: gamma.py can't find Carbon framework + better exception handling

psychopy/app/builder/dialogs/__init__.py, psychopy/app/builder/experiment.py, psychopy/app/coder/coder.py, psychopy/data.py, psychopy/tools/plottools.py
prefer eval( )
retain exec( ) for imports
skip exec() used to append to a list; should be changed but risk of breakage is higher
=> RF: reduce use of exec( )

psychopy/app/builder/builder.py, psychopy/app/builder/dialogs/__init__.py
The proper thing would be to delete this function completely, and rewrite the code. (No need to support python 2.5 anymore.)
=> FF: reposition _relpath function; closes #1098

psychopy/app/builder/experiment.py
The typos were introduced in the recent refactoring.
Thanks!
=> FF: Fix minor typos in three Builder hints

psychopy/app/builder/dialogs/dlgsCode.py
Quite optional.
This was the only egregious example of multiple lower_underscore var names that I am aware of (having just looked at a lot of app/ and library code). If its worth converting things to camelCase for consistency, maybe this is a good time to do it. If not worth it, no trouble, I do not feel strongly about it.
=> RF: convert a few non_camel vars to camelCase

psychopy/app/_psychopyApp.py, psychopy/app/builder/builder.py, psychopy/app/builder/dialogs/__init__.py, psychopy/app/builder/experiment.py, psychopy/app/builder/validators.py, psychopy/app/coder/coder.py, psychopy/clock.py, psychopy/compatibility.py, psychopy/locale_setup.py, psychopy/monitors/MonitorCenter.py, psychopy/preferences/preferences.py, psychopy/tools/monitorunittools.py, psychopy/visual/basevisual.py, psychopy/visual/elementarray.py, psychopy/visual/filters.py, psychopy/visual/gamma.py, psychopy/visual/globalVars.py, psychopy/visual/helpers.py, psychopy/visual/ratingscale.py, psychopy/visual/simpleimage.py, psychopy/visual/window.py
avoid things that a user might access, like parameters, function names, color space names
skip clock.py _countdown_duration just in case
skip: contrib/*, hardware/*, iohub/*, gui/*, micriphone.py,  introspect.py, movie2.py, platform_specific
=> RF: more lower_underscore to camelCase internals

psychopy/app/builder/components/_base.py, psychopy/app/builder/components/cedrusBox.py, psychopy/app/builder/components/code.py, psychopy/app/builder/components/dots.py, psychopy/app/builder/components/grating.py, psychopy/app/builder/components/image.py, psychopy/app/builder/components/keyboard.py, psychopy/app/builder/components/movie.py, psychopy/app/builder/components/patch.py, psychopy/app/builder/components/polygon.py, psychopy/app/builder/components/settings.py, psychopy/app/builder/components/text.py, psychopy/app/builder/experiment.py, psychopy/app/coder/coder.py, psychopy/app/connections.py, psychopy/core.py, psychopy/data.py, psychopy/logging.py, psychopy/monitors/MonitorCenter.py, psychopy/monitors/getLumSeries.py, psychopy/tools/versionchooser.py, psychopy/visual/simpleimage.py, psychopy/visual/textbox/textgrid.py, psychopy/web.py
As found by @hoechenberger and @jeremygray during whitespace and line-length refactoring; some issues fixed by removing unused code.
CHANGELOG
- fixed 12 or so minor bugs
- core.shellCall now accepts a tuple
- MonitorCenter objects made pre-version 0.63 may not work anymore
- TrialHandler .nextTrial() removed (was deprecated June 2006). Change: use .next() instead
- TrialHandler[2|Ext] objects now correctly report their class in str()
- BaseComponent.writeTimeTestCode() is deprecated (will be removed in 1.85).
=> BFs: clean up several minor bugs & issues

psychopy/demos/coder/iohub/eyetracking/simple.py, psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/eyetracker.py
1. BF: Setting sampling rate when using binocular mode in eyelink 1000 did not always update tracker to requested (valid) sampling rate. Also was printing debug messages.  
2. ADD: 'simple' eye tracker demo, uses launchHubServer, no .yaml config files, and no .hdf5 file recording.
=> BF: setting iohub eyelink binoc srate +

psychopy/tools/wizard.py
Some messages were untranslatable since the recent refactoring.
PoEdit only takes the strings which are kept directly in the `_translate()` calls.
Thanks!
=> FF: Fix untranslatable messages in wizard

psychopy/visual/ratingscale.py
`RatingScale.timedOut` and `RatingScale.beyondMinTime` were
previously only initially created during the first call to `draw()`; however, these
properties should already be created during object instantiation.
This allows to write code like:
```
rs = RatingScale(...)
while not rs.timedOut:
pass
```
instead of:
```
rs = RatingScale(...)
rs.timedOut = False
while not rs.timedOut:
pass
```
=> RF: Create some instance properties in __init__()

psychopy/app/projects.py, psychopy/hardware/crs/bits.py, psychopy/sound.py, psychopy/visual/textbox/__init__.py, psychopy/visual/window.py
Some modules had `global` statements at module top-level, which are redundant since top-level variables are global by definition.
Closes #1162.
=> RF: Remove unnecessary `global` statements

docs/source/api/encryption.rst, docs/source/coder/codeLogging.rst, docs/source/general/glossary.rst, docs/source/general/projects.rst, docs/source/gettingStarted.rst, docs/source/recipes/classroomInstallation.rst, docs/source/troubleshooting.rst
The projects documentation also had an incomplete sentence.
The "CPU" and "GPU" entry in the glossary were not included in the sorted list of entries and not linked from other pages (e.g. "rendering.rst") because of the different indentation.
Thanks!
=> DOC: Fix typos and sphinx warnings in documentation

psychopy/app/_psychopyApp.py
This was caused because the projects catalog maintained references to
projects until sys.exit so they were in a garbage-collect race with the
os.path module. We can force them to be garbage collected during
app.quit() instead of sys.exit()
=> FF: get rid of annoying message about the __del__ method of projects

psychopy/app/builder/flow.py
Removing a loop or routine raised an `AttributeError`.
Thanks!
=> FF: Fix error if removing loop or routine from flow

psychopy/app/projects.py
A project file named "None.proj" was created when the Sync dialog was opened (please see [this thread](https://groups.google.com/forum/#!topic/psychopy-dev/fM9G3WbfugQ) for detail).
1. Project ID is used as the local project name of project if no local project name is provided (Lines 495-496, 857-861).
2. Autosave is set to be False to avoid creating unnecessary project file when the Sync dialog is closed before synchronization is performed (Lines 782-783).
3. Path to the project file is updated and saved when "Sync Now" button is pressed. Autosave is set to be True at the same time (Lines 864-867).
=> FF: fix project file name

psychopy/app/builder/dialogs/dlgsCode.py
`FlatNotebook`-tabs don't allow styling, so this code adds an asterisk after the tab name if the associated `CodeBox` isn't empty (see issue #1194).
Example:
The titles are only recalculated when opening the dialog, so switching between tabs after editing doesn't add the asterisks. This shouldn't be a problem, as it's mainly needed when opening the code dialog for the first time.
=> Add a visual indicator to tabs containing code (issue #1194)

psychopy/data.py
empty cells in csv conditions files break the future loading of the
experiment flow in the builder. Empty cells in the
csv are read as type numpy.nan and stored as "nan" in the psyexp file.
This change converts them to python type None which is the same type that
empty cells in xlsx conditions files are read in as...
=> Fix problem with empty cells when importing a csv conditions file

psychopy/monitors/MonitorCenter.py
https://github.com/psychopy/psychopy/pull/1208  seems to have introduced a bug whereby Monitor Centre shows the horizontal pixel size in the vertical pixel field. Issue first reported here: http://discourse.psychopy.org/t/monitor-center-psychopy-v1-84-0rc5/877 by user Fahed
=> BF: Monitor centre not displaying vertical pixels

psychopy/data.py
In importCondtions() method, added the option "data_only=True" to the call to load_workbook(), so that the that values of a cell, and not the formulas, are imported into psychopy.
=> Excel importConditions(): don't import formulas

psychopy/visual/movie.py
which also make the module fail with an import error.
Using `MovieStim` fails with:
```
File "/usr/lib64/python2.7/site-packages/psychopy/visual/movie.py", line 48, in <module>
from psychopy import makeMovies
ImportError: cannot import name makeMovies
```
The function for which the import is attempted is nonexistent and unused.
=> removed unneeded import

psychopy/visual/movie3.py
It seems for MovieStim3() the `_reset` attribute is being replaced by `reset`.
The erroneous call breaks the `stop` atribute:
```
mov.stop()
File "/usr/lib64/python2.7/site-packages/psychopy/visual/movie3.py", line 243, in stop
self._reset()
AttributeError: 'MovieStim3' object has no attribute '_reset'
``` 
This behaviour is fixed by the PR
=> corrected attribute naming

psychopy/visual/window.py
Check if GL_STEREO not is supported on this system before calling GL.config. Psychopy crashes instead of showing the typical warning. 
Later on, we can create FBOs to substitute quad buffers for systems without the GL_STEREO extension.
=> BF: moved GL_STEREO extension check before calling GL.Config

.gitignore, psychopy/event.py, psychopy/tests/test_events/test_keyboard_events.py
This enhancement causes keyboard modifier flags from Pyglet to bubble up to the user. This is an optional feature similar to timestamps.
=> Feature Enhancement: Reflect keyboard modifier flags

requirements.txt
I've tried to install Psychopy on ubuntu 16.04 using pip from master and there was one dependency left out in requirements.txt. This pull request adds that dependency.
=> Added missing dependency requests to requirements.txt

psychopy/app/builder/experiment.py
This was happening with Routines that were renamed during versions
1.84.0-1.84.1 where the Flow entry kept the old name by mistake.
We now issue (but don't raise) an error but continue to load the experiment
=> ENH: If a Routine exists only on Flow then skip but load rest

psychopy/demos/builder/keyNameFinder/README.txt, psychopy/demos/builder/keyNameFinder/keyNameFinder.psyexp, psychopy/demos/builder/keyNameFinder/keyNameFinder_lastrun.py
This should add a builder demo called keyNameFinder, whereby the user can find the names of allowed keys to include in builder keyboard components.
=> Adding keyNameFinder builder demo

psychopy/hardware/minolta.py, psychopy/hardware/pr.py
pySerial 3.0 has fully switched to an API with getters and setters for attributes, and
removed the (previously deprecated) `set*` methods we've been using so far.
The changes introduced here are backward-compatible at least with pySerial 2.7.
Closes #1257.
=> BF/RF: Replace deprecated pySerial method calls

psychopy/core.py, psychopy/tests/test_misc/test_core.py
It appears the `StaticPeriod` never actually did what the documentation
promised when specifying the `screenHz` keyword argument. The [docs](http://www.psychopy.org/api/core.html#psychopy.core.StaticPeriod)
say:
```
```
This was indeed never the case (I checked the entire git history via `git log -L :StaticPeriod:core.py`). Instead, the `StaticPeriod` would always wait for the entire specified duration, ignoring the refresh rate and not reserving time for an additional flip. Hence, a user assuming the documented behavior would overshoot by one frame.
I consider this a serious bug we should probably announce somewhere in **bold** letters or something. I don't know if my fix will have any consequences on any Builder components/implementations. At least the `StaticComponent` makes use of the …
=> BF: Properly handle screenHz argument of StaticPeriod

psychopy/data.py, psychopy/tools/fileerrortools.py
This PR fixes two bugs:
* `data.MultiStairHandler.saveAsExcel()` would ignore the `fileCollisionMethod` keyword argument
* `tools.fileerrortools.handleFileCollision()` would behave incorrectly if `fileCollisionMethod='rename'` was passed and no existing file could be found.
Closes #1207.
=> BF: Filename collisions

psychopy/visual/grating.py
=> typo in grating example

psychopy/tools/versionchooser.py
When trying to use a valid tag from the versions repo that hadn't been downloaded as part of the initial versions repo checkout, the command to update the local versions repo was incorrect:  `git fetch github` had two small bugs:
1. Subprocess wasn't executing it in the VERSIONSDIR, giving the error: 
`subprocess.CalledProcessError: Command '['git', 'fetch', 'github']' returned non-zero exit status 128`
2. `git fetch` wasn't automatically downloading tags, so although the commit for the new version was being pulled down, without the tag it could not be checked out as requested. Adding `--tags` pulls down tags correctly.
I also added some whitespace/readability changes to the rest of version_chooser.py from the yapf readability filter, which I've found to be pretty useful (the project's …
=> Bf use version tag fetch

psychopy/visual/movie3.py
The related [issue is here](https://github.com/psychopy/psychopy/issues/1305).
I have changed the code to import the sound module depending on the noAudio flag. This removes the current and potentially future sound module dependency problems for movie presentations with no sound. This change does not effect the default behaviour.
=> moviestim3 sound module problem workaround for silent movies

psychopy/app/psychopyApp.py
On OS X (ca. 10.10 +) in combination with at least iTerm2, the contents of `LC_ALL` is empty by the time `psychopy.compatibility` calls `import psychopy.data`. This leads to
```python
File "/Users/cjb/miniconda_envs/psychopy/lib/python2.7/site-packages/matplotlib/__init__.py", line 1009, in _open_file_or_url
with io.open(fname, encoding=encoding) as f:
LookupError: unknown encoding:
```
Due to `encoding` being `None`. It seems that the fix already exists in
`psychopy/locale_setup.py`
and only impacts OS X installations. This PR simply adds an import of it to `psychopyApp.py`, which fixes the problem for me (see [this gist](https://gist.github.com/cjayb/67d8f6ada85f8fcd58ff1d4e1fc20764) for the conda recipe reproducing my environment).
Update: I'm pretty sure this is related to #1315, so …
=> add locale setup to app (OS X)

psychopy/visual/window.py
The links to pyglet and pygame in the docstring for
psychopy.visual.Window were not prefixed with http:// so they were
rendered as relative links (e.g.
http://www.psychopy.org/api/visual/www.pyglet.org).
=> DOC: Make pyglet and pygame links external

psychopy/hardware/joystick/__init__.py, psychopy/visual/window.py
I was getting an error using a joystick and fixed it by following [a previously recommended workaround](https://groups.google.com/forum/#!msg/psychopy-users/CO37d-PMQ9k/iDDVAn0SD6UJ).
I have also realized that the example usage in the [docstring](http://www.psychopy.org/api/hardware/joystick.html) had a variable name error (```currentjoy.getX()
``` should be ```joy.getX()``` because ```currentjoy``` was not defined above). So have fixed it and took the liberty of changing some more docstrings in the same file to comply with PEP 257.
=> Joystick error

psychopy/microphone.py, psychopy/sound/backend_pygame.py, psychopy/sound/backend_pyo.py
I encountered these and changed the variable names. I have searched all psychopy files to make sure that no other code use the variable names that I changed before this commit.
=> BUG: Fixing variable naming errors in sound module

psychopy/tests/test_all_visual/test_winScalePos.py, psychopy/visual/window.py
See discussion in #1322 
__NB__ `tests/test_all_visual/test_winScalePos.py` fails, predictably. Before fixing the test, I'd like to get a quick review on my implementation.
* should the value be (silently) clipped to +/- 1?
* would it be better to write a setter?
I dabbled with using `@attributeSetter` for `viewPos`, but got repeated
```python
TypeError: 'attributeSetter' object does not support indexing
```
Closes #1322
=> ENH scaling of window.viewPos according to window units

psychopy/sound/backend_pyo.py, psychopy/sound/backend_sounddevice.py, psychopy/tests/test_all_visual/test_all_stimuli.py, psychopy/visual/basevisual.py, psychopy/visual/helpers.py
SoundDeviceSound now supports MovieStim3
Images now check possible extensions:
- first check if string is a note name
- then check if is a file
- if neither then, rather than raise error, we now check whether
- removing the extension reveals a file
- adding other common extensions (jpg, png, bmp etc) reveals file
Although it's possible that this will lead to an incorrect file, it will only do so when no option was available
=> Improvements to SoundDeviceSound and ImageStim

psychopy/event.py
In event.py, since the tuples added to the _keyBuffer are either 3 or… or 2 items in length depending on which part of the code handles the keypress, if a non-ascii character is pressed and timeStamped=True the tuple only has 2 items, yet the return in getKeys is trying to access a the third element of the tuple, so we're getting an index error. This simply changes k[2] to k[-1], to get the last item of the tuple, instead of the third item of the tuple.
This is a quick fix that I hope would have no ill effect, and I'm not super familiar with pyglet and keypresses, but one thing that I thought is worth asking about is if all of the tuples placed in _keyBuffer should be of the same length. See the differences between _onPygletKey and _onPygletText, one of which includes a boolean value …
=> BF: Unicode key presses and timestamp in event.py is throwing IndexError

docs/source/installation.rst
Slight rearrangement of the Dependencies section of the installation doc page. pypiwin32 and pyobjc were included in a list of packages that could be installed in one go, but these two are platform specific. They were removed from the first list, and the sections stating that they were required for Windows and Mac, respectively, were moved just under the longer list.
=> DOC: Move platform-specific packages from general dependency list

psychopy/data.py
Was using pop from the wrong end of the stack; needed to pop(0)
Also added another option of a null trial list that was apparently
valid in the original TrialHandler `trialList=[None]`
=> BF: TrialHandler2 in method='sequential' used reverse sequence

psychopy/sound/backend_pyo.py, psychopy/sound/backend_sounddevice.py
I encountered these bugs on a Windows computer but fixed them using my linux (don't have a Windows nearby), so I was not able to verify that it works. At least it can't get more broken than it was ;-)
Wondering if *_bestDriver* should be moved from `sound/__init__.py` to `sound/backend_pyo.py` since that's the only place it's used?
=> Bugfixing sound

psychopy/sound/__init__.py
If default is selected, it should do nothing - but because the condition was set to check for "auto" instead of "default", it gives an error log saying that default doesn't exist on the audio device list.
=> "default" not correctly checked for speaker option

psychopy/sound/backend_pyo.py
Hi Jon,
I noticed that RC 1.85.00 was crashing on any sound playback - both coder and builder.   This was due to a missing sys import under sound/backend_pyo.py which i've added in.
However, I also noticed that even if you put "pygame" as the default, it crashes with the same error - and tries to use backend_pyo.py instead of backend_pygame.py.   Not sure if this is an additional error, but couldn't spot anything obvious.
Best wishes,
Frank
=> Added missing sys import call

.travis.yml, psychopy/gui/qtgui.py, psychopy/gui/wxgui.py, psychopy/tests/test_gui/test_DlgFromDictQt.py, psychopy/tests/test_gui/test_DlgFromDictWx.py
- Allow to disable automatic sorting of dictionary keys when constructing the input fields
- Make in-place modification of passed dictionary optional
- Allow creation of a `DlgFromDict` object without automatically displaying the dialog; this is esp. useful for automated unit testing
- Make the `order` kwarg more robust: it should now be able to deal with more kinds of iterables
- Streamline the constructor signature a little bit to make it clearer, while ensuring backward-compatibility
- Small number of style improvements
- Add tests
=> RF/NF/TEST: DlgFromDict improvements & Tests

psychopy/demos/coder/stimuli/textBoxStim/textstim_vs_textbox.py
As reported by @alexholcombe here: https://discourse.psychopy.org/t/textstim-vs-textbox-py-demo-not-working/2055 this demo had stopped working. Seems to be resolved by explicitly importing the textbox class. 
Perhaps there is a cleaner way to fix this?
=> BF Get textstim_vs_textbox demo running again

psychopy/sound/backend_sounddevice.py
For an array we should stick to the number of channels that were
in the array
=> BF: remove attempt to set a default n channels for arrays

psychopy/app/preferencesDlg.py
The preferences window imports `psychopy.sound` when compiling
the list of wigdets / settings to display. However, this would fail
if no audio backend is installed.
This commit catches this DependencyError and allows to open the preferences
window nonetheless.
=> BF: Allow to open prefs when no audio backend is installed

psychopy/event.py, psychopy/hardware/emulator.py, psychopy/hardware/forp.py, psychopy/tests/test_all_visual/test_ratingScale.py, psychopy/tests/test_events/test_keyboard_events.py, psychopy/tests/test_misc/test_event.py
When invoking the `event._onPygletKey()` callback function while no modifier key was pressed, pyglet sets the `modifiers` parameter to 0. In fact, this parameter is always an integer, created by OR'ing
different modifier key states. The actual names of the modifier keys can be retrieved by passing this integer to `pyglet.window.key.modifiers_string()`.
However, at many places where `_onPygletKey()` was used to create "emulated" key presses, `modifiers=None` was passed. Nobody noticed so far because apparently the modifiers were not further processed in these cases (since, obviously, they were expected to be insignificant / not present). But passing non-integer modifiers is buggy behavior and actually caused issues for me when trying to implement modifier handling for the global event keys …
=> BF: Invalid modifiers were passed to event._onPygletKey()

psychopy/visual/movie3.py
The structure of the “play” function would previously cause doubled-up
audio, or in some cases cause the audio not to start playing at all. As far as I can tell, there were as many as three issues. 
1. For some reason, audioseek was not being called consistently, sometimes causing inconsistent behavior when looping. In principle moving the IF statement relative to the setting of self.status shouldn't change anything, but it may have helped?
2. The _audioStream.play() call would occur even if the movie was already playing, causing doubling up sometimes.
3. If you used seek(0), in some cases getCurrentFrameTime could return a negative value (as it returns frame - frameinterval), and in those cases the audio would not play properly (usually not at all). This seemed to be latency-based and …
=> Fix for audio glitch

psychopy/sound/backend_sounddevice.py
From my testing of the new sounddevice backend there was no volume parameter being applied to the sound output from sounddevice for either Frequency or Array based sounds.
I have added these volume multiplication calls in https://github.com/gjcooper/psychopy/commit/a3b6dcb26c3a82bb0ec63f0d1079397065369936, however if there is a more appropriate place to apply them I am willing to change it.
From my local testing the changes do apply the correct volume settings.
_Additionally_, while I was working in the `_setSndFromArray` method I noticed a call that was duplicated (at the method level and within an else block. I have removed this in https://github.com/gjcooper/psychopy/commit/3ea295409446e33319b7fd1cfe216ba95ead8eca and it does not seem to change functionality at all.
Cheers
Gavin
=> Add volume to sounddevice Frequency and Array calls

psychopy/sound/backend_sounddevice.py
Following on from the discussion in a previous pull request: https://github.com/psychopy/psychopy/pull/1378 I have finally had a chance to test implementation of the volume for the sounddevice backend within the callback on the `_SoundStream` object.
This involves reverting volume changes introduced in the previously merged pull request and adding an extra line in the callback.
Another option would be to apply it to the block (in `_nextBlock`) **just** before returning it to the callback method - which as far as I can see would have the same effect, and could be argued is a more natural place for it to be.
I have done some testing and have verified that the pull request as it currently stands works locally.
=> Move volume calls to callback function (sounddevice backend)

docs/source/general/timing/detectingFrameDrops.rst, psychopy/info.py, psychopy/visual/window.py, psychopy/visual/windowframepack.py
`visual.Window._refreshThreshold` must be modified by the users to fine-tune checking for dropped frames when using `Window.recordFrameIntervals = True`. It is used for no other purpose and should therefore be public. This PR renames the attribute to `visual.Window.refreshThreshold`, making it part of the public API.
=> RF: Make Window's refreshThreshold public

docs/source/coder/coder.rst, docs/source/coder/globalKeys.rst, psychopy/app/preferencesDlg.py, psychopy/demos/coder/basic/global_event_keys.py, psychopy/event.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec, psychopy/tests/test_events/test_keyboard_events.py, psychopy/tests/test_misc/test_event.py
Having to check manually for keypresses to abort the experiment is cumbersome and error-prone; and I often forget to add this feature for parts of my code and have to resort to the OS task manager to kill the PsychoPy fullscreen window if I need to quit my experiment prematurely.
This PR adds the ability to specify a _shutdown key_ in the preferences, which will then be checked for during all `event._onPygletKey()` invocations. `event._onPygletKey()` is the pyglet window's keyboard event handler. These events are dispatched on each `flip()` and during `wait()` periods when using `wait(X, hogCPUperiod=X)`. If the shutdown key is pressed, a `CRITICAL` event will be logged, and `core.quit()` will be called.
The PR is to be considered a proposal and is up for discussion. Please let me know …
=> NF: Global Keyboard Events

psychopy/data.py, psychopy/tests/test_data/test_StairHandlers.py
`StairHandler.nReversals` should never be `None`, but be set to a value equal to or greater than the length of the `stepSizes` parameter. Otherwise, we will finish the staircase prematurely during `calculateNextIntensity()`. 
This closes #1342.
=> BF: StairHandler.nReversals must not be None

buildCompleteInstaller.nsi, docs/source/coder/coder.rst, docs/source/coder/globalKeys.rst, psychopy/CHANGELOG.txt, psychopy/app/builder/components/envelopegrating/__init__.py, psychopy/app/builder/components/grating/__init__.py, psychopy/app/preferencesDlg.py, psychopy/data.py, psychopy/demos/coder/basic/global_event_keys.py, psychopy/event.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec, psychopy/sound/backend_sounddevice.py, psychopy/tests/test_app/test_builder/componsTemplate.txt, psychopy/tests/test_data/test_StairHandlers.py, psychopy/tests/test_events/test_keyboard_events.py, psychopy/tests/test_misc/test_event.py
I had accidentally added a second copy of the allowedVals param to the blendMode attribute
Unfortunately which adding this commit I got the history order messed up (with an erroneous use of --rebase). Sorry!
=> FF: bug with grating/envelope component params in builder

psychopy/event.py, psychopy/tests/test_misc/test_event.py
`event.waitKeys()` always used to clear the keyboard buffer implicitly. This PR adds a new keyword argument to control this behavior explicitly.
=> NF: Allow to disable keyboard buffer clearing in waitKeys()

psychopy/visual/basevisual.py, psychopy/visual/window.py
Fixes #1412 
Note, I moved the switching logic to the window class as a new method. The stereoscopy libraries need to override window switching logic to work correctly for some display types. Making this change will allow existing psychopy stimuli to be drawn stereoscopically using the `stim.draw(win)` syntax, providing greater compatibility.
=> Bind the window's FBO after switching to that window.

psychopy/app/builder/components/keyboard/__init__.py, psychopy/app/builder/components/settings/__init__.py, psychopy/app/builder/experiment.py
add psychoJS support for nReps and
sequential/random/fullRandom trial sequences.
Add columns from conditions files to data output.
Make loops marked as “isTrials” cause a data line
to be written each iteration. Add an “eventName”
column to the data file to identify whether a data
line was caused by a keyboard event or a loop iteration.
write out experiment data when quitPsychoJS() is called.
This commit goes with the one with the same name in the
psychojs project
=> nReps and sequential/random/fullRandom

psychopy/tools/monitorunittools.py
Following codes convert contents of _points_ to other units and re-convert to original units.
```
import psychopy.monitors.calibTools
from psychopy.tools.monitorunittools import cm2deg, deg2cm, deg2pix, pix2deg
points = [[-4.0, 4.0],
[ 0.0, 0.0],
[ 4.0,-4.0]]
monitor = psychopy.monitors.calibTools.Monitor('test', width=55, distance=60)
monitor.setSizePix((1920,1080))
print '====== deg2cm -> cm2deg======'
p1 = deg2cm(points, monitor, correctFlat=False)
p2 = cm2deg(p1, monitor, correctFlat=False)
print 'deg2cm\n', p1
print 'cm2deg\n', p2
print '====== deg2pix -> pix2deg======'
p1 = deg2pix(points, monitor, correctFlat=False)
p2 = pix2deg(p1, monitor, correctFlat=False)
print 'deg2pix\n', p1
print 'pix2deg\n', p2
print '====== deg2cm -> cm2deg (correctFlat)======'
p1 = deg2cm(points, …
```
=> BF: cm2deg returns wrong value when correctFlat=True

psychopy/app/builder/components/text/__init__.py
The units parameter was being given additional quote symbols
leading to a syntax error (only happened when not inheritting
from default so wasn't noticed before)
=> BF: Builder PsychoJS code for text components formatted badly

psychopy/app/builder/components/keyboard/__init__.py, psychopy/app/builder/components/settings/__init__.py, psychopy/app/builder/experiment.py
The “eventName” column in the data file is not
needed or meaningful since now only one line is
written to the data file for each iteration of a
“trials” loop.
Also, call the trialhandler’s updateAttributesAtBegin()
function in the recordLoopIteration() function that
is scheduled at the end of each iteration of a “trials”
loop instead of in the routineStartJS code.
=> PsychoJS - remove EventName column from data file

buildRelease.py
Here are some small tweaks for the ``psychopy/versions`` deploy script. This uses universal ``du`` commands (``-k`` instead of ``-b``) to accompate the BSD version of ``du``  in MacOS, and removes unnecessary quotes around the version number in tag and commit messages. Finally, there are some small PEP8 formatting updates as well.
=> Bf use version deploy tweaks

psychopy/app/stdOutRich.py, psychopy/event.py, psychopy/monitors/calibTools.py, psychopy/visual/elementarray.py, psychopy/visual/grating.py, psychopy/visual/image.py, psychopy/visual/radial.py, psychopy/visual/secondorder.py, psychopy/visual/shaders.py, psychopy/visual/text.py
Also, the string module in PY3 no longer has .lowercase attribute
but both PY2 and PY3 have .ascii_lowercase so we use that now
=> RFpy2and3: several places where we need bytes instead of str

psychopy/visual/filters.py
Corrects an error in butter2d_lp_elliptic where x and y co-oridinates were inappropriately multipled by 2. 
Adds a function to make 2D Gaussian profiles given a grid, 2 means and 2 standard deviations. Will cope with just one mean or SD.
=> BF & ENH Corrects error in butter2d_lp_elliptic and adds 2d Guassian

psychopy/visual/noise.py
I offer this stimulus class for generating visual random noise stimuli of various kinds. There are 4 main classes. Pixel based, Gabor element based, Filtered noise, and Coloured noise. Pixel based can have grey levels distributed according to binary, normal of uniform distributions. Gabor based can be oriented or isotropic. Filter based used Butterworth filtered white noise. Coloured noise allows gives the noise a skewed spatial frequency spectrum and includes white noise and noise derived from the spectrum of an image - this tool randomises the phase spectrum of the image. I’m not 100% sure about using the term coloured noise. I’ve used it as the technical terms for not flat spectra mostly use colour names: pink-noise being the most common. But is might be confused with noise that …
=> ENH: Stimulus class for generating random noise stimuli

psychopy/demos/coder/iohub/eyetracking/selectTracker/eyetracker_configs/iviewx_config.yaml
This tab character threw an error when trying to run some SMI ioHub
demos. This was one of the issues noted previously in
https://github.com/psychopy/psychopy/issues/1372
=> BF: fix typo in ioHub YAML config file

psychopy/visual/noise.py
Add catches to prevent user from drawing an un drawable stimulus in the buffer and to stop runtime errors.
Add notes to documentation header about the risks of setting noise frequencies too high.
=> BF: Add error catches

createInitFile.py, psychopy/__init__.py
We used to `raise` if `configobj` could not be found (on Python 3 installations). However, recent versions of `configobj` do support Py3, so there's no need to raise anymore.
Further, this PR contains a small number of style fixes (PEP8-compat).
=> Small cleanups, Py3 compat

createInitFile.py, psychopy/__init__.py
I think future and configobj are imported pre-`setuptools.setup`, leading to `ImportError`s because they haven't yet been installed.
Example (applies to python 2 and 3, just switch `python=2.7` to `python=3.6`):
```shell
conda create --name py27 python=2.7 numpy scipy -y
activate py27
pip install git+https://github.com/psychopy/psychopy
#Collecting git+https://github.com/psychopy/psychopy
pip install git+https://github.com/aforren1/psychopy@preinstall
```
=> FF: Allow pass on missing configobj/future during install.

psychopy/data/trial.py
This PR fixes Python 3 support for `data.TrialHandler.__str__()` and `data.TrialHandler2.__str__()`
`str(type(getattr(self, attrib)))` returns:
- `"<type 'instancemethod'>"` for Python 2
- `"<class 'method'>"` for Python 3
We sent Python 3 into an infinite loop with the previous code when  requesting the string representation of a `TrialHandler` or  `TrialHandler2` object. This is fixed now.
=> BF: Fix string representation for Python 3

psychopy/app/builder/components/keyboard/__init__.py, psychopy/app/builder/components/mouse/__init__.py, psychopy/app/builder/experiment.py, psychopy/data/trial.py, psychopy/event.py, psychopy/info.py, psychopy/tests/test_app/test_builder/componsTemplate.txt, psychopy/tests/test_data/test_TrialHandler2.py, psychopy/visual/image.py, setup.py
Mouse component now has new params:
- "clickable stimuli": a list of stimuli that we can register as clicked
- "store params for clicked": e.g. store the name, and the stimulus text/image/color etc
- "new clicks only": checks if button is down *and wasn't on previous frame*
and some changed params:
- "End routine on press" now supports choice options "never" (equivalent to previous False), "any click" (equivalent to previous True) and "valid click" (new option, only finish if they clicked one of the listed stimuli)
=> Mouse from Builder supports "clickable" stimuli (virtual buttons)

psychopy/event.py
fixes issue reported on discourse:
https://discourse.psychopy.org/t/mouse-getpos-doesnt-reflect-recently-set-mouse-setpos/2850/2
=> BF: pyglet shifted mouse but didn't store updated position

psychopy/data/base.py, psychopy/data/experiment.py, psychopy/data/staircase.py, psychopy/data/trial.py, psychopy/tests/test_data/test_ExperimentHandler.py, psychopy/tests/test_data/test_StairHandlers.py, psychopy/tests/test_data/test_TrialHandler.py, psychopy/tests/test_data/test_TrialHandler2.py, psychopy/tests/test_data/test_TrialHandlerExt.py, psychopy/tools/filetools.py
This PR consists of two improvements:
1. it  implements the `__eq__()` and `__ne__` (`==` and `!=`) methods for `DataHandler` and `_BaseTrialHandler`(and derived classes)
2. it adds JSON serialization for StairHandler and derived classes
Example:
```python
In [1]: from psychopy.data import TrialHandler
...:
...: t1 = TrialHandler([dict(foo=1)], 2)
...: t2 = TrialHandler([dict(foo=1)], 2)
...:
...: print(t1 == t2)
...:
True
```
Specializations were required for
- `TrialHandler2`: ignore RNG object
- `QuestHandler` and `PsiHandler`, as they use contrib classes (see below).
`QuestHandle`r and `PsiHandler` rely on classes implemented in contrib modules; these should be left unchanged. Because an `==` or `!=` comparison on two `QuestHandler` / `PsiHandler` instances will eventually descent …
=> Add == and != operators for DataHandler and _BaseTrialHandler, and JSON export for staircases

psychopy/app/builder/components/cedrusBox/__init__.py
Attempting to utilize a cedrusButtonBox response in the Builder view results in the error:
**_AttributeError: 'ResponseDevice' object has no attribute 'status'_**
Unlike classes like KeyBoardComponent, cedrusButtonBoxComponent does not have a corresponding response class in which the status attribute is initialized. However, the status attribute is still necessary for the experiment script to run, hence the changes.
=> BF: Add status attribute in CedrusBox script generation

psychopy/app/localization/__init__.py
PsychoPy application crashes on Python 2.7 because translated strings are not output in unicode.
unicode=True is necessary to output translated string in unicode in Python2.
See also [https://discourse.psychopy.org/t/code-name-window-size-on-mac/2939](url)
=> FIX: gettext.install() needs unicode=True in Python2.

psychopy/gui/qtgui.py
`isinstance` is used to check if `thisType` is an instance of `basestring` in this case, `thisType` is a class itself, not an instance of a class. If `thisType` is `<type 'unicode'>`, then using `isinstance(thisType, basestring) returns False- which appears to not be the intended function. However using `issubclass(thisType, basestring) returns True because `unicode` is a subclass (not an instance) of basestring.
=> Update qtgui.py handleLineEditChange fxn

psychopy/core.py, psychopy/data/experiment.py
I've implemented a clean up system via an ExperimentHandler variable that keeps track of all instances of the class, then calling their `.close()` methods manually prior to shutting down threads.
Fixes the underlying issues discussed in: #1497
=> BF: Fix Garbage collector reliance for ExperimentHandler clean up in core.quit()

createInitFile.py
In the template, `from psychopy.tools.versionchooser import useVersion, ensureMinimal` was inside of a for loop, which caused the statement `from psychopy import useVersion` to fail in a separate script. Fixing the indentation in the init template fixes this issue.
=> FF: psychopy.tools.versionchooser in for loop

psychopy/visual/movie2.py
opencv returns `self._video_stream.get(cv2.CAP_PROP_FRAME_WIDTH)` (and height) as a float. This causes an error a few lines down in
`self._numpy_frame = numpy.zeros((self._video_height, self._video_width, self._video_frame_depth),  dtype=numpy.uint8)`
By changing these variables to integers, this error does not occur.
See: #1509
=> BF: self._video_height/width should be int, not float

psychopy/visual/basevisual.py
Correcting an embarrassingly trivial bug in my last commit that was breaking drawing to multiple windows when passing a window other than its parent to draw(). 
Cause: _selectWindow() was ignoring its 'win' argument preventing stimuli from being drawn windows other than it's parent. This was due to self.win._setCurrent() being called rather than the _setCurrent() method of the 'win' passed to _selectWindow().
Fix: Changed self.win._setCurrent() -> win._setCurrent(), closes issue #1513
=> BF: Fixed _selectWindow() ignoring 'win' argument

psychopy/core.py, psychopy/data/experiment.py
In correspondence with #1497 I've replaced the old fix for this solution: keeping track of ExperimentHandlers manually with weakref, then manually calling the each instance's `.close()` method in `core.quit()` 
with a new, cleaner fix: use `atexit` to register each instances `self.close` method to be called on interpreter exit before garbage collection. This does fix the same issue that the original weakref patch was working towards.
=> FF: atexit solution in favor for closing ExperimentHandlers

psychopy/data/trial.py, psychopy/tests/test_data/test_TrialHandler2.py, psychopy/tools/filetools.py
We now support JSON export of `TrialHandler2` and all staircase procedures.
`TrialHandler` and `TrialHandlerExt` are not supported because their required `DataHandler` proves to be difficult to serialize.
=> NF: Add JSON serialization for TrialHandler2

psychopy/data/experiment.py
- Don't hard-code CSV field separator when saving CSV through `ExperimentHandler.close()`
- Update docstring
- Small style fixups along the way
=> FF, DOC: Don't hard-code CSV field separator in `ExperimentHandler.close()`

psychopy/tests/test_all_visual/test_all_stimuli.py, psychopy/tests/test_all_visual/test_contains_overlaps.py, psychopy/visual/line.py
The `contains()` and `overlaps()` methods of `visual.Line` had a different signature than their parent (accepting no arguments), essentially being useless and violating [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle). We now consume all passed (keyword) arguments, fixing this problem. We also explicitly return `False` now, as has always been indicated by the docstrings. Added tests for this behavior. While at it, I additionally cleaned up the test scripts a little bit to improve readability.
=> BF: Line.{contains,overlaps}

psychopy/sound/backend_pyo.py
For some users it seems that
```
devName = dev['name'].decode(osEncoding)
```
Spits a decode error and `dev['name']` claims already to be a unicode
object (so shouldn't need decoding). It isn't clear why, but it looks
like portaudio on some systems returns a bytes string and on some
returns a unicode object!?
=> BF: an attempt to fix further unicode issues with audioLibs

psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec
'sounddevice' was missing from `baseNoArch.spec`/`general`/`audioLib` list. I've added it in, and used generateSpec.py to update the rest of the `.spec` files.
See #1529
=> BF: Added 'sounddevice' to all audioLib vars in `.spec` files

psychopy/app/builder/experiment.py
7d499265bca introduced some bugs:
- experiment.py now needs to import OrderedDict to load variables of that
- we can't do `word = thisTrial.word` any more
we need `word = thistrial['word']` now
=> FF: fixes needed as result of OrderedDict change

psychopy/data/utils.py
psychopy.data.getDateStr() returns non-ASCII characters on Python2, which causes exception when compiling Builder experiment.
Please see #1543 for detal.
=> FF: non-ASCII characters in date string causes exception on Python2

createInitFile.py, psychopy/__init__.py, psychopy/monitors/calibTools.py, psychopy/tests/test_monitors/test_monitors.py, setup.py
- Better handling of preferences import during installation.
- Use install-only variable to determine whether or not to skip preferences import in `psychopy/__init__.py`. The previous way I tried (in #1480) wasn't ideal.
- Added `pypiwin32` as dependency on Windows.
- Open json monitor calibration file with 'r', rather than 'rb'.
- I get a `TypeError: the JSON object must be str, not 'bytes'` on a Windows 10 machine, current psychopy master, python 3.5, when trying to load the default `testMonitor.json`. However, the problem was fixed in python 3.6 (I think https://bugs.python.org/issue10976?).
=> RF/BF/FF: Imports during installation, Windows requirements, and loading json calibration files

psychopy/visual/window.py
The `AttributeError` didn't get caught as it was superseded by the `Exception`, which was caught right before. Changed to order of `except` blocks to fix this.
=> ENH: Catch AttributeError during avbin import

psychopy/iohub/devices/serial/__init__.py
Attempts to resolve issue #1309 by increasing the number of hardcoded hardware buttons from 5 to 7.
=> BF: Supported light and voice keys by increasing hardware button limit

psychopy/app/psychopyApp.py, psychopy/core.py, psychopy/tests/test_misc/test_core.py
This PR
- fixes `core.shellCall()` for Python 3, which did not work before (NB: min. required version: 3.6 – allows to re-use most of the existing Python 2 code unchanged, which is not the case for earlier Python 3 releases)
- allows users to pass environment variables to programs executed via `shellCall()`
- ensures `psychopyApp.py` is run through `pythonw` on macOS with Anaconda (closes #1326)
=> Fixes for shellCall(), and  improvements to psychopyApp.py on macOS with Anaconda

psychopy/app/connections.py
This addresses issue #1443 , which I think was a twofold issue. The first was a simple bug in connections.py, where the latest version isn't expanded properly when checking if the install is up-to-date.
The second is that self.latest is fetched from http://www.psychopy.org/version.txt, which at the moment is 1.85.3. There was no handling for when the running version is actually higher than this. I'm not sure if this is a situation that is intended to happen, or if the version.txt page is just out of date. The [intstallation instructions](http://www.psychopy.org/installation.html) recommend installing 1.85.4.
I've added some handling so that the message "You are running PsychoPy ([VERSION]), which is ahead of the latest official version ([VERSION])" is displayed when this occurs. It may be …
=> BF: psychopy updates shouldn't suggest 'updating' to older version 

.travis.yml, .travis_coveragerc, conda/environment-2.7.yml, conda/environment-3.6.yml, conda/gen_environment.sh, psychopy/demos/coder/stimuli/MovieStim2TimingTest.py, psychopy/iohub/devices/eyetracker/hw/smi/iviewx/eyetracker.py, psychopy/tests/dummy_xorg.conf, requirements_travis.txt, setup.py
I expanded our testing (Travis) setup to use Anaconda for setting up Python 2.7 and 3.6 environments, and tuned some tiny bits and pieces here and there.
This PR:
- Now also tries to build & install PsychoPy, instead of simply running the tests on the downloaded source tree
- Adds Anaconda testing environments for Python 2.7 and 3.6, while preserving our previous test setup. That is, we now have a testing matrix that includes non-Anaconda 2.7, Anaconda 2.7, and Anaconda 3.6
- Fixes bugs in `iohub` and the `MovieStim2` demo
I don't know if all dependencies for properly testing on Python 3 are actually installed, because obviously `pytest` fails quite early. We'll now just have try and fix the Python3 show stoppers one by one, and add additional required packages whenever needed.
As a next …
=> TESTS: Add Anaconda builds & tests for Python 2.7 and 3.6

psychopy/iohub/datastore/__init__.py, psychopy/iohub/datastore/util.py
As per this issue #1548 ioHub/datastore needed an update to be compatible with the PyTables API version > 3.x
* I've removed the `from tables import *` statements and added explicit imports, to make the files easier to debug.
* Rather than checking PyTables version on every API call, I do the check once after the import statements and use `getattr` for all API calls, as I found that more elegant - not sure what you think.
* I haven't included any tests yet, as this may take a little longer, I only tested with my local set-up and serial device (successfully)
* I've also added some white space around operators and fixed some other Pep8 formatting issues, not sure if this is wanted (do you follow another code style guide?)
In terms of testing, please let me know how to proceed. I plan on …
=> Fix: updated PyTables API in ioHub/datastore

.travis.yml, conda/environment-2.7.yml, conda/environment-3.6.yml
We can now test both wxPython 3 and 4 on Python 2.7 on Travis; wxPython 4 is allowed to fail.
Additionally, I've added test support for openpyxl 2.5, which has some breaking API changes; naturally, these tests are allowed to fail as well.
=> TESTS: Add Travis tests for wxPython 4 and openpyxl 2.5

psychopy/data/staircase.py, psychopy/tests/test_data/test_StairHandlers.py
The "initial rule"  disregards user-specified n-up/n-down settings and performs a 1-up/1-down staircase until the first reversal point is found. This commit introduces a new keyword argument `applyInitialRule` that can be used to alter this behavior.
=> ENH: Allow users to disable the "initial rule" of StairHandler

psychopy/iohub/constants.py, psychopy/iohub/devices/display/__init__.py, psychopy/tests/test_hardware/test_ports.py, psychopy/tests/test_iohub/testutil.py, psychopy/visual/window.py
I stumbled over this when running an ioHub example on linux/pthon3 and realized, that many `sys.platform` checks are already conducted with `sys.platform.startwith('linux')` while some still tested for `linux2` only.
I did not update the occurrence in `psychopy/tests/test_hardware/test_ports.py`, so that test will mock the version to `linux2` which should be okay for testing, if I understand correctly.
=> BF: sys.platform comparison for linux/python3 in some files

psychopy/sound/_base.py, psychopy/sound/backend_pyo.py, psychopy/sound/backend_sounddevice.py
Revised the documentation to explain that arguments named 'hamming' are preserved even though the apodize function now uses a Hanning window instead.
=> BF: Cleaned up documentation

psychopy/app/connections.py
closes #1443
A further safety check for version comparison. The main fix had
already been provided in #1567 but this adds the extra security
of using `parse_version()`. '1.90.0a1' is > '1.90.0' al[habetically
but in version syntax would be the preceding alpha release (i.e.
should be considered less than 1.90.0)
=> ENH: use parse version in version checking of psychopy itself

psychopy/demos/builder/images_blocks/blockedTrials.psyexp
Changed image stimulus units from `pix` to `height` so that the image stimuli display correctly (with a size of (0.5, 0.5), they were invisible with pixel units).
=> BF: incorrect units in images_blocks Builder demo 

.travis.yml
openpyxl was previously not required to pass
=> TESTS: we're now compatible with openpyxl 2.5 so always test that too

psychopy/app/builder/experiment.py, psychopy/data/utils.py
Following bugs are fixed:
1. Builder cannot open condition file when non-ASCII characters are included in the file path in Python2.
2. Builder cannot save experiment when non-ASCII charcteers are included in "Text" field of TextComponent in Python2.
Please see #1608 for detail of error messages.
=> BF: Builder crashes due to non-ASCII characters in path of condition file and TextComponent in Python2

psychopy/visual/movie3.py
A handful of bug fixes and upgrades to allow for future sounddevice implementation (currently not stable enough to use, sadly).
Bugs fixed:
Previously, seek(0) would sometimes act like a negative value and cause a crash by trying to find either a nonexistent frame or nonexistent point in the audio stream [partly due to getcurrentframetime subtracting the frame interval...which makes sense except when you seek(0)] Checks have been added to ensure that any attempt to seek to a negative value lands you at 0, for either audio or video.
Seeking while paused could double your audio stream or create other audio bugs. Moving the movie status update when using "play" and checking it when audioseeking prevents this. 
A further check has also been added to stop the program from attempting to play …
=> BF: movie3 seek behavior + audio

psychopy/app/_psychopyApp.py, psychopy/app/builder/builder.py, psychopy/app/coder/coder.py
Following bugs are fixed.
- Splash window doesn't close automatically
- Coder experiment doesn't start when Run button is clicked.
- Status of Run/Stop is not updated when Builder experiment is terminated.
- Python crashes when Stop button is pressed during experiment in Builder.
Coders were tested on:
- winpython2.7.10 x86, wxpytho3.0.2
- winpython2.7.10 x86, wxpython4.0.0b2
- winpython3.6.1 x64, wxpython4.0.0.b1
=> FF: fixing bugs with closing splash and running experiments in Windows wxPython4

psychopy/app/builder/components/unknown/__init__.py, psychopy/app/builder/dialogs/dlgsConditions.py, psychopy/app/builder/experiment.py, psychopy/app/coder/coder.py, psychopy/data/trial.py, psychopy/data/utils.py, psychopy/demos/builder/branchedExp/branching.psyexp, psychopy/demos/builder/mental_rotation/MentalRot.psyexp, psychopy/event.py, psychopy/gui/wxgui.py, psychopy/visual/ratingscale.py
I've fixed several compatibility issues with Python3 and wxpython4.  I think I should send pull request before making further modification.  Following issues are fixed.
- Builder
* StaticPeriod component doesn't work because `psychopy.clock` is not imported.
* branchingDemo doesn't work due to inappropriate initial value in expInfo dialog in Python 3.
* **Custom codes in mentalRot demo are incompatible with Python 3 (e.g. print sentence).**
* .pkl condition file can't be read in Python 3.
* Conditions dialog can't be opened in wxpython 4.
* Layout of condition dialog is odd in wxpython 4.
- Coder
* Coder can't reload file when the file is modified outside of PsychoPy due to encoding in Python 3.
- General
* Pyglet recognizes `0xFF0D` as `'enter'` in Python 3 **(maybe …
=> FF: fix compatibility issues with Python 3 and wxpython 4

README.md
Old link in PyPI badge was to Travis-CI instead of to PyPI
=> Fix link in PyPI badge

.travis.yml, psychopy/app/_psychopyApp.py, psychopy/app/builder/builder.py, psychopy/app/builder/components/settings/__init__.py, psychopy/app/builder/dialogs/__init__.py, psychopy/app/builder/experiment.py, psychopy/demos/builder/iohub/stroop_eyetracking/stroop.psyexp, psychopy/demos/builder/iohub/stroop_keyboard/stroop.psyexp, psychopy/demos/builder/mental_rotation/MentalRot.psyexp, psychopy/iohub/datastore/pandas/__init__.py, psychopy/iohub/util/__init__.py, psychopy/tests/conftest.py, psychopy/tests/data/test001EntryImporting.psyexp, psychopy/tests/test_app/test_builder/test_Experiment.py, psychopy/tests/test_gui/test_DlgFromDictQt.py, requirements_travis.txt
Python3 doesn't allow 001 as a valid value and this was used in our
demos. The new code in dialogs.__init__ handles that
Also, dialogs .show() now accepts a timeout for use with testing
so we can now simulate pressing OK after showing a dialog even
with ShowModal()
=> TESTS and FF: PsychoPy now fixes its demo 001 issues for Py3 compat

.travis.yml
Also anaconda is working. All 5 environments are now required to pass.
Thanks to @hoechenberger, @hsogo (and all the @psychopy/coredev) for their help getting us here.
I do not for a moment think that this is all the compatibility bugs fixed, but it's a really big step!
=> Test suite fully passed on Py3 / wx4 / openpyxl2.5

psychopy/app/builder/dialogs/__init__.py
Builder's Component Properties dialog closes immediately after opened, and Loop Properties dialog cannot be opened due to lack of `timeout` attribute.
=> FF: Fix for timeout feature of Builder Dialog

.lgtm.yml
@boazmohar pinged us on the lgtm.com forums (https://discuss.lgtm.com/t/unable-to-build-psychopy/777). [I see](https://discourse.psychopy.org/t/static-code-analysis/3369) that you've been using [our analysis](https://lgtm.com/projects/g/psychopy/psychopy) results to improve PyschoPy — glad it's useful to you!
Recent changes (I think 38e87ce and/or 8d4d08f) to setup.py in PsychoPy meant that lgtm.com could no longer analyse the project due to some missing dependencies. We're working hard to improve the automatic detection and installation of dependencies, but in the meantime I've put together this configuration file that will give lgtm a nudge in the right direction. If you require more dependencies in the future, it's best to add them to this file. At the moment, lgtm uses the [Travis …
=> Configuration file to re-enable lgtm.com analysis

psychopy/visual/ratingscale.py
The fix ensures tick labels of 0 or False are drawn, but
None labels are skipped. Fixes #1648
=> BF: Fixes tick label in visual.RatingScale

conda/environment-2.7.yml, conda/environment-3.6.yml, requirements_travis.txt, setup.py
It was just 3.11.0-3.11.1 that wzs broken? Version 3.11.2 is the current
default install and that works fine
=> FF: json_tricks upstream is now fixed so relax version requirement

psychopy/app/_psychopyApp.py, psychopy/localization/__init__.py
localization should not set up the wx.Locale it should provide a function
so that the app can do this when it's ready (not necessarily during import)
This means the app doesn't have to exist in order for translation to work
which means we can now import/export experiments without needing a wx.App
=> ENH: don't require wx App in order to translate to locale

psychopy/app/coder/coder.py, psychopy/sound/backend_pyo.py
**1.** Coder can't open file which contains non-ASCII characters in Python 3 on OS whose default encoding is not UTF-8 (e.g. Windows).  Encoding (utf-8) must be specified to open such file in Python 3.
**2.** Coder can't paste text which contains non-ASCII characters in Python2. The variable `txt` in line 1126 of coder.py is unicode. So we have to  use `encode()`, not `decode()`.
**3.** Script that imports `psychopy.sound` causes RuntimeError when the script is finished when audio library is pyo and running on Windows10.  I experienced this error with pyo 0.8.8 in both of python 2 and 
Following single line is enough to replicate this phenomenon.
```
import psychopy.sound
```
This error doesn't occur when pyo 0.8.8 is directly imported (i.e. `import pyo`).  I investigated this issue and …
=> FF: Coder can't open/paste text including non-ASCII characters

docs/source/api/iohub/starting.rst, psychopy/visual/window.py
The ioHub server was previously changed renaming `registerPygletWindowHandles` to `registerWindowHandles` and `registerPygletWindowHandles` to `registerWindowHandles`: https://github.com/psychopy/psychopy/commit/55bbce6cab50d2ec1cc7661240cb8a8f26b74f32
This fixes a remaining reference to the old function names that otherwise causes a crash.
Issue appears to be present in 1.85.6
=> [BF] Replace registerPygletWindowHandles with registerWindowHandles

psychopy/hardware/bbtk/__init__.py, psychopy/hardware/cedrus.py, psychopy/hardware/crs/bits.py, psychopy/hardware/crs/colorcal.py, psychopy/hardware/minolta.py, psychopy/hardware/pr.py, psychopy/hardware/serialdevice.py
Serial devices were failing to communicate using Python 3. By default, Python 2 stores strings as bytes and Python 3 stores strings as unicode. As serialdevice communicates using bytearrays, Python 3 strings must to be converted to bytes before being sent to serialdevice.
=> RF: Adds serialdevice string-to-byte conversion for Python 3

psychopy/app/dialogs.py
With Python 3, adding new elements for experiment info in experiment settings dialogue box raises an attribute error with GBSizerItem. This commit fixes the bug by replacing btn.GetPosTuple() with btn.GetPos(). No issues raised.
=> BF: Fixes add bug with experiment settings dialogue.

docs/source/installation.rst
pysounddevice does not exist on PyPi, corrected the documentation
I'm not sure if it is by design but sounddevice does not appear in "...if you want **everything** available..." part?
=> DOC: corrected PyPi name, pysounddevice to sounddevice

psychopy/app/builder/builder.py, psychopy/experiment/components/__init__.py
Builder window crashes if `componentsFolders` is set to load custom builder components.  Error message is:
> Traceback (most recent call last):
>   File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\\_psychopyApp.py", line 487, in showBuilder
>     self.newBuilderFrame()
>   File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\\_psychopyApp.py", line 473, in newBuilderFrame
>     fileName=fileName, app=self)
>   File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\builder\builder.py", line 1098, in \_\_init\_\_
>     self.componentButtons = ComponentsPanel(self)
>   File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\builder\builder.py", line 727, in \_\_init\_\_
>     self.app.prefs.builder['componentsFolders'])
>   File …
=> FF: Custom builder components can't be imported

psychopy/hardware/crs/bits.py
My otherwise-behaving Display++ is unable to return the pixel values within the previous default timeout - leaving it stuck at the status screen.
=> ENH: reduce chance that Display++ will time out (video line)

psychopy/visual/aperture.py
Aperture would fail if provided a filename that contained upper case characters, because the argument is always converted to lower case.
Here, it checks that it is not a file before converting to lower case.
=> BF: allow Aperture to have uppercase letters in filename

psychopy/tests/test_app/test_builder/genComponsTemplate.py
genComponentsTemplate didn't know about the change!
fixes #1713
=> FF: fixed imports of experiment (moved out of builder) in test framework

psychopy/experiment/components/sound/__init__.py
This fix attempts to stop spectral splatter for short duration tones.
=> BF: Removes Sound.stop() code for short duration (2<secs).

docs/source/about/credits.rst, psychopy/clock.py, psychopy/localization/__init__.py
Before calling wx.Locale() the locale.getpreferredencoding returns 'utf-8'
Immediately after, it returns '' but that causes matplotlib to fail (it
expects to get some encoding or None but not ''). We work around that by
detecting the preferred encoding and then, if it gets set to '' we revert
it to the original
=> BF: fix problem with wx3.0 somehow overwriting the preferred encoding

psychopy/visual/window.py
effectively gave the screen one frame behind
See #1725 point number 5
=> BF: getMovieFrame('front') with useFBO=True returned wrong buffer

psychopy/visual/backends/gamma.py, psychopy/visual/backends/pygletbackend.py
The problem is how to convert a 4-byte value into an int, which is what
the 0xFFFFFFFF line was doing.
Instead, convert to int when returning the window handle from pyglet._dc
=> BF: the use of adding a hex in Py3 doesn't work

psychopy/tools/colorspacetools.py
New function to convert CIEL*a*b* to RGB values. By default the conversion is between CIELAB and sRGB (BT. 709). You can specify your own conversion matrices and white point if needed (CIE XYZ 1931 working space). Any reasonable array (Nx3, NxNx3) can be converted. Output is in PsychoPy signed RGB values. 
Someone once requested this feature on the message boards, https://discourse.psychopy.org/t/rgb-to-cielab-conversion/3662/6
=> NF: Added CIEL*a*b* color space conversion.

psychopy/monitors/calibTools.py
Routines to generate sRGB conversion matrices given the chromaticity coordinates (CIE-xy) of the display's RGB primaries and white point. The resulting matrix maps CIE-XYZ (1931) color coordinates to *linear* sRGB values. This function is required to use the new `CIEL*a*b*` color space tool correctly.
=> NF: sRGB conversion matrix generator

psychopy/visual/backends/glfwbackend.py
Made the GLFW backend use the createLinearRamp function instead of the placeholder routine. By far the most important feature, the PsychoPy logo is now used as the icon for GLFW windows.
=> RF: GLFW backend gamma and fluff

psychopy/visual/window.py
I added importing pyglet.media.sources for pyglet 1.3.
"Pyglet.media import avbin" causes import error,
because pyglet 1.3 has pyglet.media.sources.avbin instead of pyglet.media.avbin in pyglet 1.2 and 1.1.
The source of pyglet.media.sources.avbin of pyglet 1.3 
https://bitbucket.org/pyglet/pyglet/src/ab98c6b7478422acbf9b893f01c0e7778bc1ad9d/pyglet/media/sources/avbin.py?at=pyglet-1.3-maintenance&fileviewer=file-view-default
=> BF: Add importing pyglet.media.sources for pyglet 1.3

psychopy/visual/backends/gamma.py
#1736 changed the ramp type decision tree (commit https://github.com/psychopy/psychopy/pull/1736/commits/3adc3e033e14c83383d1a7ffa3222465ca958c4e). It wasn't correct initially, but I think the update incorrectly set the win32 and linux ramp types to 1 when driver info was provided. Here, I've tried to clarify the tree.
=> FF: gamma rampType logic

psychopy/hardware/serialdevice.py
```getResponse``` in ```serialdevice.py``` was passing the function rather than the function's result, if requested to get all the buffer contents.
=> BF: was passing function rather than returned value

psychopy/tools/colorspacetools.py, psychopy/visual/backends/glfwbackend.py
I finalized the style for specifying arbitrary transfer functions to color space conversion routines (so we don't need to ship all possible TFs) and wrote up some nicer docs. When I introduce additional color space routines, they'll all be structured similarly. Hopefully I can soon make CIELAB an actual working space for stimuli.
=> RF: Finalize CIELAB support and docs

psychopy/clock.py
When a `StaticPeriod` starts, the window's `recordFrameIntervals` is set to `False`. After completion, the previous value of `recordFrameIntervals` is restored. However, the order of statements in `StaticPeriod.start()` means that the initial value of `recordFrameIntervals` is always set to `False`, and _then_ saved. By saving before disabling, this initial value will be successfully restored in the future.
=> BF: Save recordFrameIntervals in StaticPeriod before disabling.

psychopy/iohub/client/__init__.py, psychopy/iohub/client/keyboard.py, psychopy/iohub/devices/keyboard/__init__.py, psychopy/iohub/server.py
The fixes are mainly specific to keyboard devices.
=> BF: Fixes ioHub compatiblity issues with Python 3.

psychopy/data/fit.py
I ran into the problem of needing to set bounds on parameters for a custom function I wrote (Weibull, with lapse rate), and this change makes that convenient within the normal psychopy framework.
=> ENH: Added option to pass other parameters to optimize

psychopy/iohub/constants.py, psychopy/iohub/devices/keyboard/darwin.py, psychopy/iohub/devices/keyboard/darwinkey.py
A few minor issues cropping up with iohub on Python 3:
1) trailing commas were causing a few of the keycodes to be represented as tuples, which was ignored in python 2 but in 3 gives:
```
TypeError: '>' not supported between instances of 'tuple' and 'int'
```
2) darwinkey needed to be a relative import
3) locals() returns a view in python 3, which means we can't change it when iterating over it. Explicitly creating a copy should preserve the old behavior.
=> BF: iohub python 3 compatibility

psychopy/visual/ratingscale.py
The existing rating scale only allows the user to change the Y-location of the rating scale upon instantiation of the rating scale object. Thus, if y-positioning is to be changed throughout the experiment, the rating scale must be re-instantiated. This new feature allows the user to change the y-positioning of the rating scale at any point during the experiment without the need to re-instantiate a rating scale object.
=> NF: function allows user to change Y position of rating scale.

psychopy/data/utils.py
The importConditions function uses Pandas to import data from csv or excel files. However, if a column header is empty, an incorrect Value Error is raised telling the user that column headers cannot contain punctuation or spaces. This is because Pandas names unnamed columns on import with names that contain spaces. To fix, unnamed columns are removed from the dataframe, assuming that columns are unnamed because the user does not want to use those columns in the experiment.
=> BF: Removes unnamed columns for data.importConditions.

psychopy/experiment/components/sound/__init__.py
When no duration is given, a ValueError is raised when the None string
is converted into a float. This fix changes the conditional statements
to set stopVal to -1 if no duration is given.
=> BF: Fixes sound component error when duration is None.

psychopy/app/_psychopyApp.py
Previously, we would always use the downloaded version of ffmpeg with imageio. We now only download if no already installed binary could be found. Closes GH-1805.
=> BF/RF: Only download ffmpeg if no local binary could be found

psychopy/visual/helpers.py
When specifying the color of shapes (circle/rectangle) using hex such as '#000000', this is converted to RGB tuple correctly using the `colors.hex2rgb()` function, but in the helper code, 1 is subtracted from the values, giving the wrong colors...
=> fixed color specification of shapes using hex

psychopy/app/coder/coder.py, psychopy/visual/backends/pygletbackend.py
Regarding the win.Close fix, a NoneType error was raised when repeated win.Close functions are called because the Windows device context is set to None on closure in the first instance, thus causing conversion of the device context to a screenID integer to fail in the second instance
=> BF: Fixes Coder URL decomposition, and win.Close error.

psychopy/info.py
The code was trying to sort by lower() which wasn't necessary and
hard to implement in a way that supports Py2 and Py3 together
fixes #1825
=> BF: print(RunTimeInfo()) not working due to unicode/str error

psychopy/app/preferencesDlg.py
If changes were made to audio devices in the prefs dlg, the preferences were overwritten by previous preferences when the apply button was used followed by Ok button. No other selections seem to be affected by this bug. Solution: remove redundant 'Apply' button.
=> BF: Ok button overriding saved prefs after Apply clicked.

psychopy/data/trial.py
Tiny change to document that the .data attribute of a `TrialHandler` is actually a `DataHandler` (a subclass of `dict`), rather than a standard dictionary, making it easier to understand why it has a `.add()` method and so on.
=> DOC: clarifying the type of the .data attribute

psychopy/sound/backend_sounddevice.py
This fixes the issue described at https://discourse.psychopy.org/t/sounddevice-issue-with-stream-started-at-beginning/
=> Don't try to be clever about filling the output buffer with zeros

docs/source/installation.rst
this pull requests documents on how to use plain ana/conda and pip install for `psychopy` no longer using Erik's binstar channel (which today seems to have some flaws not allowing installation to end properly). This is possible since `wxpython` and other dependencies can now readily be installed with `conda install` not using any additional channels.
=> installation with plain ana/conda packages

psychopy/monitors/MonitorCenter.py
In monitor center, the SimpleGrid class needs to increment the refcount when the refcounted object, in this case the GridCellFloatEditor, is assigned to multiple objects, in this case the cell editor objects that exist in the grid cell. See https://github.com/wxWidgets/Phoenix/issues/627 for explanation. Fixes #1827.
=> BF: Fixes refcount issue with monitor centre. Fixes #1827.

psychopy/hardware/crs/__init__.py, psychopy/hardware/crs/bits.py, psychopy/hardware/crs/crsTest.py
Adds functionality to send trigger pulses (all devices) including control of FE-1 goggles via the D25 connector.
Adds analog outputs (Bits# and some Display++ models).
Adds functionality to enable, disable and read RTBox style returns from the device (Bits# and Display++) and thus communicate with button boxes, including the CB6 IR button box.
Adds functionality to start, stop, and poll the device status (Bits# and Display++) and to read every status report or just changes in status. Includes ability to read the analog inputs on Bits# and some Display++ models.
Adds functionality to enable, disable and read touch screen events for Display++ models with a IR touch screen and to convert verbose event lists to shorter lists of more significant touch events.
Adds a DisplayPlusPlus class (just …
=> ENH: Add functionality for CRS display devices

docs/source/installation.rst
Updated python 2.7 for more explicit splitting between plain `conda`, `conda-forge` and `pypi`. Included the install for python 3.5.
Careful ! Did not test `psychopy`'s full functionality after install.
=> conda install for python 3.5

psychopy/tests/test_hardware/test_CRS_bitsShaders.py, psychopy/visual/window.py
Note, getpixel from the returned image object does not work if back buffer is used, or if full screen is used.
=>  BF: Amendments to JP fix to getRegionOfFrame - now working

psychopy/app/builder/builder.py, psychopy/app/coder/coder.py
Two issues are fixed.
1) Builder cannot generate script in Python2 if non-ASCII characters are included in path.  This was fixed by encoding path string into file system coding in Python2.
2) Builder uses Python2 to generate script even when Builder is running on Python3 in Ubuntu (16.04 LTS).  This is because compile is done by "**python** -m psychopy.scripts.psyexpCompile ...".  In Ubuntu commad line should be "**python3** -m ...".  My fix is based on `_runFileAsProcess()` in psychopy/app/coder/coder.py.
=> FF: Builder cannot compile script

psychopy/app/preferencesDlg.py, psychopy/sound/backend_pyo.py, psychopy/sound/backend_pysound.py, psychopy/sound/backend_sounddevice.py
I experienced the same error reported at [1.90.1 language localization locale](https://discourse.psychopy.org/t/1-90-1-language-localization-locale/4293).
There are some audio devices which have newline characters in their device name like below ('\r\n' follows 'Hands-Free%0').
`u'\u30d8\u30c3\u30c9\u30bb\u30c3\u30c8 (@System32\\drivers\\bthhfenum.sys,#2;%1 Hands-Free%0\r\n;(PLT_E500))'`
Such name causes "cannot be safely quoted" error in ConfigObj. 
To avoid this problem, '\r\n' in the name of audio devices should be removed.
=> BF: Preference cannot be saved if newline character is included in the name of sound device

psychopy/gui/qtgui.py
BF:
- `string.ato*` were deprecated in python 2.0, and removed >= 3.0. I replaced them with `float()`/`int()`, where appropriate.
RF:
- Simplified checks for existing QApplications (I don't think it's necessary to return anything if `qtapp` is global?)
- Removed extra casts to string (superfluous without the `string.ato*` calls?)
- Minor import cleanup
ENH:
- Robustified against existing QApplications, i.e. if there's already one created by something else, we'll use that one
minimal example for the BF (from docs):
```python
from psychopy import gui
info = {'Observer':'jwp', 'GratingOri':45, 'ExpVersion': 1.1, 'Group': ['Test', 'Control']}
dictDlg = gui.DlgFromDict(dictionary=info, title='TestExperiment', fixed=['ExpVersion'])
print(info)
#{'ExpVersion': 1.1, 'Observer': 'jwp', …
```
=> BF/RF/ENH for qtgui.py

psychopy/app/builder/builder.py, psychopy/experiment/_experiment.py
We thought we were fetching the parameter, but we were actually only
fetching the *name* of the parameter (which was never a filename obvs!)
=> FF: Builder params (e.g. images) weren't being found in resources

psychopy/visual/textbox/freetype_bf/__init__.py
Suggested fix for textbox that uses wx version of freetype found in the site-packages directory.
=> BF: Fixes failure to find freetype if not in system search path

psychopy/experiment/components/noise/__init__.py, psychopy/tests/test_app/test_builder/componsTemplate.txt
Changes the Blendmode entry in the noise component dialog to be drop down instead of text entry.
Brings this into line with other components.
=> RF: Change blendmode to dropdown in noise component

docs/source/recipes/builderTerminateLoops.rst
DOC: To prevent error :
if len(key_resp.keys) <1:
TypeError: Object of type 'NoneType' has no len()
As discussed in https://discourse.psychopy.org/t/error-feedback-has-syntax-error/1509 and https://groups.google.com/forum/#!msg/psychopy-users/jZDTXg8oXgY/8v94pS3YDQAJ
=> DOC: Update builderTerminateLoops.rst

psychopy/app/builder/dialogs/dlgsCode.py, psychopy/experiment/components/__init__.py
Code component was not correctly saving code in params when closing window with 'Both' selected
=> FF: Fix to dual panel code component

psychopy/experiment/components/sound/__init__.py
This was due to the use of getInitVal function being called and used to define
the sound name.
=> BF: Sound fix where filename variable not written on routine

psychopy/demos/coder/hardware/RiftHeadTrackingExample.py, psychopy/demos/coder/hardware/RiftMinimal.py, psychopy/visual/__init__.py, psychopy/visual/rift.py
This is the initial commit for Oculus Rift support for PsychoPy. See `demos/coder/hardware/Rift*` for basic examples on how to use the library. Requires PsychXR (https://github.com/mdcutone/psychxr) for hardware access and currently only supports Windows. PsychXR is limited to 64-bit Python 3.6, I'll build packages for 3.7 soon. For 32-bit support, people will need to build PsychXr themselves using the guide on its project page. 
@peircej Is there any objection to where the modules are placed in the PsychoPy file structure? Furthermore, are there issues around lazy loading the library with 'visual'? I added code which keeps the module from loading if PsychXR is not installed.
=> NF: Oculus Rift Support

psychopy/experiment/components/settings/__init__.py, psychopy/experiment/components/sound/__init__.py, psychopy/sound/backend_sounddevice.py, psychopy/tests/test_app/test_builder/componsTemplate.txt
This fix is specific to backend_sounddevice. The fix will raise an error
if channels in stream < data, because this causes problems when combining
the two arrays in the callback function. No problems if data file is mono and
stream is stereo.
=> BF: Fixes error raised when stream inits with fewer chans than data

psychopy/visual/movie3.py
add self._mov.close() to MovieStim3._uload, move self._unload() in MovieStim3.stop after logging code.
Calling self._mov.close() seems to prevent invalid handle error in call to
ffmpeg_reader in moviepy module.
See
https://stackoverflow.com/questions/43966523/getting-oserror-winerror-6-the-handle-is-invalid-in-videofileclip-function
=> add self._move.close()to MovieStim3._uload,

docs/source/developers/buildercomponent.rst, psychopy/visual/text.py
Previously, the bidirectional algorithm and Arabic reshaping were being applied in the wrong order when rendering Arabic text. We now do the reshaping step first. Hat tip to Dr Reza Shoorangiz for assisting with identifying and correcting this. Pyglet rendering of Arabic/Farsi text should now be correct for single lines of text. The pyglet issue with multi-line text flowing from bottom-to-top remains and is out of our control. There is a thread including that here: https://bitbucket.org/pyglet/pyglet/issues/202/add-support-for-alternate-directional-text
NB Online experiments via Builder's Javascript output correctly display Arabic automatically: the web backend handles all of that without any effort.
=> BF: fixed ordering of Arabic text reshaping and direction

docs/source/developers/buildercomponent.rst
Minor revisions to developer documentation on adding new components to Builder.
Updated some file path locations and added instructions for re-generating the `componsTemplate.txt` file needed for the Travis testing process when a new component is added to a pull request.
=> DOC: edit instructions on making Builder components

psychopy/demos/coder/hardware/RiftHeadTrackingExample.py, psychopy/demos/coder/hardware/RiftMinimal.py, psychopy/visual/rift.py
Calling "Rift.endSession()" crashes PsychXR since the last firmware update. I removed it for now and it appears to have no ill effect.
=> BF: Removed 'endSession' (Oculus Rift)

psychopy/visual/slider.py
With a slider I commonly expect that, once I have started dragging, I can move the mouse cursor away from the slider while dragging continues (and the slider updates accordingly). This commit adds this feature.
=> ENH: Allow Slider dragging outside of "valid" area

psychopy/CHANGELOG.txt, psychopy/demos/builder/ratingsNew/ratingsNew.psyexp, psychopy/experiment/_experiment.py, psychopy/visual/backends/glfwbackend.py, psychopy/visual/backends/pygamebackend.py, psychopy/visual/backends/pygletbackend.py, psychopy/visual/window.py
- writing of psyexp files now honors the order of component parameters
- fullscr can (sort of) be toggled (but we need to handle recreating the FBO as this is a resize)
- the newRating was set to forceEndRoutine for the ratings but should be set to false (they're all multi-rating demos)
=> various fixes

psychopy/tests/test_all_visual/test_slider.py, psychopy/visual/slider.py
Colleagues suggested that the default marker for `rating` was too big and that a larger marker for `slider` would look nicer. This PR adds the ability to adjust the marker size via a keyword argument.
Also included:
- `size` is now a readonly prop
- small style & doc cleanups, removed references to unused params
=> ENH: Allow adjustment of Slider's marker size

psychopy/tests/test_all_visual/test_slider.py, psychopy/visual/slider.py
PEP8 says consistency within a project is the #1 priority :-)
For info, the fact that in tests we do use methods like`test_marker_scaling_factor` is because pytest/nose didn't used to support methods written in camelCase.
=> RF: fixed incorrect code styling in #1949

psychopy/tools/gltools.py
The file 'gltools' contains OpenGL related helper functions. Notably functions for creating framebuffers to be used as off-screen render targets (including multisample FBOs). Having reusable code for these operations will come in handy for supporting a variety of stereo rendering routines. Everything was tested and seems to work fine, I've also fully documented the functions within.
=> NF: Add file gltools.py

psychopy/tests/test_all_visual/test_slider.py, psychopy/visual/slider.py
This was introduced in GH-1949, but after discussion decided to be superfluous, as one can simply set `Slider.marker.size` directly after `Slider` creation.
=> RF: Remove kwarg to adjust Slider marker size

psychopy/event.py, psychopy/tests/test_events/test_keyboard_events.py
Num Lock status seems to be "on" on Windows systems, leading to unexpected behavior. We now simply ignore Num Lock, don't consider it a valid user-specified modifier anymore. Closes GH-1792.
=>  RF, BF: Ignore Num Lock in global key events

psychopy/data/trial.py, psychopy/data/utils.py, psychopy/tests/test_data/test_TrialHandler2.py
`data.utils.importConditions()` returned a tuple of `fieldNames`, but `TrialHandler2` expects a list (so it can `.append()` to it).
=> BF: importConditions() should return list of fieldNames

docs/source/api/tools/rifttools.rst, docs/source/api/visual/rift.rst, docs/source/conf.py, psychopy/visual/rift.py
Set of Rift docs were missing a few commits, here are the rest. I also enabled support for NumPy style docstrings in the 'conf.py'.
=> DOCS: Rift doc fixes.

psychopy/visual/backends/glfwbackend.py, psychopy/visual/text.py
Made changes which allow the Pyglet text renderer to be used with GLFW. Seems to work fine after running a bunch of demos. Also fixed a bug where the depth of the stencil buffer was incorrectly set when opening a GLFW window. That made the 'allowStencil' argument produce unexpected results.
=> BF/RF: GLFW textstim and stencil buffer fixes

setup.cfg, setup.py
As we're using environment markers since GH-1959 now, the package dependencies can be moved to `setup.cfg`, further streamlining and clarifying `setup.py`.
=> PKG: Move requirements to setup.cfg

psychopy/tests/test_all_visual/test_gamma.py, psychopy/visual/backends/gamma.py
This relates to issue #1859.
The first problem was that, on windows, the gamma table that was read was not the same as the gamma table that was set. The set operation used a ```byteswap```, whereas the get operation did not.
To expand:
* It seems like windows takes a 16 bit unsigned integer for each entry in the LUT. The first 8 bits are taken as the LUT index and the second 8 bits are ignored/undefined.
* The ```byteswap``` function swaps the first and last bytes, so one can make a LUT between 0 and 255 and then use ```byteswap``` to move that into the first byte rather than the second.
* When reading the LUT, the first 8 bits will where the LUT is defined. That means that we can do a ```byteswap``` to shift them into the second 8 bits and then normalise by dividing by 255. This should …
=> BF: gamma table issues

psychopy/tools/gltools.py
Settled on the layout of GL tools which provides a flexible means of creating FBOs and working with them. I added a context manager which helps keep track of framebuffer bindings so you don't mess up the rendering pipeline. This is going to reduce the work around adding other stereo modes and creating textures for the new 3D mesh stimuli class.  I also added a bunch of examples to the documentation. 
Texture and renderbuffer functions generate and work with descriptor datatypes (namedtuples) whose fields contain information about the buffer. Using descriptors are optional in many cases, you can extract the field of interest and discard the rest.
=> NF/RF/DOCS: Changes to gltools

psychopy/app/_psychopyApp.py
Fixes #1985.
Ensure colorPicker returns an RBG triplet rather than RGB + alpha. Currently causes errors when assigning colors, as 3 rather than 4 channel values are expected.
Second attempt at this, as found there was an API-based way to not return the alpha value, rather than truncating the returned list manually. NB the displayed colour picker still has an active alpha control. This could cause users some confusion, as they may apply a value of alpha other than 1.0 in the colour picker UI but not have it reflected in the returned colour.
=> BF: Make colorPicker return RGB rather than RGBA

psychopy/visual/shape.py, psychopy/visual/text.py
- One `win.winType in ["pyglet", "glfw"]:...` hadn't been changed, so text was misaligned and missing color.
=> BF: GLFW TextStim fix

psychopy/visual/rift.py
Someone pointed out head locking the HMD view doesn't work when in monoscopic mode. This patch fixes that. I also added an attribute that allows head locking to be set during runtime.
=> BF: headLocked ineffective when in monoscopic mode (Oculus Rift)

docs/source/api/tools/gltools.rst, docs/source/api/visual/rift.rst, psychopy/tools/gltools.py, psychopy/visual/rift.py
This PR adds functions for importing Wavefront *.OBJ models with materials, mainly for use in VR experiments. Vertex data is loaded into vertex buffer objects and indexed VAOs are created for each material. VAO support has been improved to support index buffers which reduces redundant vertex data. These functions will form the basis of the Mesh3dStim class which is planned for release soon, which hides all the OpenGL stuff from the user. I'll soon release a guide on how to export models from Blender for presentation in PsychoPy.
=> NF/EN: Added OBJ/MTL importer. General improvements to VAO support.

psychopy/visual/backends/gamma.py
Rather than raising an error when the LUT size is returned as 0, issue a warning and proceed with an assumed LUT size of 256. This relates to #1982.
Hopefully this will become less encountered - updated drivers seem to report the correct LUT size.
=> ENH: raise a warning rather than an error if the gamma ramp size is 0

psychopy/app/builder/builder.py
In fileExport method, htmlPath now set by _getHtmlPath. In fileExport, the html export dlg view is now conditional on online settings in exp settings, where dlg is only shown if export is manual. When shown, the export dlg choices set online settings choice in experiment settings. If dlg is cancelled, no export occurs.
Note. _getHtmlPath method recursive function corrected so that recursion occurs before HTML path is set and returned
=> BF: Changes how html files are exported in ref to exp settings

psychopy/experiment/flow.py
loopStack should contain the list of children for each loop,
not the loop itself.
=> BF: compiling nested loops was crashing on the JS outputs

psychopy/experiment/components/sound/__init__.py, psychopy/sound/backend_pyo.py
In the second commit for the pyo backend:
When updating the sound volume dynamically using Pyo, a pyolib._core.PyoArgumentTypeError is raised because self.volume is a numpy float64, which is not expected by pyolib. This fix converts the self.volume variable to a native python float that is compatible with the Pyo library.
=> BF: Allows user to set sound volume dynamically

psychopy/gui/qtgui.py
Extended class "DlgFromDict" with the following features:
(1) The "sort_keys" parameter now also accepts a list defining the order of the displayed fields. This allows for a user defined order of input fields in the dialog.
(2) A "labels" parameter can be used to define labels which are displayed instead of the keys. This allows for comprehensible captions for input fields in the dialog while maintaining brief key strings.
(3) A "preserve_type" parameter can be used to enforce preservation of the variable types provided in the dictionary, if at all possible. This remedies the following problem currently occurring under Windows. Say, the call to DlgFromDict() is:
```
dictionary = {'Parameter1', 99}   # the 99 is an int
DlgFromDict(dictionary)
```
The dialog will display an input field …
=> Extend class "DlgFromDict"

psychopy/app/builder/validators.py
When variables should be set to update, the component dialog now warns the user. Also, when correct answer is improperly defined i.e. does not prepend code with '$', the user is warned of the error.
=> ENH: Highlights errors in component dialogs

psychopy/experiment/components/settings/JS_htmlHeader.tmpl, psychopy/experiment/components/settings/__init__.py, psychopy/experiment/loops.py
This fix addresses the problem that once the trials are been scheduled, the trial index was not updated any longer. This fix now updates trial indexing on each call to importConditions. Also updates to 3.0.0b11.
=> BF: Fixes JS trialhandling and updates to 3.0.0b11.

psychopy/experiment/loops.py
This fix addresses a problem where all columns were duplicated, except for those columns created for components in the JS experiment code.
=> BF: Fixes duplicated columns in datafiles on Pavlovia

.travis.yml, conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, psychopy/preferences/preferences.py, setup.cfg
I've been working on this off-and-on for a couple weeks now, and finally the builds pass on Travis.
This PR adds support for running the test suite on Python 3.7 on Travis and temporarily disables the remaining Python 2.7 test that was using the "system Python", which hasn't properly worked in months now. (This just is just commented out and can therefore be easily re-enabled at a later time should we desire)
It also adds support for future releases of `configobj` via https://github.com/psychopy/psychopy/pull/2062/commits/de2aae9494938ee849b073d4e8b6611aa7c446c0
=> TESTS: Add Python 3.7 support

setup.cfg
Tests pass on Python 3.7, so add it to the list of supported languages.
=> PKG: Update classifiers – We support Python 3.7

psychopy/sound/backend_sounddevice.py
A classic Python bug.
There may be a better solution than what I'm suggesting here, but in any case the list `self.sounds` should not be mutated while being iterated.
This fixes the crackling problem described in https://discourse.psychopy.org/t/sound-crackling-under-specific-conditions-demo-included/5480.
=> Don't mutate list while iterating

psychopy/visual/text.py
In place to remove the deprecation warning for pyglet.font.Text.
Temporary fix until pyglet.text.Label use is identical to pyglet.font.Text.
=> BF: Removes deprecation warning for use of pyglet.font.Text

psychopy/tools/attributetools.py, psychopy/visual/rect.py
Rect autoLog param was overwritten with attributeSetter and thus satisfied logging requirements in attributeTools (i.e., True), even though autoLog set to False.
=> BF: Fixes logging error with Rect and attributeTools

psychopy/gui/qtgui.py
The qtgui was crashing when user entered text because self.inputFieldTypes dict was throwing a key error when field names were being accessed as though they were a list, i.e. with an integer index value.
=> BF: Fixes GUI crash when entering text

psychopy/app/builder/builder.py
The _getHtmlPath method would get stuck in a recursive loop if save was cancelled when syncing a project. The fix stores the return value from fileSave, returning False and breaking the loop if fileSave is cancelled.
=> BF: Allows user to cancel saveAs when syncing unsaved project.

psychopy/visual/backends/glfwbackend.py
Currently, the GLFW window sticks around until the python script terminates. This allows destruction of the window + context before that point.
Example:
```python
from psychopy import core, visual
win = visual.Window(winType='glfw', allowGUI=False, pos=(0, 0), size=(400, 400))
core.wait(2.0)
win.close()
core.wait(2.0)
```
=> BF: Allow earlier destruction of GLFW window

psychopy/app/coder/codeEditorBase.py
The key error originates from the dict for controlling the commenting type (Js or Py) or commenting signal (colon or curly braces).
=> BF: Fixes key error when code component uses 'Both' dual view

psychopy/experiment/components/settings/JS_setupExp.tmpl, psychopy/experiment/components/settings/__init__.py, psychopy/tests/test_app/test_builder/componsTemplate.txt
The setRedirectURL function takes string arguments from online experiment
settings, however the default setting was redirecting to nonexisting URLs.
This fix changes the default value in the URL params, and only writes
the setRedirectURL function in the JS if an entry is provided for one of
the URL params in exp. settings.
=> BF: setRedirectUrl function should only exist when URLs are provided.

MANIFEST.in
This is to have the file 'version' in the sdist, and fix the problem with
'pip install' not finding the version file.
See issue #2049, #2095
=> PKG, BF: added 'include version' to MANIFEST.in

psychopy/visual/movie3.py
Previous `stop()` will set status to FINISHED, since `_unload` resets self.status to FINISHED.
=> ENH: set status to STOPPED when stop() is called.

psychopy/visual/window.py
When creating an FBO, only the stencil, not the depth component of the storage buffer is attached to the render buffer. This causes unexpected behaviour when using glDepthTest when rendering 3D objects.
=> BF: Fixed FBO missing depth attachment.

psychopy/core.py, psychopy/visual/backends/glfwbackend.py
Addresses #2089.
Currently, if `core.quit()` is called while a GLFW Window is open, `glfw.terminate()` (in core.py) runs before the window's `close_on_exit()` (via atexit). This PR registers `terminate()` with atexit when core is imported, meaning it ought to run *after* `close_on_exit()` (which is registered later).
Example:
```python
from psychopy import core, visual
win = visual.Window(winType='glfw')
core.quit()
```
@mdcutone, what do you think?
=> BF: Run `glfw.terminate()` later during cleanup.

.travis.yml, conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml
- Update the `conda` environments to match the current set of PsychoPy dependencies
- Actually try to build and install `sdist` and `bdist_wheel` distributions on Travis to catch any (simple) bugs in the first-stage packaging scripts (`setup.py` and such)
=> TESTS: Enhancements to Travis testing

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml
=> TESTS: Remove gitpython dependency

psychopy/app/psychopyApp.py
Running `psychopyApp.py` used to silently fail (return code 0, no error message) for me on macOS with a Miniconda installation. Turned out that one dependency (`wxpython`) was missing, but I never got to see the exception error message because the output of the `pythonw` executable that we invoke via `shellCall()` was silently discarded. This commit changes this behavior: we will now retrieve `stdout` and `stderr`, and "re-print" them to the appropriate streams.
=> ENH: Return stdout, stderr of pythonw invocation during app startup

psychopy/preferences/generateSpec.py
Also, switch to using context managers for file handling.
=> ENH: Python 3 compatibility of `generateSpec.py`

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, psychopy/app/pavlovia_ui/functions.py, psychopy/app/pavlovia_ui/project.py, psychopy/constants.py, psychopy/projects/pavlovia.py, requirements_travis.txt, setup.cfg, setupApp.py, setupApp.sh
Turns out the dulwich (and libgit2 which also looked promising) don't support proper pull with
merge option. 
That means we need to stick with the original git executables (and access via gitpython for simplicity for now). Sadly we're now packaging those inside PsychoPy which adds hundreds of MB :-(
=> Moved back to gitpython from dulwich

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, requirements_travis.txt, travis/20_install_miniconda_python.sh
- SoundFile and Sounddevice are available from `conda-forge`, we don't need to install via `pip`
- We now explicitly install `wxpython` & `openpyxl` via `conda-forge` (previously the `defaults` channel could have been used, leading to potential binary incompatibilities). This seems to fix recent issues with Travis (builds segfaulting).
- Install `pyglet` from `conda-forge`, and bump min. version to 1.3.0 (used to be a 1.3 beta)
=> TESTS: Small changes to Travis environments

psychopy/experiment/components/static/__init__.py
`bytes(compName)` does not work in Python 3 and because of that static component does not work too.
replacing it by `str(compName)` fixed the problem
=> Fix to a bug related to static component

psychopy/data/utils.py
New line characters in strings were printed not executed when
imported from a conditions file because new line characters are escaped
when the conditions file is converted from a dataframe to a numpy record
array. This fix checks for string in record after conversion to recarray,
and replaces the excaped newline with an unescaped new line.
=> BF: Replaces escaped newline chars in conditions file strings

conda/environment-2.7.yml, conda/environment-3.6.yml, setup.cfg
wxpython 4.0.2 and 4.0.3 break Undo/Redo behavior in the app. Exclude these versions from requirements and conda environments. However, only 4.0.3 is available for Python 3.7 on conda-forge, so do not impose any restrictions for Python 3.7 for now. Closes GH-2119.
=> PKG, TESTS: Exclude broken wxpython versions

docs/source/api/iohub.rst
As far as I know, there is no `win.swap()` method ... so `flip` is probably what is meant here.
=> DOC: fix typo win.swap --> win.flip

psychopy/experiment/components/mouse/__init__.py
When mouse save state was set to final, time was saved according to
the parameter settings in the mouse component. However,time given at the end
of the trial is misleading, becuase it can be interpreted as a reaction time.
=> BF: Removes misleading time data saved when mouse save set to "Final"

psychopy/hardware/crs/bits.py
Display++ was giving an error on initialisation because the reply was not available to be read immediately - this pauses to allow the device time to respond before reading.
=> ENH: pause BitsSharp device after sending message

psychopy/experiment/components/text/__init__.py
When text is set to Blank or None in Builder, the JS output provided a Nonetype as text, which fails in JS.
Also, setting to undefined, as in JS, the user is given a Hello World string.
This fix sets the JS output text for text component to an empty string if no text is provided.
=> BF: Adds an empty string to text JS text component if text is None

docs/source/about/index.rst
The link to the 2007 paper was broken. Fixed to use DOIs as the links for both papers, and added citation details of the Builder textbook. Will need to update again when the new paper comes out.
=> DOC: update citation information

psychopy/experiment/components/joystick/__init__.py
Button state was not correctly initialized at the start of every 'routine'. Causing previously read button states to be incorrectly read as new presses. Now initialized to the to current button state at the start of a routine to ignored existing presses until the state has changed back to unpressed.
=> BF:  Fix button debounce behaviour for when used in multiple routines.

psychopy/experiment/components/image/__init__.py, psychopy/experiment/params.py, psychopy/experiment/py2js.py, psychopy/tests/test_psychojs/test_py2js.py
Numbers in lists with unary operators were converted to tuples, numbers in tuples with unary operators were converted to  lists. Now, elements of list/tuple with unary operators are converted to nested list, unless a binary operator exists, in which case parenthesis are used to determine order of operations.
Also, some tuples were not converted to lists, and now py2js checks for tuple in params, and converts to list.
py2js tests are added to check conversions of parameters.
=> RF/TESTS: Changes py2js conversion of params and adds py2js tests

psychopy/app/builder/builder.py
This addresses one of the issues brought up in GH-2132.
=> ENH: When renaming Routine, display current name as default in dialog

psychopy/experiment/components/cedrusBox/__init__.py, psychopy/experiment/components/eyetracker/__init__.py, psychopy/experiment/components/ioLabs/__init__.py, psychopy/experiment/components/joystick/__init__.py, psychopy/experiment/components/joystick/mouseJoystick.py, psychopy/experiment/components/keyboard/__init__.py, psychopy/experiment/components/mouse/__init__.py, psychopy/experiment/components/parallelOut/__init__.py
- Set status to `FINISHED` instead of `STOPPED` when components stop (#2132).
- `mouseJoystick.Joystick` should be new-style class. Closes #2151.
=> RF: Updates to Builder Components

psychopy/experiment/params.py, psychopy/experiment/py2js.py, psychopy/tests/test_psychojs/test_py2js.py
The previous fix converted lists with unary operations to nested lists,
which failed when JS color functions expected "an array of numbers of length 3".
The new fix now converts only tuples, and maintains parenthesis in order
to uphold order of operations. Unary operations are treated with
parenthesis by default to preserve that order and the numbers contained
are treated as numbers, not arrays. Thus ```[(-1), (-1), (-1)]``` is a valid color.
=> BF: Fixes py2js tuple to list conversion using ast transformer.

psychopy/app/builder/builder.py, psychopy/app/coder/coder.py
By adding the window style `wx.FD_OVERWRITE_PROMPT` to the `wx.FileDialog`, we don't have to manually handle the "file already exists, should we overwrite?" case anymore.
This also closes GH-2113.
=> ENH: Use WX's built-in prompt-to-overwrite-file feature

psychopy/data/base.py, psychopy/data/utils.py, psychopy/microphone.py, psychopy/sound/_base.py, psychopy/tools/filetools.py, psychopy/visual/helpers.py, psychopy/visual/movie.py, psychopy/visual/movie2.py, psychopy/visual/movie3.py, psychopy/visual/simpleimage.py
* Added `path_to_string` function under tools/filetools which will coerce pathlib objects (or any object that utilizes the `__fspath__` dunder method) to their corresponding filesystem representation (string or bytes). Any object that does not have an `__fspath__` dunder method will be returned as is.
* Added support for pathlib to:
* microphone
* data/utils
* data/base
* visual/movie*.py
* visual/helpers.py
* sound/_base
Wasn't sure if tests for the new `path_to_string` function were needed. I think I covered most of the important areas where users will supply their own paths, but if you think of any others please let me know.
see #1817
=> NF: psychopy pathlib support

psychopy/experiment/_experiment.py, psychopy/experiment/components/_base.py, psychopy/experiment/components/settings/__init__.py, psychopy/tests/test_app/test_builder/test_Experiment.py
This is a more generic way to add import statements to a Builder-generated experiment. (See https://github.com/psychopy/psychopy/pull/2141#issuecomment-447287872 for a first short discussion)
Previously, only `requirePsychopyLibs()` was available, which would only `from psychopy import xxx`; whereas the new `requireImport()` can import `from` and `as` arbitrary packages/modules/names.
`requirePsychopyLibs()` was modified such that it now acts as a convenience method for `requireImport()`.
Example:
```python
Experiment.requireImport(importName='matplotlib.pyplot', importAs='plt')
import matplotlib.pyplot as plt
Experiment.requireImport(importFrom='psychopy.preferences', importName='prefs', importAs='p')
from psychopy.preferences import prefs as p
```
I first wanted to create an "execute …
=> NF: Add Experiment.requireImport() method

psychopy/app/preferencesDlg.py, psychopy/experiment/components/parallelOut/__init__.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec, psychopy/preferences/preferences.py, psychopy/sound/__init__.py, psychopy/sound/backend_pyo.py, psychopy/tests/test_sound/test_sound_pygame.py, psychopy/tests/test_sound/test_sound_pyo.py, psychopy/tests/test_sound/test_sound_sounddevice.py, psychopy/visual/movie3.py
As proposed in https://github.com/psychopy/psychopy/pull/2141#issuecomment-447287872, this PR introduces a new "hardware" section in the preferences and, likewise, a "hardware" tab in the preferences dialog. I've moved the following settings from "general" to "hardware":
- audioLib
- audioDriver
- audioDevice
- parallelPorts
=> ENH, RF: New "hardware" prefs tab

psychopy/experiment/components/_base.py, psychopy/experiment/components/keyboard/__init__.py, psychopy/experiment/components/settings/__init__.py, psychopy/experiment/components/sound/__init__.py, psychopy/experiment/flow.py, psychopy/experiment/loops.py, psychopy/experiment/routine.py
Corrected call to callOnFlip for sound - note, must check is supported with AP
Corrected call to callOnFlip for keyboard
Update code to include selected rows in Trial Handler
Other JS compile fixes relating to equality operators
Added extra spacing to separate conditionals and loops for readability
=> BF: Various fixes for JS compiler for psychojs-3.0.0b12.

psychopy/experiment/_experiment.py, psychopy/experiment/components/_base.py, psychopy/experiment/components/settings/__init__.py, psychopy/tests/test_app/test_builder/test_Experiment.py
The new `Experiment.runOnce()` method allows to add arbitrary code to the beginning of the experiment script (directly below the imports) which will only be executed a single time. This is for example useful if a Component requires a certain initialization routine, e.g. activation of hardware, and this procedure shall be executed only once even if the Component appears multiple times in the experimental flow. See https://github.com/psychopy/psychopy/pull/2141#issuecomment-447295089
Also update some docstrings.
=> ENH/NF: Add Experiment.runOnce() method 

psychopy/data/base.py, psychopy/data/experiment.py, psychopy/data/staircase.py, psychopy/data/trial.py, psychopy/data/utils.py, psychopy/tests/test_data/test_ExperimentHandler.py, psychopy/tests/test_data/test_TrialHandler.py, psychopy/tests/test_data/test_TrialHandler2.py, psychopy/tests/test_data/test_TrialHandlerExt.py, psychopy/tests/test_tools/test_filetools.py, psychopy/tests/utils.py, psychopy/tools/filetools.py
This allows for better support of "special" characters and improves e.g.
support of Chinese. Closes #2166.
=>  ENH: Use utf-8-sig instead of utf-8 encoding

psychopy/visual/ratingscale.py
We used to receive: `DeprecationWarning: object of type <type 'float'> cannot be safely interpreted as an integer.`
=> RF: Get rid of NumPy deprecation warning

pytest.ini, setup.cfg
- Move `pytest` configuration to `setup.cfg` for more consistency ("everything in one place")
- Use `python_requires` config option to restrict supported Python interpreter versions
=> TESTS, PKG Updates

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, psychopy/contrib/configobj/LICENSE, psychopy/contrib/configobj/__init__.py, psychopy/contrib/configobj/_version.py, psychopy/contrib/configobj/validate.py, psychopy/preferences/preferences.py, setup.cfg
The latest release of `configobj` is already a bit old and does not support Python 3.7. For that reason, we switched to using the `master` branch – at least for testing – a couple months back. Now when working on the "bring PsychoPy to conda-forge" project, it turned out that this is in fact a quite problematic approach as `conda-forge` does not accept "non-released" software packages (meaning we would not be able to package `configobj` `master` for the Python 3.7 build).
I discussed the situation with the `conda-forge` folks and they suggested the easiest approach would
probably be to "vend(or)" `configobj` `master`, i.e., ship it with PsychoPy, at least until a new version with the fixes we need has been published.
This is exactly what this PR does. Note that it also retains support for …
=> PKG: Include copy of configobj master in PsychoPy contrib directory

psychopy/demos/builder/pump/bubble_cycle.psyexp
For whatever reason, `bubble_cycle.psyexp` contained references to an `UnknownComponent` where it should have been `QmixPumpComponent`. Don't know how that happened, maybe committed the wrong file at some point, or mixed up stuff during a rebase.
Whatever the cause, with these changes in place, Travis should pass again, hopefully.
x-ref: GH-2192
=> DOC/TESTS: Fix Pump Builder demo

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, requirements_travis.txt, setup.cfg
`iohub` tries to import `msgpack-numpy` and, if that import fails, emits a warning that this "may cause issues". Therefore, adding `msgpack-numpy` to the package requirements.
NB Will rebase once #2199 has been merged.
=> PKG: Add msgpack-numpy dependency

psychopy/scripts/psyexpCompile.py
Imported modules at the beginning of the script were used to
compile the experiment script. These modules were imported from the current
version of PsychoPy, not the requested version. This fix imports modules
after useVersion has been called, which fixes the problem. Also adds docstrings and
refactors.
=> BF/RF: Fixes import error with psyexp.compileScript and refactors

psychopy/app/builder/dialogs/__init__.py, psychopy/experiment/components/settings/__init__.py, psychopy/tests/test_tools/test_versionchooser.py, psychopy/tools/versionchooser.py
PsychoPy versions < 1.85.4 are incompatible with wx >=4.0.0. This fix filters those versions using the version filter. Also improves error handling of py3 compatibility.
=> BF: filters version chooser for wx compatibility.

psychopy/sound/backend_sounddevice.py
sounddevice backend raises exception in Python2 because `list` object in Python2 doesn't have `copy() `method.
Please see #2214 for detail.
=> BF: sounddevice backend raises exception in Python2

psychopy/app/builder/dialogs/dlgsCode.py
One use of params in CodeBox is to determine code type (JS or PY).
This fixes a TypeError raised when ParamCtrls creates a CodeBox for Text Component,
because ParamCtrls does not pass params to the CodeBox, resulting in params
being None. Therefore, when params are used on keypresses for smart indenting
lines, a TypeError is thrown as NoneTypes are not subscriptable.
=> BF Fixes  TypeError when changing text in text component.

psychopy/tools/versionchooser.py
Note, returns False when using parse_version for```3.0.* > 1.90.1``` but True for ```3.0.* > 1.90.*```
parse_version implements PEP440 version identification - see docs. See also #2172
=> RF: Makes use of parse_version for version filtering.

psychopy/experiment/components/settings/__init__.py
'use preferences' for window units breaks JS code. This fix sets the default window units as 'height'. Fixes new issue in #2227.
=> BF: Replace 'use prefs' default with 'height'  for JS window units

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, travis/20_install_miniconda_python.sh
Addresses GH-2238 and ensures `conda` will not update arbitrary packages when we try to install another one.
=> TESTS: Pin pip to version <19.0 and ensure packages are not updated when installing a new conda package

.travis.yml, conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, travis/20_install_miniconda_python.sh
- slightly change how `conda` environment gets activated (to match recommended procedure for newer `conda` versions)
- ensure all dependencies listed in the environment files are installed from `conda-forge` only; this will avoid future mixups of `conda-forge` and `defaults`, which can lead to unexpected behavior as seen in #2239
- provide a list of all `conda` packages installed  in the testing environment to simplify future debugging
=> TESTS: Updates to conda environment setup

psychopy/sound/backend_sounddevice.py
Fixes GH-2230.
Old behavior:
```python
In [1]: from psychopy.sound import Sound
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
In [2]: input('foo> ')
bar.
Out[2]: 'bar.'
```
New behavior:
```python
In [1]: from psychopy.sound import Sound
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
In [2]: input('foo> ')
foo> bar.
Out[2]: 'bar.'
```
=> ENH/BF: Workaround for stderr confusion after importing sounddevice

psychopy/iohub/client/__init__.py
The previous code would throw an exception on Py3.
=> BF: Use correct import of visual.window when shutting down iohub

psychopy/experiment/routine.py
In commit ff5f731956a3 we had switched the order of checks to end
routine versus end experiment but in GH-2213 an auto merge resulted in
the moved code existing in both locations
=> BF: Undoing error from an auto merge at GH-2213 that left uneeded code

psychopy/app/builder/builder.py
This fix disables Pavlovia Run when syncing because running too early caused a wx error. The choice to use 0 or 1 for toggle state was more intuitive than False or True. Happy to change if bool is preferred.
=> BF: Disable Pavlovia Run when syncing.

psychopy/app/pavlovia_ui/project.py, psychopy/experiment/components/text/__init__.py
--For textstim, this changes any NoneTypes to 'undefined', except actual text,
where NoneTypes become empty string (as with Python).
--The Pavlovia sync project function was throwing a TypeError if the user
chose not to recreate project on sync, if the exp was pointing to a remote
that doesn't exist. Error thrown because the line was comparing Int and None
if the user aborted.
=> BF: Convert NoneTypes to undefined for HTML export, and Pavlovia gui fix

psychopy/app/builder/builder.py, psychopy/experiment/components/polygon/__init__.py, psychopy/scripts/psyexpCompile.py
--In Builder, the output for errors raised by subprocess were in bytes and not nice to read. This fix decodes the bytes and prints line by line in the console.
--The psyexpCompile script was appending the wrong error message to all error msgs raised when compiling scripts. This fix changes error messages accordingly.
--Adds line and triangle to JS code. Raises errors for regular polygons (except those with 2, 3 and 4 sides) and 'cross' and 'star' shapes, until supported and we can delete.
--Fixes error in Python code where size given as a single int, not float, did not convert to list of x,y sizes.
=> BF/ENH: Adds line and triangle polygons to JS compiler, and other fixes.

psychopy/projects/pavlovia.py
If a project was opened, but the user had not logged in, and tried to sync,
the user was asked to create a project, even though the project existed.
The failed sync then resulted in the user being logged in and the sync
working on the next attempt. This fix attempts to log the user in on a sync
if the user is known, or in the case of multiple users where the namespace
is not indicative of the user account, uses the project name to determine
membership to known user and which known user should be logged in. Also
increases number of items listed to 100 when retrieving user projects from
Pavlovia. Fixes and refactors warning messages.
=> BF/RF: Fixes sync problem occuring when user was not actively logged in.

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, psychopy/data/base.py, setup.cfg
=> TESTS, PKG: Install imageio & imageio-ffmpeg; support openpyxl 2.6

psychopy/app/pavlovia_ui/_base.py, psychopy/app/pavlovia_ui/functions.py
This fix creates a new dialog class for committing changes.
The dialog checks for user input in the commit summary.
The OK button is disabled when the text box is empty, however
a default message is inplace and highlighted by default as a reminder,
and to ensure the the OK button can still be clicked.
Deleting the default message leaving the summary text empty will disable
the OK button, thus preventing errors caused by having an empty commit message.
=> ENH/RF: Changes how commit dialog works, ensuring commit message given.

psychopy/projects/pavlovia.py
This fix checks the version of Gitlab, and uses per_page parameter only if Gitlab version > 1.4.
=> BF: per_page Gitlab parameter only available for gitlab versions > 1.4

psychopy/app/pavlovia_ui/sync.py
This is useful if an error message is output into the frame (see #2262). Having a resizable frame makes it easier to read the error without having to paste into a notepad or equivalent.
=> BF: Allow user to resize sync frame

psychopy/experiment/components/_base.py
Save onset/offset times are output even though "Save onset/offset times" in the Properties dialog are unchecked.
=> BF: "Save onset/offset times" doesn't work

docs/source/api/tools/viewtools.rst, docs/source/api/visual.rst, psychopy/tools/viewtools.py, psychopy/visual/window.py
Some small changes to 'viewtools' including documentation/examples. 
- Added 'pointToNdc' to the viewtools index. 
- Some changes to attributes in the window class which viewtools works with. Mostly to reduce redundant numpy and GL calls.
- I also added viewtools to the documentation index for 'visual' for discoverability. 
I also went through and fixed up some mangled docstrings not related to viewtools which make the API reference look ugly.
=> RF/DOCS: Misc fixes to 'viewtools', window, and docs.

psychopy/experiment/components/sound/__init__.py
This fix now checks the duration of each sound file (if sound file used)
and stops the sounds after that duration. Also, sound component status are
updated now. Also, tones and frequencies are now handled specifically
because they do not have a predetermined duration like a sound file.
=> BF: Sound files were not ending online if duration was None.

psychopy/app/builder/builder.py, psychopy/app/builder/dialogs/dlgsCode.py, psychopy/app/coder/codeEditorBase.py, psychopy/app/coder/coder.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec
Should fix issue of mixed EOLs causing lines of code to disappear, see [Discourse](https://discourse.psychopy.org/t/bug-disappearing-line-breaks-in-code-cells-in-builder/6607/9).
Also, adds Legacy Mac line endings as a preference.
=> BF: converts EOL on opening and compiling scripts to Coder.

psychopy/app/coder/coder.py
This prevents a NoneType error.
Signed-off-by: dvbridges <david-bridges@hotmail.co.uk>
=> BF: Check whether EOL is not None on paste

psychopy/experiment/components/slider/__init__.py
The fix changed the conditional to end the routine, as currently it
always ends routine without a response because 'undefined' !== undefined.
Note, you cannot see the actual marker if you ask the Slider to end the
routine. The routine will end without a marker being drawn.
=> BF: slider.getRating() returns undefined, not 'undefined'

psychopy/app/builder/builder.py, psychopy/app/builder/dialogs/dlgsCode.py, psychopy/app/coder/codeEditorBase.py, psychopy/app/coder/coder.py, psychopy/app/preferencesDlg.py, psychopy/experiment/_experiment.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec, psychopy/preferences/hints.py
The original issue from Discourse appeared to be a problem with interpretting
mixed EOLs in Coder and code components. The original fix
attempted to convert EOLs to those defined in the preferences to provide
uniform EOLS. However, this did not address the problem described in
the original post.
=> BF: Reverts all commits from #2278 and #2279

psychopy/app/builder/dialogs/dlgsCode.py, psychopy/app/coder/codeEditorBase.py
This fix adds a keycheck when using paste shortcut and redirects
to the codeEditorBase paste method. It also enables the
context menus for both Coder and Code Component to be directed
to the Paste function in the codeEditorBase.
Edit: The context menu **DOES** work when switching the tabs - the tab just needs
to be active. The keyboard shortcut is independent
of the context menu fixes, and can be cherry picked if the menu is not
wanted.
=> BF: Code component was not using Paste method from codeEditorBase class

psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/eyetracker.py
This PR fixes some errors in `psychopy.iohub` occurring when running Psychopy with Python3.6. Basically catches errors when trying to use `basestring` or `unicode`, and pointing these classes to the default Python3 `str` class.
It also fixes a bug when trying to remove the extension of the `default_native_data_file_name` string.
=> BF: Fix basetring/unicode bugs for Py3

psychopy/experiment/components/microphone/__init__.py, psychopy/tests/test_app/test_builder/componsTemplate.txt
This is so that the experiment builder can auto generate 'chnl' attribute for AdvAudioCapture, as not all devices share the same default '0' for input device.
**Detailed explaination of fix in below thread**
https://discourse.psychopy.org/t/potential-improvements-to-microphone-component-of-experiment-builder/6814
=> ENH: Added Channel field to Microphone properties

psychopy/app/coder/coder.py
The new context menu, specific to only the output window in Coder,
now provides the option to clear the output. In addition, select all and
copy text is provided as the only useful other options. Fixes #2285.
=> ENH: Adds custom context menu to output window in Coder.

psychopy/event.py
I found the spacebar is missing 
```
File "stimulus_show.py", line 40, in <module>
event.globalKeys.add(key='space', func=pause)
File "/usr/local/lib/python3.6/site-packages/psychopy/event.py", line 1090, in add
raise ValueError('Unknown key specified: %s' % key)
ValueError: Unknown key specified: space
```
And adding the spacebar to the valid keys can fix this.
=> BF: add spacebar to the valid keys

psychopy/projects/pavlovia.py
Raise was emitting a TypeError: exceptions must derive from BaseException
when passed inappropriate value (in this case a 'U' was passed. This
fix handles this case as a value error. However, perhaps more general
exception handling is required.
=> BF: Better handling of exceptions raised for getChanges method

psychopy/app/builder/builder.py, psychopy/app/builder/dialogs/dlgsCode.py, psychopy/experiment/_experiment.py, psychopy/experiment/components/_base.py, psychopy/scripts/psyexpCompile.py, psychopy/tests/data/TextComponent_disabled.psyexp, psychopy/tests/data/TextComponent_not_disabled.psyexp, psychopy/tests/test_app/test_builder/componsTemplate.txt, psychopy/tests/test_app/test_builder/test_Experiment.py, psychopy/tests/test_psychojs/test_compile.py, psychopy/tests/test_scripts/test_psyexpCompile.py
During testing of an experiment, (temporarily) disabling a component can make life much easier. This PR adds a `Testing` tab to the component properties, which currently only contains a `Disable component` checkbox. If active, the component will be removed from the experiment when compiling the `psyexp` file (the original experiment / `psyexp` file will remain untouched).
Does not add the `Disable component` checkbox to `CodeComponent`s (they can still be disabled programmatically.)
=> NF: Allow components to be disabled

psychopy/app/builder/builder.py, psychopy/app/builder/flow.py, psychopy/experiment/_experiment.py, psychopy/experiment/routine.py, psychopy/scripts/psyexpCompile.py, psychopy/tests/data/routine_disabled.psyexp, psychopy/tests/data/routine_not_disabled.psyexp, psychopy/tests/test_app/test_builder/test_Experiment.py, psychopy/tests/test_scripts/test_psyexpCompile.py
This PR allows routines to be disabled via a context menu entry.
Note that because of the  way PsychoPy adds routines to the flow, there is currently no easy way to allow users to disable individual representations of the same routine. If a routine is
placed in the flow multiple times, disabling one of them will disable _all_ occurrences.
More background info on this:
When adding a routine to the flow, PsychoPy simply adds this routine to a list. When adding another representation of the same routine to the flow, effectively the very same object will get added again -- they both point to the same routine object in memory. Modifying one will automatically alter the other too (since, well, it is not "another", but "the same" routine). To fix this, we'd have to come up with a solution to …
=> NF: Allow routines to be disabled

psychopy/app/preferencesDlg.py
SetToolTipString() raises following warning message when the Preference dialog is opened.
```
C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\preferencesDlg.py:288: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
ctrls.valueCtrl.SetToolTipString(_translate(hint))
```
SetToolTip() has already been used at other places (e.g. coder\coder.py, pavlovia_ui\_base.py,...) and seems to work fine.  I tested my fix on Windows Python2.7, Python3.6 and Ubuntu Python3. There was no problem.
=> ENH: remove deprecated method: SetToolTipString()

psychopy/demos/coder/iohub/keyboardreactiontime.py, psychopy/iohub/client/keyboard.py, psychopy/iohub/datastore/__init__.py, psychopy/iohub/devices/__init__.py, psychopy/iohub/devices/experiment/__init__.py, psychopy/iohub/devices/keyboard/__init__.py, psychopy/iohub/devices/mcu/iosync/__init__.py, psychopy/iohub/devices/serial/__init__.py, psychopy/iohub/devices/serial/default_pstbox.yaml, psychopy/iohub/devices/touch/hw/elo/__init__.py, psychopy/iohub/devices/xinput/__init__.py, psychopy/iohub/removed/util/targetpositionsequence.py, psychopy/iohub/server.py
Fixes iohub.datastore errors for records that had a string column.
The demos demo/coder/iohub/launchHub.py, keyboard.py, and mouse.py should now run on Windows 7 / 10 using Python 2.7 or 3.6. 
Note: due to changes in the gevent pkg implementation,  the smallest iohub device poll interval on windows is apparently 1 msec. If you put anything small than 0.001 in an iohub device interval field you get a warning from gevent and it is set to 1 msec. Devices that use callbacks are not affected by this.
=> BF: Misc iohub fixes

psychopy/experiment/components/settings/__init__.py, psychopy/tests/test_app/test_builder/test_components.py
By flipping one last time after the very last routine of an experiment has finished execution, we ensure that `win.callOnFlip()` and `win.timeOnFlip()` calls will take effect even at the end of an experiment (they used to have no effect as we simply didn't flip, see GH-2169).
=> ENH: Flip at the very end of a Builder experiment

setup.cfg
I noticed that the most recent version on PyPI still requires lots of packages, including the deprecated `pygame`. I've fixed that in this PR, but maybe it would be a good idea to do some more cleaning (especially since the [install docs now mention a minimal setup](https://www.psychopy.org/installation.html), which currently cannot be installed because all requirements get pulled in). Let me know if you want me to do that.
=> Remove pygame requirement

docs/source/api/visual.rst, psychopy/tools/viewtools.py
* Cleaned up the documentation for 'viewtools' to make it easier to follow. 
* Added examples for various functions showing most common use cases.
* Defined an `__all__` statement. 
* Made 'up' optional for 'lookAt'.
* More sensible handling of singularity condition in 'pointToNdc'.
* Added APA reference for 'generalizedPerspectiveProjection'.
* Added 'See also' entries for related functions.
=> DOCS/RF: misc documentation fixes and module organization for viewtools 

docs/source/api/tools/colorspacetools.rst, psychopy/tools/colorspacetools.py
Just doing some documentation work on modules I've contributed to in the past. Added __all__statment to keep internal functions from gunking up the namespace.
Also, it might be helpful to consider using Colour Science for Python libraries (https://www.colour-science.org/) to handle future colorspace conversion routines.
=> DOCS/RF: Documentation fixes for colorspacetools

psychopy/visual/backends/glfwbackend.py, psychopy/visual/window.py
Enabling vertical sync when using the GLFW backend requires additional configuration other than setting waitBlanking=True in some cases. This patch sets the GLFW swap interval accordingly depending on the value of waitBlanking.
=> BF: Make waitBlanking set the GLFW window's swap interval.

psychopy/hardware/keyboard.py
On windows we can use (and need!) `PsychHID('Keyboard', None)` to get
all keyboards.
On Mac that currently returns only the first keyboard, not a combo, so
on Mac (and linux?) we need to fetch all keyboard-looking devices again
and create a virtual unified keyboard ourselves.
=> FF: fix multiple PsychHID keyboards on mac

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml, setup.cfg
It seems there is a freetype and a py-freetype (and I think the former is installed by the latter) so maybe we need to fix them both to a particular version rather than just one of them?
=> Another attempted fix to incompatible freetype library

psychopy/app/dialogs.py
Previously, if you wanted to add extra fields to exp info in experiment
settings, the new row would be added above the selected field. This fix
changes this behaviour so that rows are appended beneath the current row.
=> BF: Creates row beneath selected row in exp. settings expInfo

psychopy/experiment/components/cedrusBox/__init__.py, psychopy/experiment/components/ioLabs/__init__.py, psychopy/experiment/components/keyboard/__init__.py, psychopy/experiment/exports.py, psychopy/hardware/keyboard.py, psychopy/tests/data/correctScript/correctKeyboardComponent.py, psychopy/tests/data/correctScript/correctcedrusButtonBoxComponent.py, psychopy/tests/data/correctScript/correctioLabsButtonBoxComponent.py
- New keyboard code is written dependent on the existence of the
psychtoolbox module (PTB). If PTB does not exist, then keyboard
reverts to using event module code.
- The new keyboard module will make different calls depending
on whether PTB exists. Currently, only getKeys is implemented. If no PTB,
then a new response object is created from the event.getKeys output
containing the key name and the response time. This differs from previous
calls to event.getKeys, which returned a list of key names.
- BuilderKeyResponse container class is now redundant and replaced with
keyboard attributes. These are refreshed on every repeat of the
routine, because a new keyboard object is instantiated on each repeat.
- To smooth call signature to new getKeys methods, the event.getKeys
kwargs are added to …
=> ENH: Adds new keyboard code to Builder!

psychopy/experiment/components/movie/__init__.py
Previously, movie units were set to 'undefined' if screen units set to
"from exp settings". Now, "from exp settings" is replaced with
"height" units. Also fixes a missing namespace from movie status.
=> BF: Fixes status and units in movie stim

psychopy/hardware/bbtk/__init__.py
Opto smoothing is only important for CRT monitors and adds 20ms delay to
timing thus delaying visual stim offset. This fix turns off opto
smoothing on BBTK init rather than making it dependent on BBTK methods.
Previously, smoothing was only disabled when setResponse method was
called, the method used for responding to stim. This meant that other
timing methods (e.g., recordStimulusData) kept default "active"
smoothing on all channels.
=> BF: Removes opto smoothing, but not mic smoothing, on BBTK init

psychopy/experiment/components/keyboard/__init__.py
To fix this syntax error, the keyList param is hardcoded, but the
keyList arg is written as either a list (if filled) or None.
Also refactored the evaluation of keylist as a a variable, as conditional
statements are more readable using correct line breaks and indentation.
=> FF: New keyboard no longer creates syntax error if keyList empty

psychopy/visual/text.py
Explain that alignVert is unlikely to align the exact center of text on the position set for the text object. However, I'm not sure I got the jargon quite right.
=> Explain alignVert positioning

psychopy/app/pavlovia_ui/_base.py
This fix removes the default commit msg (which was annoying for Mac
users who needed to select all to clear) leaving an empty field.
Further, blank commit msgs no longer disable the OK button, but to
prevent errors, blank commits are filled with "_".
=> FF: commit title no longer mandatory for commit dlg

README.md
Minor README tweaks.
The developers link was 404'ing, so I fixed it, made your other links correct Markdown, and added a link to CONTRIBUTING.md.
=> Fix and add links in README

buildCompleteInstaller.nsi, buildWinDistributions.ps1
With these changes, the windows installer no longer requires admin. 
Fixes #2127 
- If run with admin privileges, allows user to choose "Current User" or "All Users"
- If run without admin, defaults to "Current User" and warns user about installing avbin
The main changes to the NSI file are:
- using `!include MultiUser.nsh` and its needed settings
- using LogicLib to do some conditional things on install/uninstall
I changed the .ps1 script to make it less path-dependent as well.
Likely needs testing on more bitness/platforms, but the installer is largely the same; just slightly different methods to set PATH and create shortcuts, etc.
=> Fix windows NSIS installer to work in CurrentUser mode

psychopy/experiment/components/settings/__init__.py
This should work on Python 3.6+, where dictionaries retain insertion order by default.
Example settings:
Old behavior – sorted alphabetically:
New behavior – sorted as in Experiment Settings:
=> ENH: Don't alphabetically sort exp info dict by default in Builder

psychopy/visual/movie2.py
Calling vlm_release makes latest VLC die with a memory access error.
I think this is because we never initialize the VLM stuff, and don't
need to release it. The audio stream release should be enough.
Also fixed a typo while in there.
=> Fix crash bug in MovieStim2

psychopy/app/builder/dialogs/__init__.py, psychopy/experiment/loops.py
Makes more sense to capture and replace the file path separators for JS
when compiling the script, rather than attempting to convert the actual
condition filename and path parameter. This fix also converts both double
and single backslashes. Double may be input by the user if manually
typing file path.
=> BF: Replace loop file path separators for cross-platform compatibility

psychopy/visual/backends/glfwbackend.py, psychopy/visual/backends/pygletbackend.py, psychopy/visual/window.py
Fixes the issue posted here: https://discourse.psychopy.org/t/scaling-problems-with-multiple-windows-using-different-resolutions/7476/5
This patch fixes issues around switching windows which cause things to be incorrectly drawn in some use cases (e.g. when using windows with differing resolutions). It also makes window switches a touch more efficient by reducing redundant calls when a context change is requested on a current window. 
Also has support for properly configuring windows on retina displays. However, I don't have one to test with.
=> WIP - BF/EN: Fixed drawing on multi-window displays with heterogeneous configurations.

psychopy/hardware/keyboard.py
KB was calling clearEvents to clear the key buffer, which only cleared the events list, not the
actual list of keys pressed. This means that keypresses persisted
even with the option to discard previous keypresses before KB onset
was selected. To fix, rather than have clearEvents call _clearEvents,
which other methods also call, the events and key list are cleared
directly.
=> BF: Keyboard event keys cleared properly

psychopy/microphone.py, psychopy/sound/backend_pyo.py, psychopy/sound/backend_sounddevice.py
Mic is currently ONLY supported under pyo backend so, if another backend
is set as the default, we should initialise the pyo engine anyway and give
a warning that the mic and the preferred output lib may clash
=> BF: fixed mic for pyo backend when prefs did not give pyo as preferred

psychopy/experiment/components/settings/__init__.py
The version Param was not formatting correctly in the JS and HTML
because the string representation of the value was not being used. This fix
uses the val attribute of version Param to format JS and html.
=> BF: Fixes version formatting by using string value of version Param

psychopy/visual/window.py
Fixes some issues where ``viewPos`` and ``viewScale`` are overwritten by the new matrix logic. Added a bunch of fixes for retina displays when switching contexts. I drew a range of stimuli and everything draws correctly now. 
I'm going to play it safe an avoid going all in with regards to the view/projection matrix system until the next major release. If anyone can test this patch out on a Mac, that would be very helpful to see if retina support is working correctly.
Also for some reason there are lots of duplicate commit entries. Seems like git is acting up a bit.
=> BF/RF: Window fixes 

psychopy/iohub/client/keyboard.py
This fix ensures that `waitForKeys` still returns the current set of queued events if `maxWait` is a number but not greater than 0. Previous behavior was to return an empty list.
Fixes #2454
=> BF: Return keys if maxWait <= 0

psychopy/visual/form.py
Form component crashes if non-ASCII characters are used in form items in Python2.
Error message is as follows:
```
File "C:\Users\Hiroyuki\Desktop\untitled.py", line 81, in <module>
itemPadding=0.05)
File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\visual\form.py", line 99, in __init__
self._doLayout()
File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\visual\form.py", line 605, in _doLayout
question, questionHeight, questionWidth = self._setQuestion(item)
File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\visual\form.py", line 269, in _setQuestion
psychopy.logging.exp("Question text: {}".format(item['questionText']))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in …
```
=> BF: FormComponent crashes if non-ASCII characters are used in Python2

psychopy/hardware/keyboard.py
The windows OS does not differentiate between 'num enter' and 'return'
and so the same keycode is returned for keyboard. Changed name to 'return'
because that is (probably) more commonly used.
=> BF: Set name of Windows 'num enter' and 'return' to 'return'

psychopy/experiment/components/keyboard/__init__.py, psychopy/tests/test_scripts/test_component_compile_js.py, psychopy/tests/test_scripts/test_component_compile_python.py
When KB was synced to visual, the KB clock was not reset and events
not cleared before first response was collected, only when
a response happened immediately after keyboard status was changed
to "STARTED". The clearEvents call now added to callOnFlip when visual
sync for KB is True. The new waitOnFlip var does not allow
getKeys to be called if the initial callOnFlip, used for resetting clock
and clearing events, has not been completed.
=> BF: Ensure events cleared and clock reset for KB when using visual Sync

docs/source/api/visual/window.rst, psychopy/visual/window.py
The documentation seems a bit out-of-date and broken in some places. I tried to convert much of the documentation of the Window class to Numpy style. I fixed loads of broken cross-refs and links in the process. I also added directives to hide private and deprecated attributes from being included in the documentation. I generated the HTML on my end and it looks great.
~However, I didn't convert the parameter list for the Window class to numpy style just yet. That's going to be pretty involved.~
I also made a bug-fix where the ``setMouseType`` function doesn't do anything. Should probably be converted to a property someday.
=> DOCS: Numpy style docs for the window class

psychopy/app/connections/news.py
As a result, it would always show the news item, which would get very
annoying!
I've inserted this and reduced the category values so that we can set
new announcements to 30 and only newer copies of the app will show them
=> BF: news viewer was not updating its lastNewsDate value

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml
Latest releases of `freetype-py` support recent `freetype`, so no need to restrict `freetype` versions anymore.
**Edit** We don't need an explicit `freetype` dependency as it gets installed along with `freetype-py`.
=> TESTS: Remove freetype dependency

psychopy/experiment/components/settings/__init__.py
This fix solves a problem where routine data was not saved
if no loops came after that routine (because nextEntry was not called).
This current implementation will not work until PsychoJS
Experiment Handler attributes of `_trialsData` and `thisCurrentTrial`
are changed  to `entries` and `thisEntry`, respectively.
=> BF: Find and save orphaned data at end of online task

psychopy/experiment/routine.py
This fixes an issue where Variable components cause AttributeErrors
when datatypes, that do not support attribute assigment, are used in the
component. The issue has arisen following new changes that the track start and
stop times of PsychoPy components. This fix stops Variable comps from being
added to the list of routine components that need start/stop times
recording. Fixes #2499.
=> BF: Leave out Variable components when tracking start/stop times

psychopy/parallel/__init__.py
Some of the API examples for the parallel port still give the impression of needing to call functions of the `parallel` module itself, rather than of a specific instance of the `parallel` class. To avoid confusion  for users (particularly those who are still finding old code examples around), have amended the examples to refer to a named instance `port`, and duplicate showing how it is created within each function's example.
=> DOCS: Change to object-style calls in all parallel port API examples

psychopy/hardware/crs/bits.py
Sets the default mode for CRS button boxes more completely than before. Result is more intuitive if the users does not set all of the modes.
=> ENH: Changes the defaults for CRS button boxs

psychopy/experiment/components/mouse/__init__.py
Redeclaring the prevButtonState in the if statement using let was causing
the prevButtonState to have scope limited to the if statement. This caused
an error when checking the mouse state using the undefined prevButtonState
variable. This only occured when "New clicks only" was deselected.
=> BF: prevButtonState was declared local to a block causing an error

docs/source/builder/components/form.rst, psychopy/tests/test_all_visual/test_form.py, psychopy/visual/form.py
This enhancement means that a minimum number of columns are needed for
Forms, as missing headers/columns are now replaced with default entries.
For example, questionText column is sufficient to create a Form with
Yes/No response items. Incorrect headers are also replaced, but warning
is raised. Also some refactoring. The randomize method works
in place, so no need to return the items. Also updates documentation
with default vals. Tests also updated and no longer check for error with
incorrect headers, as they are now replaced using default values.
=> ENH: Adds default headers for Form when headers are missing

psychopy/event.py
The (actual) coords returned by the retina display are twice the
(virtual) coords returned by the window. So mouse.getPos needs to convert
these back to virtual coords as well (by dividing by 2)
=> BF: with a retina display and Window.units='pix' mouse.getPos needs /2

conda/environment-2.7.yml, conda/environment-3.6.yml, conda/environment-3.7.yml
Remove the `pip <19.0` restriction.
=> TESTS: Recent releases of pip should work for us again

psychopy/experiment/components/settings/__init__.py, psychopy/experiment/loops.py
The endLoopIteration was not being called when isTrials was false, meaning
that the loop could not be broken using loop.finished. Adding the
endLoopIteration function to loops where isTrials is false means that the
a new arg `isTrials` must be passed, because `isTrials` never actually
exists in the `thisTrials` arg, so can not satisfy the else if statement,
and thisTrial can be both defined and undefined when isTrials is false,
meaning nextEntry could be called when it should not be. Now,
endLoopIteration will only call nextEntry if isTrials is true if not
trying to break loop manually.
=> BF: Call endLoopIteration when isTrials is False so loop can be broken

psychopy/visual/window.py
Addresses documentation error noted in #2524
=> DOCS: Correct typo in window.py

psychopy/experiment/components/slider/__init__.py
This fix means slider units are no longer dependent on the screen units
for both local and browser tasks.
=> BF: Allow Slider units to be set via component dialog

psychopy/data/staircase.py, psychopy/tests/test_data/test_MultiStairHandler.py, psychopy/tests/test_data/test_StairHandlers.py
* Parameter estimates must now be retrieved via `.paramEstimate` attribute (used to be `.paramEstimates`)
* Posterior PDFs can now be retrieved via `.posterior` attribute
* tiny changes to tests
=> RF, ENH, TESTS for QuestPlusHandler

docs/source/conf.py
With [`sphinx.ext.viewcode`](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html), users can click on a very subtle "source" link next to each function/method/... in the API docs and that link leads them ... to the source :-)
For example, I was just inspecting [`getActualFramRate` in the API docs](https://www.psychopy.org/api/visual/window.html#psychopy.visual.Window.getActualFrameRate) and wanted to learn a bit more about it ... `sphinx.ext.viewcode` would have made that easier than going to GitHub and clicking on lots of different folders and files, or using a search function in an editor etc.
=> DOC: enable sphinx.ext.viewcode

psychopy/visual/shaders.py
Log from shader compilation needs to be converted to UTF-8 string first before printing to console.
=> BF: Shader log returned as bytes causing string operations fail.

psychopy/experiment/components/_base.py
In this fix, the call to change line color now creates a new instance
of the Color class for that line color.
=> BF: Set line color in JS correctly when parameters update

docs/source/api/tools/gltools.rst, psychopy/tools/gltools.py, psychopy/visual/shaders.py
Added a bunch of useful functions for working with shaders. Includes functions for generating shader programs compatible with existing PsychoPy shader code and newer GLSL specs.
I tried re-writing the `compileShaders` function (haven't committed it) to be dual compatible, using the legacy shader functions when running on Intel drivers. Nvidia doesn't complain when compiling older spec drivers with the newer functions. Not sure about AMD at this point. The point of all this is to deal with shaders failing to work on GLFW when using vertex arrays, they need to use core profile functions to work.
=> NF/DOCS: Added shader functions to gltools

psychopy/constants.py, psychopy/experiment/components/_base.py, psychopy/experiment/components/aperture/__init__.py, psychopy/experiment/components/cedrusBox/__init__.py, psychopy/experiment/components/envelopegrating/__init__.py, psychopy/experiment/components/eyetracker/__init__.py, psychopy/experiment/components/ioLabs/__init__.py, psychopy/experiment/components/joyButtons/__init__.py, psychopy/experiment/components/joystick/__init__.py, psychopy/experiment/components/keyboard/__init__.py, psychopy/experiment/components/mouse/__init__.py, psychopy/experiment/components/movie/__init__.py, psychopy/experiment/components/parallelOut/__init__.py, psychopy/experiment/components/pump/__init__.py, psychopy/experiment/components/settings/__init__.py, psychopy/experiment/components/sound/__init__.py, psychopy/experiment/routine.py, psychopy/sound/backend_ptb.py, psychopy/tests/test_all_visual/test_winFlipTiming.py, psychopy/tools/attributetools.py, psychopy/visual/window.py
Using the `Window.getFutureFlipTime()`, created for PTB sound timing, we can make more accurate timing decisions for Builder output code as well.
=> Timing improvements

docs/source/download.rst
As per request https://discourse.psychopy.org/t/conda-installation/7871/7?u=michael
=> DOCS: Update Conda install notes to Python 3.6

docs/source/api/tools/gltools.rst, docs/source/api/tools/mathtools.rst, psychopy/tools/gltools.py, psychopy/tools/mathtools.py, psychopy/visual/shaders.py
Added function `embedShaderSourceDefs` to `gltools`. This function generates and inserts ``#define`` statements into existing GLSL source code, allowing one to use GLSL preprocessor statements to alter program source at compile time. Using this feature, it is possible to have vertex and fragment shader code in the same source text. It also allows for constants to be defined and render code paths to be pruned at compile time. 
Shader code can be formatted in a file like so (here is the combined code for PsychoPy's FBO blit shader):
```
#ifdef VERTEX
void main() {
gl_FrontColor = gl_Color;
gl_TexCoord[0] = gl_MultiTexCoord0;
gl_TexCoord[1] = gl_MultiTexCoord1;
gl_TexCoord[2] = gl_MultiTexCoord2;
gl_Position =  ftransform();
}
#endif
#ifdef FRAGMENT
uniform sampler2D texture;
float rand(vec2 …
```
=> NF/RF/DOCS: embedShaderSourceDefs, shader source lists, and doc fixes

psychopy/tools/gltools.py
Minor fix, have embedded `#define` statements match the indentation level of the GLSL source code they are being inserted into. This make printing the modified GLSL source code appear neater. Also removed quotations from define values.
=> FF: Have `embedShaderSourceDefs` use proper indentation level.

psychopy/experiment/components/sound/__init__.py
The issue dates back to GH-1710 with an attempt to "reduce spectral
splatter" but it also has the effect that brief sounds don't stop by
themselves (they only stop if a short file)
fixes GH-2564
=> BF: undo the attempt not to force-stop brief sounds

docs/source/api/tools/gltools.rst, psychopy/tools/gltools.py
Reworked the VBO and VAO functions in 'gltools' to handle interleaved buffers. Also added `mapBuffer` functions for accessing and editing GPU buffer data with numpy array pointers. This results in enormous performance gains (multiple orders of magnitude) when drawing and updating arrays over current routines used in `ElementArrayStim`. These methods work on nVidia and Intel cards with fixed-function and core pipelines.
=> NF/DOCS: Advanced VBO and VAO features

psychopy/iohub/removed/devices/serial/__init__.py
Native Py3 strings are unicode. Serial only accepts bytes. Convert from
native to bytes on serial.write() to avoid type error and convert back
to native (utf8) on read so that user can combine with native strings
=> BF: serial read/write in PY3 should convert to/from string

psychopy/app/builder/builder.py, psychopy/experiment/py2js.py
This enhancement ensures that all errors related to the script compiler captured and printed to the stdOutFrame so the use can see what errors have occurred. This does mean though, that the stdOutFrame appears more frequently e.g., when syncing and exporting html. This is only the first step to better error handling. The stdOutFrame as an error message target will be replaced in the new global error handling enhancement, but for now this is better than what is currently in use and so may be useful for the next release.
=> ENH: Better handling of error capture and reporting when compiling scripts

psychopy/experiment/components/keyboard/__init__.py
The status of the keyboard start changes using the function `start`,
there is no need for a second setting to change status attribute. Also,
not having the status change on win.flip affects how stored keypresses
are registered i.e., they can be used to end incorrectly before they
have been cleared. Also, keyboard status should not depend on whether
or not data is stored, so status change no longer conditional on storage.
=> BF: Removes status change and storage condition for starting keyboard

psychopy/CHANGELOG.txt, psychopy/experiment/routine.py, psychopy/tests/test_all_visual/test_winFlipTiming.py, psychopy/visual/window.py
Now reseting trialClock according to time of first known flip
so that t=0 is always the time of the first flip for all stimuli
=> FF: fix to timing. Account for first flip tStart>0

requirements_travis.txt, setup.cfg
Pathlib is in the Python 3.4 standard library after PEP 428 acceptance.
=> ENH: Add pathlib dependency for Python versions < 3.4

psychopy/app/builder/builder.py
=> BF: Make subprocess.Popen params Py2 and Py3 compatible

psychopy/app/builder/builder.py
Trackback error messages were starting on the StdOutFrame and finishing
on the console. Also, an error occured randomly causing psychopy to crash.
The crash would happen when printing whilst a traceback was printed.
With this fix, the crash has not reoccurred.
=> BF: Print errors to stdoutFrame

psychopy/app/stdOutRich.py
Without this, the stdoutFrame would not show again after being closed.
=> BF: Bind EVT_CLOSE to stdoutFrame closeFrame method

psychopy/experiment/components/cedrusBox/__init__.py
In Builder, when using a variable for allowedKeys of CedrusBox component, the compilation would fail. Code generation now uses same code style as keyboard component.
=> BF: compilation fails if allowedKeys for Cedrus Box are a variable

psychopy/data/staircase.py, psychopy/tests/test_data/test_StairHandlers.py
This is necessary e.g. when `QuestPlusHandlers` are created via a `MultiStairHandler`, and all "MultiStair conditions" are passed down to `QuestPlusHandler`. These are now all swallowed through a `**kwarg` in the signature. To warn users of potential typos in their code, a warning will be emitted if one or more unknown kwargs are encountered.
=> BF: QuestPlusHandler now accepts "unknown" kwargs

docs/source/builder/components/form.rst, psychopy/demos/builder/BigFiveInventory/bigFiveItems.csv, psychopy/demos/builder/BigFiveInventory/demographics.csv, psychopy/tests/test_all_visual/test_form.py, psychopy/visual/form.py
This fix stops the aperture from being drawn when the Form is created.
This was causing the aperture to persist over all routines, until the
Form was actually drawn, where the aperture could be disabled.
=> BF: Disable the Form aperture on creation, enable only on draw

psychopy/iohub/devices/serial/__init__.py
Fixes setLampState in Python 3.
=> BF: iohub PstBox P3 compat

psychopy/data/staircase.py, psychopy/tests/clock/test_clock.py, psychopy/tests/test_data/test_StairHandlers.py
`.currentDirection` and `.stepSizeCurrent` attribs don't make sense for QUEST+ and only lead to confusion when their default values appear in logs. The `.stepType` attrib is never used (we use `.stimScale` instead). This PR ensures that we don't write any of these attribs to the `MultiStairHandler` data files any longer: the columns `direction`, `stepSize`, and `stepType` will not be included anymore.
=> RF: In QuestPlusHandler, Initialize unused inherited attribs (to avoid confusion), and exclude them from being written to the MultiStairHandler log

psychopy/experiment/components/settings/__init__.py, psychopy/tools/versionchooser.py
The filtering removes the option to select a Major release version from
the drop down menu, whilst preserving the ability to retrieve these values
from version retrieving methods.
=> ENH: anchors version for blank/latest, and filters single val versions

psychopy/experiment/_experiment.py
This was being raised when using a conditions file contained rows to control
subsets of a conditions file. The entry (e.g. 0:5 ) would look to the
code like it might be a file location (e.g. c: ) because we only used the :
to indicate a file path
=> BF:  ERROR path is on mount ‘0:’, start on mount ‘C:’

psychopy/tools/gltools.py
Fixes an issue where too many arguments are being passed to `setVertexAttribPointer` when creating a VAO.
=> FF: Too many arguments being passed to `setVertexAttribPointer`

docs/source/api/visual/pie.rst, psychopy/demos/coder/stimuli/kanizsa.py, psychopy/visual/__init__.py, psychopy/visual/pie.py
Here is a stimulus class that create "pie" shapes, which is a circle with a wedge cut out. This is usually called a pac-man shape in the VS community. Typically, you would use these to generate Kanizsa figures. This is a pretty well-known illusion and it might be useful to have this class for teaching. You can also use these shapes in applications where you need to visually represent a proportion. For instance a visual countdown timer where filled proportion of the shape shrinks with time. 
The shape takes arguments `start` and `end` in degrees, which defines the filled region of the shape. Using negative values will fill in the opposite direction. The size of the shape is defined by `radius`. The code which generates the vertices is pretty fast, so you can make updates to these values in …
=> NF: `Pie` shape class for pac-man shapes.

docs/source/api/preferences.rst
#fixes  #2651
You can set the preferred audio backend. However, it is not in prefs.general, but in prefs.hardware.
=> DOC Update preferences.rst

psychopy/visual/rect.py
Fixes issue #2644 by aliasing `width` and `height` with `size`.
Behavior of `__init__` has been changed to use `size` only to set the dimensions of the rectangle. Keyword arguments `width` and `height` set `size`. If `size` is specified, the values of `width` and `height` are ignored. Documentation has been updated to reveal this new behavior. Attributes `width` and `height` can be set after initialization so operations may be used to manipulate the shape of the rectangle in one dimension. Changing the size attribute will also update the values of `width` and `height`.
=> RF: Have attributes `width` and `height` aliased with size in `RectStim`.

psychopy/visual/dot.py
Went through the code and optimized some areas of `DotStim` to handle substantially more dots than before. Looks like most of the slowdown was caused by the Python `sum` function being used on `ndarrays` instead of the `Numpy` one which is several orders of magnitude faster. I also cleaned up some docstrings and comments. The documentation needs some love, really inconsistent style in there.
=> EN/RF: Faster DotStim

psychopy/data/staircase.py, psychopy/experiment/loops.py, psychopy/tests/test_data/test_MultiStairHandler.py, psychopy/tests/test_data/test_StairHandlers.py
`MultiStairHandler` now supports a `fullRandom` randomization method. We do this by sampling with replacement from the list of all running staircases on each "pass".
To make this testable, I also added a `randomSeed` kwarg to `MultiStairHandler`, which is used to seed a `np.random.RandomState` RNG. All randomization operations are then being done through that object.
Closes GH-2635.
=> NF: Add fullRandom method to MultiStairHandler

docs/source/api/tools/mathtools.rst, docs/source/api/tools/rifttools.rst, docs/source/api/visual/rift.rst, docs/source/conf.py, psychopy/data/staircase.py, psychopy/demos/coder/hardware/RiftHeadTrackingExample.py, psychopy/demos/coder/hardware/RiftMinimal.py, psychopy/demos/coder/stimuli/dots.py, psychopy/tools/arraytools.py, psychopy/tools/gltools.py, psychopy/tools/rifttools.py, psychopy/visual/__init__.py, psychopy/visual/rift.py, psychopy/visual/window.py
Here's the big one. This is the update to the Rift class for PsychXR 0.2+. This adds loads of new features to the Rift class that come with nearly a year's worth of development to PsychXR in a laboratory environment. 
* You are now able to easily use arbitrary head pose data to compute eye locations.
* Added tweaks specific for the Rift S.
* Removes all of the math functions from the Oculus library in favor of the new `LibOVRPose`. This greatly simplifies rigid body transformations in VR scenes. If you want to do some math that is not available through `LibOVRPose`'s methods, nearly all of it is in `mathtools` library now. Furthermore, PsychXR returns vectors, matrices, and quaternions as numpy arrays. So you can use them more readily with your code. The `LibOVRPose` object will have a …
=> RF: Update `Rift` class to use PsychXR 0.2+

docs/source/api/visual.rst, docs/source/api/visual/sceneskybox.rst, psychopy/demos/coder/misc/rigidBodyTransform.py, psychopy/demos/coder/stimuli/stim3d.py, psychopy/tools/gltools.py, psychopy/visual/__init__.py, psychopy/visual/shaders.py, psychopy/visual/stim3d.py, psychopy/visual/window.py
Changes:
* Adds a Blinn-Phong material for use with 3D stimuli replacing Phong only. This material is a better approximation of real lighting.
* Adds a skybox object for rendering backgrounds with cubemaps. Useful for VR environments. This class came with the original version of PsychXR.
* `clearBuffer` can also clear depth and stencil buffers.
* Added `resetViewport` function.
* Made the default depth compare function `less`, which is the OpenGL default.
=> EN/NF: SceneSkybox and BlinnPhong material

psychopy/visual/backends/glfwbackend.py, psychopy/visual/backends/pygletbackend.py, psychopy/visual/window.py
Adds the ability to configure the pyglet backend to use 10 bit displays. This gives the pyglet backend the same feature as the GLFW backend.
=> NF: 10-bit display support for pyglet backend

docs/source/api/visual.rst, docs/source/api/visual/boundingbox.rst, psychopy/tools/mathtools.py, psychopy/tools/viewtools.py, psychopy/visual/__init__.py, psychopy/visual/stim3d.py
Two features to make the 3D support more useful.
* `BoundingBox` is a class that attaches to `RigidBodyPose` which is used for visibility culling. This is a feature ported over from PsychXR to give users a pure-python option. All 3D stimuli when created generate a bounding box automatically. They have a `isVisible` attribute to determine if they shouldn't be drawn as all the geometry falls outside of the viewing frustum. 
* `cursorToRay` computes a direction vector between the eye point and the mouse cursor location. This allows you to convert a 2D screen location to a 3D direction or position if you transform the vector using the view matrix. This allows you to implement ray picking so you can click on 3D objects in the scene.
=> NF: Added `cursorToRay` and `BoundingBox`

psychopy/visual/stim3d.py, psychopy/visual/window.py
Built-in method for the window class to convert screen coordinates to a direction vector which projects from the line of sight of the viewer through the cursor or some other screen coordinate. This allows you to position 3D objects in a scene at the cursor and implement ray picking. Also, you can use the screen coordinate given by eye trackers to calculate the direction someone is looking in the scene, and possibly what they are looking at. Also opens up possibilities for gaze contingent 3D graphics displays.
Right now the only raypicking algorithm in PsychoPy is for planes (included an example), however I someday port over the one from PsychXR for bounding spheres and possibly boxes too.
=> NF: `coordToRay` method for window class

psychopy/tools/gltools.py, psychopy/tools/mathtools.py, psychopy/visual/stim3d.py
Added support for instanced VAOs to gltools. This allows for blazing fast drawing and updating of multiple discrete meshes (quads, circles, cubes, etc.) with very few API calls. This can be used to create absolutely enormous fields of nearly anything and vary their properties in nearly any dimension. Requires shaders to utilize this feature.
=> NF: Instanced VAOs

psychopy/experiment/routine.py
This addresses a regression in version 3.2.0 in which setting `continueRoutine = False` no longer has an effect in Builder code components (because the Builder-generated code overrides the custom code by always resetting `continueRoutine = True` immediately before the routine begins). All this pull request does its shift `continueRoutine = True` to be first rather than last in the order of execution prior to a routine, so that custom code can override it.
For recent bug reports, see:
https://discourse.psychopy.org/t/continueroutine-false-in-begin-routine-tab-has-no-effect/9801
and for previous development history, see:
https://github.com/psychopy/psychopy/issues/1143
=> BF: Fix regression in continueRoutine behaviour

docs/source/api/tools/mathtools.rst, psychopy/demos/coder/misc/rigidBodyTransform.py, psychopy/tools/mathtools.py, psychopy/visual/rift.py, psychopy/visual/stim3d.py
This function computes the intersect of a ray and bounding box of arbitrary orientation. This is likely the most useful of the ray picking algorithms included with PsychoPy. Allows you to find the intersect for `RigidBodyPose` objects and 3D stimulus classes which use it.
=> NF: Added intersectRayOBB

.travis.yml, createInitFile.py, psychopy/hardware/crs/bits.py, psychopy/tests/test_all_visual/test_all_stimuli.py, setup.cfg, travis/environment-2.7.yml, travis/environment-3.6.yml, travis/environment-3.7.yml, travis/environment-3.8.yml
- Make `hardware/crs/bits.py` and `createInitFilt.py` work on Python 3.8
- Add `pytest` marker for PyGame visual tests
- Skip PyGame tests on Python 3.8 for now due to unavailability of Linux wheels
=> TESTS, ENH: Enable Python 3.8

psychopy/experiment/components/movie/__init__.py
Previously, this was conditional on the useInits arg, which meant that
movies created at the beginning of routines would have incorrect params
if the params were None.
=> BF: Write movie params as undefined if param is None.

psychopy/tests/test_tools/test_mathtools.py, psychopy/tools/mathtools.py, psychopy/visual/stim3d.py
Fixes small issues and adds `normalMatrix` computation for rigid bodies needed for incoming PBR material shaders.
* Fixes incorrect argument name after refactor of mathtools.
* Adds the ability to compute a normal matrix from a rigidbody, this is needed by shaders and could be computed JIT only if a rigid body is transformed between frames.
This also should test out if Travis is enabled.
=> BF/NF: Fixed argument `rayDir` and JIT computation of normal, inverse and model matrices.

psychopy/app/builder/dialogs/dlgsCode.py
`has<Module>` is the preferred naming convention.
=> RF: Use consistent naming convention for module test

psychopy/alerts/_alertDialog.py, psychopy/alerts/alertsCatalogue/9998.yaml, psychopy/app/pavlovia_ui/project.py
Alerts now formatted using rich text rather than list control. URLs
that point to help pages created from the alerts catalogue
are opened using python built-in webbrowser, which uses the default
browser for loading the webpage.
Next step should be to create the runner frame, and present the alerts each time a script is compiled or run.
=> ENH: Presents rich text alerts

psychopy/contrib/quest.py, psychopy/data/staircase.py, psychopy/tests/test_data/test_StairHandlers.py
Update QUEST documentation to clarify meaning of parameters of the psychometric function, based on my research found [here](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/515#issuecomment-564293107) and in the following comments. Also expose the `epsilon` parameter.
Closes #2722.
=> DOC, ENH: QUEST improvements

psychopy/visual/dot.py
Up to now, the coordinates of new dots were sampled from the same
uniform probability distribution with a range of [-width/2, height/2) in
DotStim._newDotsXY().  This is presumably a bug; X coordinates should be
sampled from [-width/2, width/2), and Y coordinates from [-height/2,
height/2).
Under the previous behaviour, some of the stimulus field would go
unused, whereas some new dots would be randomly placed in an
out-of-field position before being removed one frame later by
DotStim._update_dotsXY().  This patch fixes these problems.
=> Correct range for X and Y coordinates of new DotStim dots

psychopy/alerts/alerttools.py, psychopy/experiment/py2js.py
The refactor did not catch use of variables in all cases. Variables cause
errors when converting to float, since variable names are strings.
This fix checks each value can be converted to a float
(meaning it is a number), but is now more specific so start and end
times are checked independently. Also handles syntax errors in dialog
boxes, so real time syntax errors are not raised and printed to console,
but caught and thus allowing the dialog to perform its syntax warnings.
=> BF: Fixes alerttool error from refactor.

psychopy/demos/coder/stimuli/variousVisualStims.py
Since `MovieStim` seems to be deprecated in favor of `MovieStim3` (#1532), I thought it would be a good idea to use `MovieStim3` in `variousVisualStims.py`. The demo threw an error on my fresh Windows installation, but it works with `MovieStim3`.
=> Use MovieStim3 in demo

conda/psychopy-env.yml
Playing sounds with `psychtoolbox` requires `SoundFile`, which I've added to the conda env so that this gets installed automatically.
=> Add SoundFile to conda env

conda/psychopy-env.yml
Follow up for #2730.
It is not necessary to specify `pip` because this package is installed by default in any conda env. Furthermore, what do you think about removing `pygame`? This is the oldest backend and PsychoPy ships with better options.
=> Use platform markers in conda env

psychopy/data/staircase.py, psychopy/tests/test_data/test_StairHandlers.py, setup.cfg, travis/environment-3.6.yml, travis/environment-3.7.yml, travis/environment-3.8.yml
Users may now pass a dict that contains only a subset of the supported options (needed to contain _all_ options before, otherwise it would throw an error). Requires `questplus` 2019.2.
=> ENH: Better handling of QuestPlus stimSelectionOptions

createInitFile.py, psychopy/app/connections/sendusage.py, psychopy/app/connections/updates.py, psychopy/demos/coder/hardware/testSoundLatency.py, setup.cfg
Fixes #2733.
I've only replaced the `platform.dist` calls, but I noticed problems that should be fixed in another PR:
- https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/hardware/testSoundLatency.py#L99 concatenates a `str` and a `tuple`
- https://github.com/psychopy/psychopy/blob/master/psychopy/app/connections/updates.py contains undefined names `unicode`, `time`, and `platform`
=> Replace platform.dist with distro.linux_distribution

psychopy/sound/backend_pyo.py
The `pyo` backend currently uses `sounddevice.query_devices()` to get a list of audio devices. This means that `sounddevice` needs to be installed just because of this function even if `pyo` is used for everything related to sound input/output.
Actually, `pyo` includes a query function, which unfortunately doesn't return a value but prints to stdout. I've written a small function to convert this to what PsychoPy needs. This means that the `pyo` backend no longer needs the `sounddevice` module.
=> Remove sounddevice in pyo backend

psychopy/gui/qtgui.py, travis/environment-2.7.yml, travis/environment-3.6.yml, travis/environment-3.7.yml, travis/environment-3.8.yml
Addresses #2741, but only in PyQt.
This change makes Dlg use the primary display if the screen that was asked for does not exist. As I use standalone and therefore PyQt, this fixed the issue for me.
=> BF: Use primary display for Dlg if screen is unavailable

psychopy/data/staircase.py, psychopy/tests/test_data/test_StairHandlers.py, setup.cfg, travis/environment-3.6.yml, travis/environment-3.7.yml, travis/environment-3.8.yml
This also pins Travis's Python 3.7 to 3.7.3, as 3.7.6 (latest 3.7 release on conda-forge) exposes a bug in pyglet's xlib support: https://github.com/pyglet/pyglet/issues/112
=> ENH: Allow specification of QuestPlus prior probabilities

travis/environment-3.6.yml, travis/environment-3.7.yml, travis/environment-3.8.yml
Prepares for changes in Python 3.7.6, and future 3.6 and 3.8 releases to come:
https://github.com/pyglet/pyglet/issues/112
Note that we still run tests with pyglet 1.3 too.
=> TESTS: Require pyglet 1.4.9+

psychopy/alerts/__init__.py, psychopy/alerts/_alerts.py, psychopy/alerts/alerttools.py, psychopy/tests/test_alerts/test_alerts.py
catalogue -> catalog
stringFormat -> stringFields (strFormat usually refers to a format string
not a dict)
import alert and catalog into psychopy.alerts as the key entrypoints
=> RF: alerts with american spellings and simpler string format

psychopy/alerts/_alerts.py, psychopy/alerts/alertsCatalogue/2115.yaml, psychopy/alerts/alertsCatalogue/2120.yaml, psychopy/alerts/alertsCatalogue/2155.yaml, psychopy/alerts/alertsCatalogue/3110.yaml, psychopy/alerts/alertsCatalogue/3115.yaml, psychopy/alerts/alertsCatalogue/4105.yaml, psychopy/alerts/alertsCatalogue/4115.yaml, psychopy/alerts/alertsCatalogue/4205.yaml, psychopy/alerts/alertsCatalogue/4210.yaml, psychopy/alerts/alertsCatalogue/4305.yaml, psychopy/alerts/alertsCatalogue/4310.yaml, psychopy/alerts/alertsCatalogue/9998.yaml, psychopy/alerts/alertsCatalogue/9999.yaml, psychopy/alerts/alertsCatalogue/alertTemplate.yaml
Previously it was set so that the alert in the script/app didn't
have access to the full details (e.g. long descr) but that's unecessary
and for generating the web pages it's easier if it *does* have access to
all parts of the alert info
=> RF: alerts definition should be allowed to store all info

psychopy/alerts/alerttools.py, psychopy/tests/test_alerts/test_alerttools.py
Using % operator for floats gives some odd answers!
e.g. 0.5%0.01 gives 0.00999 but should be 0 (0.01*0.5 is exactly 50!)
so use our own function instead
Also removed the 100Hz tests although we should, at some point, allow
users to specify the rate of their monitor for these tests
=> FF: Fix validDuration calculation for frames

docs/source/api/iohub/device/eyetracker_interface/SR_Research_Implementation_Notes.rst, psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/eyetracker.py
byte arrays are now converted to strings before being passed to pylink.sendMessage()
=> BF: iohub eyelink device sendings messages as byte arrays

psychopy/app/_psychopyApp.py, psychopy/app/dialogs.py, psychopy/hardware/keyboard.py
Better info to user for how to turn on the necessary privacy settings to use PTB keyboard class:
- in keyboard.py we now detect that PTB keyboard didn't work. Falls back to using the event.getKeys Keyboard class if PTB can't be used
- the app detects that the PTB keyboard not working (from the above mechanism) and provides a dialog taking the user to the appropriate setting in System Preferences (the Assistance panel for<=Mojave and the InputMonitoring panel for >=Catalina
=> Better mac keyboard handling

psychopy/app/_psychopyApp.py, psychopy/preferences/Windows.spec
I noticed Builder and Coder are pretty blurry on Windows on my high-dpi display, it makes some text completely illegible for me. I added a preference that enables High-DPI awareness which makes text rendering and graphics appear much sharper. Scaling is messed up in some places, so the feature is disabled by default and flagged as experimental.
=> NF: High-DPI awareness on Windows.

psychopy/app/builder/dialogs/dlgsCode.py
Previously, the code type was forced to either Auto->JS, or Both, because
code type selection was conditional based on whether metapensiero was
installed. This fix now unselects Auto->JS if metapensiero is not
installed, but otherwise loads previously selected code type.
=> BF: Code Type is now set correctly on opening the dialog

psychopy/hardware/keyboard.py
Fixing an argument name error in the example code, noted by Rebecca Hirst on the Discourse forum https://discourse.psychopy.org/t/equivalent-of-event-waitkeys-using-keyboard-keyboard/11076
=> DOCS: Fix typo in keyboard.py

docs/source/faqs/versionControl.rst
This leads to, on the FAQ section main page, links to the different subheadings in the document also, see attached screenshot. I wasn't able to disable that unfortunately - please have a go at doing so if you want to.
For background on the suggested new page, see https://discourse.psychopy.org/t/best-practices-for-using-multiple-psychopy-versions-on-one-computer/10749/10 .
=> DOCS: add version control page, linked to from the FAQ section

psychopy/app/_psychopyApp.py, psychopy/app/builder/builder.py, psychopy/app/builder/flow.py
When creating a new loop or collapsing component panes, either the control flickers when moving the mouse around or only partially redraws. This PR double buffers the controls providing a smoother visual experience (on Windows at least). 
Also includes a bugfix for #2818.
=> BF: Double buffer panels/fix high DPI error on Windows <8.1

psychopy/data/utils.py
In the data.importConditions() (lines 276-289) I added a try/except block to allow an automatic loading of csv with either ',' or ';' as separator. 
Now, pandas loads the file without raising errors even if only one column is detected (for example when loading a file separated with semicolon with the argument sep = ',') and the presence of weird punctuation in the dataset is only tested later when the _assertValidVarNames() function is called from within the pandasToDictList() function. Therefore the except function only works if pandasToDictList(trialsArr) is run before it. 
Right now to avoid changing the code too much I have repeated the same block of code twice (and it is used one more time later on for the excel format). It works but it seems to me a bit redundant.
What do you think?
=> BF: make data.importConditions() able to import csv with ',' and ';' separator

psychopy/app/_psychopyApp.py, psychopy/app/coder/coder.py, psychopy/app/errorDlg.py, psychopy/app/preferencesDlg.py, psychopy/preferences/Darwin.spec, psychopy/preferences/FreeBSD.spec, psychopy/preferences/Linux.spec, psychopy/preferences/Windows.spec, psychopy/preferences/baseNoArch.spec
Adds an error dialog box which comes up when an unhandled exception occurs in the GUI application thread, preventing them from going unnoticed until the user checks the output box. It's also a bit more polished than simply dumping errors to the output.
Displays a message informing the user that an internal error occurred and presents the traceback. The dialog has buttons to copy or save the traceback making it easier for the user to get the necessary information for the developers to fix/diagnose the problem. The message also keeps errors from the GUI out of the output window, so subprocess errors are presented separately. At this point, GUI still outputs errors to stdout along with being caught by the dialog (that could be changed now). The user can press OK and continue using the …
=> NF/EN: Error dialog for unhandled exceptions in the GUI thread

docs/source/conf.py
Use the default value for mathjax_path, so sphinx.ext.mathjax loads
MathJax from the cdnjs content delivery network. See documentation of [mathjax_path](http://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax_path). Should fix #2845 .
=> DOC: use default mathjax_path

psychopy/experiment/py2js_transpiler.py
This is a small edit to javascript transpiler to fix the bug specified in #2849  in which python code is upper limit exclusive but the JS code is upper limit inclusive.
=> BF: Fix randint translation to remove upper limit inclusivity.

psychopy/experiment/components/__init__.py
This only really affects developers when going back to older versions of
PsychoPy (that don't have all the builder components of newer versions)
The Components folder can be left with orphaned .pyc files but the old
way to detect those doesn't work for Py3 orphans. In Py3 these appear in
a __pycache__ folder whereas in Py2 they were in the main folder next to
the .py files
=> BF: fixed detection of component orphan files from Py3 installs

psychopy/compatibility.py, psychopy/tools/filetools.py
As reported on discourse:
https://discourse.psychopy.org/t/making-the-fromfile-function-compatible-with-psydat-files-obtained-with-python-2-easy-fix/13785
Thanks to @mservantufc for working out the fix
=> BF: update fromFile to allow files from Python2 versoins to be loaded

psychopy/preferences/preferences.py
Currently the user prefs directory is tested for permissions, however they way this is done causes a `PermissionError` on windows:
```
>>> import os
>>> open("test", "r")
<_io.TextIOWrapper name='test' mode='r' encoding='cp1252'>
>>> os.remove("test")
File "<stdin>", line 1, in <module>
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test'
>>>
```
This change fixes this by opening the file within a context, so the file handle is closed appropriately.
```
>>> import os
>>> with open("test2", "r") as fh:
...     fh.read()
...
''
>>> os.remove("test2")
>>>
```
Debugging this within a build system that uses prebuilt wheels is cumbersome because the code hides the underlying error.
This change …
=> BF: Fix PermissionError on windows in Preferences.getPaths

psychopy/monitors/calibTools.py
Currently the module tries to create the monitors directory if it's missing.
The issue with this is that there is a race condition in how it is implemented:
- The directory could be created between the `os.path.exists` and `os.makedirs` calls.
This change modifies this to use a ask-for-forgiveness approach:
- Try to create the directories, but ignore any "file/directory already exists" errors.
`errno` should work cross-platform, so this will not break multi-platform support.
=> BF: Fix import time race condition in monitors/calibTools.py

psychopy/data/staircase.py
Fixes several small documentation errors, such as typos, in the staircase API documentation.
=> DOC: Fix several typos in staircase API documentation comments

psychopy/gui/qtgui.py
PsychoPy3_PY2 uses Qt4 which can run into errors when trying to count the number of screens (as seen in #2879) as code assumes Qt5 - this checks if using Qt5 or another version, and if not Qt5, applies the older QtWidgets.QtDesktopWidget().screenCount() method to return int for number of screens.
=> BF: Fix for PY2 counting screens for Qt4 distribution #2879

docs/source/builder/settings.rst
For the Builder's data filename documentation, fix the example that
shows how to create data files anywhere on the filesystem.
=> DOC: Fix data filename documentation example

psychopy/app/_psychopyApp.py, psychopy/app/builder/builder.py, psychopy/app/coder/coder.py, psychopy/app/sysInfoDlg.py
Adds a "System Info" menu item to "Help" which displays system information much like how running the "sysinfo.py" script does. However, shows a bit more information and has nicer formatting. The report dialog has buttons to copy the info to the clipboard or save it to a file. 
This is a little more user friendly and discoverable than running the script. It can help people build error reports more easily. 
Output looks like this:
```
PsychoPy 2020.1.3
Paths to files on the system:
userPrefsFile: C:\Users\matth\AppData\Roaming\psychopy3\userPrefs.cfg
appDataFile: C:\Users\matth\AppData\Roaming\psychopy3\appData.cfg
demos: C:\Users\matth\PycharmProjects\psychopy\psychopy\demos
appFile: C:\Users\matth\PycharmProjects\psychopy\psychopy\app\PsychoPy.py
System Info:
Operating System: …
```
=> NF: System information dialog

psychopy/app/builder/dialogs/__init__.py
The params in the Component Dialog boxes were not well-aligned
vertically on windows (fine on Mac). It seems the controls have
different defaults on this platform so we need explicit alignment flags
=> BF: alignment broken on component params on windows

psychopy/app/preferencesDlg.py, psychopy/app/sysInfoDlg.py
Makes copy behavior consistent with the System Info dialog.
=> FF: Copy when there is a selection for System Info

setup.cfg
`json` is a built-in Python library, so it causes this error on attempting installation:
ERROR: Could not find a version that satisfies the requirement json (from PsychoPy==2020.1.3) (from versions: none)
ERROR: No matching distribution found for json (from PsychoPy==2020.1.3)
=> BF: Remove json from setup.cfg

psychopy/experiment/components/__init__.py, psychopy/experiment/components/brush/__init__.py, psychopy/visual/brush.py
Currently to draw with the Brush stimulus requires holding down the mouse button. Allowing drawing without a button press can be useful, and may be easier with trackpads, touch interfaces, and so on.
Also exposed this functionality via the Builder component UI.
***NB this has been implemented only for PsychoPy.*** Equivalent changes would need to be made for PsychoJS. Any volunteers?
Made in response to this forum topic:
https://discourse.psychopy.org/t/creating-a-mouse-trail-for-trail-tracing/15138
=> ENH: Allow Brush to draw without holding down the mouse button

psychopy/app/builder/builder.py, psychopy/app/coder/coder.py
Moves around menus to be more consistent with other applications. Adds an item to File in coder and builder that closes the frame but doesn't close PsychoPy. I've accidently hit Quit thinking it would close the window, but instead it exits the whole suite.
=> RF: Move around menu order, add frame close items.

psychopy/app/builder/dialogs/__init__.py, psychopy/app/builder/dialogs/dlgsCode.py
AuiNoteBook and FlatNoteBook both look nice, with a more standard 'tab'
interface but in our case we don't want tabe that can be moved/closed
and the rendering on the mac of both those is poor on wx 4.1.0
Could revisit in future
=> FF: changed compon dialogs to use wx.NoteBook instead of AUI or Flat

psychopy/app/_psychopyApp.py
This pull request implements the fix for the problem described in issue #3065
=> BF:  FixFont error caused when SetFaceName() is called for .AppleSystemUiFont

psychopy/gui/wxgui.py
Fixes the `TypeError: expected string or bytes-like object` error caused by passing a float to the RegEx search.
=> Fix RegEx error

psychopy/clock.py
Proposing a docstring for `CountdownTimer.reset()`. Previously, at least on the API docs on the web, it was inheriting the description of the reset method for Clock, which works differently. (In particular, it's not the case that "With no args time will be set to zero.")
=> DOC: Clarify differences between reset() for CountdownTimer vs. Clock

psychopy/visual/textbox2/fontmanager.py
Fix "Can't start PsychoPy if fonts don't have family name" #3084
=> BF: don't call _createFontInfo() if font doesn't have family name

psychopy/experiment/components/mouse/__init__.py
Previously we were defining the `xys` and `buttons` with local scope.
Instead remove that local definition (const/let) and the script compiler
will then automatically give it global scope (var at the top of the script)
To avoid likely clashes we've given more obscure names:
- `_buttonXYs`
- `_mouseButtons`
fixes psychopy/psychojs-88
=> BF: handle multiple mouse objects in one Routine in JS

psychopy/app/runner/runner.py, psychopy/app/runner/scriptProcess.py
fixes GH-3142
Also some reports of the wrong script running?
We now;
- track if the script process is running and use that to determine
whether RunBtn should be enabled:
just runBtn.Enable() during onSelectedItem if not running
- store a dict of entries for the ListCtrl rather than searching for
the items (ListrCtrl FindItem is poor)
- don't hard-code the column numbers - what if we change them later?
=> BF: Runner file selection issues

psychopy/visual/ratingscale.py
=> BF: Reset marker color after a response

psychopy/experiment/components/settings/JS_htmlHeader.tmpl
@peircej @apitiot Tweak script tag for linking to the latest version of PixiJS as required to address psychopy/psychojs#168. Closes #3144, but would need to be pulled in together with psychopy/psychojs#181 if at all possible to avoid any accidents  :blush:
=> experiment/settings/JS_htmlHeader: link to pixi latest (5.3.3)

psychopy/demos/builder/ratingsNew/ratingsNew.psyexp
Use norm units in experiment, and then use experiment settings in demo, so sliders are visible. Fix typos in ratingsNew demo also. Should resolve #3149.
=> Use norm units in demo, fix typos

psychopy/experiment/components/slider/__init__.py
Add depth parameter to Slider writeInitCode and writeInitCodeJS
methods so sliders are rendered in the same order they are displayed
in the routine canvas. Should resolve #3154.
=> BF: Add depth parameter to Slider writeInitCode

setupApp.py
setupAppp needs to package parso outside the site-packages.zip
fixes #3170
=> BF: macOS Standalone crashing with autocomplete turned on

psychopy/app/builder/validators.py
Hi,
I've been debugging a PsychoPy experiment which failed running on PsychoJS (on Pavlovia), here's what went wrong:
1. The experiment contained a Sound item whose sound value was set to `$sound`, which corresponded to a variable set in an xlsx column "sound". However, the sound value was left as 'constant' instead of 'set every repeat'.
2. This results in an initialization statement being generated at the beginning of the experiment, which looks like that:
```
sound_1 = sound.Sound(sound, secs=1.0, stereo=True, hamming=True,
name='sound_1')
```
Later during the actual trial, the correct sound file is loaded like so:
```
sound_1.setSound(sound, hamming=False)
```
3. In the first snippet above, `sound` is a reference to the PsychoPy sound module, while in the second snippet it is a local …
=> Warn user when reusing global symbols as variables

psychopy/app/builder/builder.py
this is due to deprecated "topFlow" pref
=> BF: Builder was raising error when right clicking on components

psychopy/app/builder/builder.py, psychopy/app/coder/coder.py, psychopy/tests/test_tools/test_mathtools.py, psychopy/tools/mathtools.py
A bug-fix and touch-ups ...
* This PR fixes an array broadcasting issue with the `distance` function in `mathtools`, were the 1-to-many calculation was incorrectly setting up an output array with the wrong size, causing a hard crash if you tried using it that way. This is a show-stopper bug so it wouldn't have silently screwed up anything people were doing.
* Added some better tests for the `distance` function which covers some other functions too. I've also improved the tests for matrix and quaternion rotation functions to ensure they give similar results when applied to the same set of random points. 
* Removed the `matrixAngle` function since it's pretty useless, it's simpler to just convert the matrix to a quaternion and get both the axis *and* angle from that.
* Calculations for …
=> BF/TESTS: Fixed broadcasting issue with `distance` function, added better tests.

docs/source/coder/codeTrials.rst
The link to TrialHandler class was not working, but StairHandler was, therefore I changed to the same format.
In the past years I have seen multiple researchers asking for an oddball trial handler. I developed a solution quite some time ago and it still seems to work, so I added the link in the docs.
=> DOC: Fixed link to TrialHandler, added link to TrialHandlerExt

psychopy/experiment/components/settings/JS_htmlHeader.tmpl
@apitiot @peircej To help with https://github.com/psychopy/psychojs/issues/211. Parallel post upgrade PsychoJS tweaks are required for which a separate PR is in the works, closes #3218
=> experiment/settings/JS_htmlHeader: rely on Tone.js latest (14.7.61)

psychopy/visual/textbox2/textbox2.py
Uses Color class as a one-off fix to be over-written when the class is fully implemented
=> BF: Fix to textbox colors

psychopy/experiment/components/_base.py, psychopy/experiment/components/movie/__init__.py
While trying to fix an issue on discourse caused by user err with $ sign we
ended up removing the js-translation of all code in 275d2ab
fixes gh-3241
=> Fixes to JS script Builder outputs

psychopy/alerts/alertsCatalogue/4305.yaml
People don't necessarily remember how they disabled a component (e.g. this thread: https://discourse.psychopy.org/t/how-to-enable-a-disabled-component/17896), so now provide more explicit details here.
=> DOCS: Alert 4305 additional content

psychopy/monitors/calibTools.py
Delay loading scipt.optimize unless/until it's actually needed
I don't know *why* scipy.optimize doesn't load on machines with bitlocker
and the fix here won't solve the problem for those that need gamma
correction but it mitigates the issue for all those that don't need
gamma and bitlocker at the same time
fixes #3286 #3229
=> BF: some machines (with bitlocker?) were failing b/c scipy.optim failed

psychopy/experiment/_experiment.py, psychopy/experiment/flow.py
This is essential to make sure that it can be used for importing
=> BF: move the BeforeExperiment JS code to come before the first function

psychopy/experiment/components/_base.py
This was omitted from writing the PsychoJS script in the days where
log=False was not supported but it is now so make sure it's used.
This is likely to have contributed to dynamic stimuli memory leak
and to the massive log files being uploaded to Pavlovia
=> BF: PsychoJS script should also not log params that "set every frame"

psychopy/app/themes/Classic.json, psychopy/app/themes/ClassicDark.json, psychopy/app/themes/GitHub.json, psychopy/app/themes/HiVisDark.json, psychopy/app/themes/HiVisLight.json, psychopy/app/themes/MinimalDark.json, psychopy/app/themes/MinimalLight.json, psychopy/app/themes/PsychopyDark.json, psychopy/app/themes/PsychopyLight.json
An enhancement, but could go in a bug fix release as the only files changed are theme spec and these are all very standard parameters. The dark green on PsychopyLight was just bugging me...
=> ENH: Italic docstrings, remove off-scheme green from PsychopyLight

docs/source/general/dataOutputs.rst
Replace old example (which was written for Python 2 and didn't wo…rk) with new examples for using .psydat files. Update the relevant documentation and make it more beginner-friendly, emphasizing the data retrieval/restoration aspect.
The former example for handling .psydat data doesn't work with the most recent versions of PsychoPy since it uses Python 2 commands (`print` as a statement, not a function) and attributes that ExperimentHandler instances no longer have (`datFile.data`). I added an example that introduces what is probably the use case most relevant to the widest audience, retrieving/restoring data not set to be saved in PsychoPy code/Builder. I wasn't sure what the expected output of the old example used to be or how to recreate it using the latest PsychoPy version, but I …
=> DOC update .psydat-related documentation in dataOutputs.rst

psychopy/visual/basevisual.py, psychopy/visual/textbox2/textbox2.py, psychopy/visual/window.py
not on init, meaning it is only editable when on screen. Fixes #3267, overrides #3269.
=> RF: Set textbox editable on change to autoDraw, 

docs/themes/psychopy_bootstrap/navbar.html
The links in the Documentation dropdown menu of the navbar used relative paths to HTML documents. This didn't work when the navbar was presented in a subdirectory (such as over [here](https://www.psychopy.org/online/index.html)). By replacing the link targets with pathto pointing to the right Sphinx documents, I resolved this issue.
=> Fix paths by having pathto(...) point to the right Sphinx documents

docs/source/builder/components/slider.rst, psychopy/experiment/components/slider/__init__.py, psychopy/visual/slider.py
I am opening a new pull request to update SliderComponent documentation, because the documentation added in #3146 was copy-paste of the RatingScale component documentation. This PR also fixes the link to documentation in SliderComponent, and fixes the pointer to Slider demo. Should resolve #3152 and #2985.
=> DOC: Update Slider component documentation

psychopy/experiment/routine.py, psychopy/tests/data/correctScript/js/correctTextComponent.js
The output tried to return early (as if in the eachFrame block) whereas
what it should have done was store continueRoutine as a global.
Key changes
--------------
1. Set continueRoutine as a global at *top* of beginRoutine code block
so it can be modified later in that block
2. remove this line from eachFrame (it would undo above fix)
let continueRoutine = true; // until we're told otherwise
3. remove the erroneous code where the return Scheduler.Event.NEXT was
made dependent on continueRoutine
=> BF: beginRoutineJS code was broekn if continueRoutine==False

psychopy/data/staircase.py, psychopy/event.py, psychopy/hardware/__init__.py, psychopy/iohub/util/__init__.py, psychopy/tests/test_hardware/test_ports.py
=> Import ABC from collections.abc for Python 3.9 compatibility.

psychopy/demos/builder/spatialUnits/unitDemo.psyexp
The new units demo is great but the instruction text could easily be occluded by the white square - the user could get stuck if they didn't know the keys to press to change units. Changed drawing order and text colour to make the instructions always visible.
=> BF: Retain text visibility in units demo

psychopy/experiment/components/settings/JS_htmlHeader.tmpl
@peircej @apitiot Tweak script tag for linking to the legacy browser supporting version of PixiJS as required to address psychopy/psychojs#228. Closes #3361
=> experiment/settings/JS_htmlHeader: link to pixi.js-legacy (5.3.3)

psychopy/tools/versionchooser.py
Correctly sort versions from high to low. Below is some test script that demonstrates the fix and the new behaviors of psychopy.tools.versionchooser 
```python
from packaging.version import parse as parse_version
versions = ['3.2.4', '3.2.3', '3.2.2', '3.2.1', '3.2.0', '3.1.5', '3.1.4', '3.1.3', '3.1.2', '3.1.1', '3.1.0', '3.0.7', '3.0.6', '3.0.5', '3.0.4', '3.0.3', '3.0.2', '3.0.1', '3.0.0', '2020.2.6', '2020.2.5', '2020.2.4', '2020.2.3', '2020.2.2', '2020.2.1', '2020.2.0', '2020.1.3', '2020.1.2', '2020.1.1', '1.90.2', '1.90.1', '1.90.0', '1.85.6', '1.85.4', '1.85.3', '1.85.2', '1.85.1', '1.85.0', '1.84.2', '1.84.1', '1.84.0', '1.83.04', '1.83.03', '1.83.01', '1.83.00', '1.82.01', '1.82.00', '1.81.03', '1.81.02', '1.81.01', '1.81.00', '1.80.06', '1.80.05', '1.80.03', '1.80.02', …
```
=> BF: Fix version sorting

psychopy/app/preferencesDlg.py, psychopy/visual/__init__.py
I haven't contributed to psychopy before, so if something more is needed, please let me know and I'll happily put in the extra work! :)
I found that on my laptop display, the stimulus images looked blurry and scaled. This PR adds an option to set high DPI support on windows for visual stimuli. This also fixes a problem where the reported size of the screen/display/windows differs from the actual size in pixels.
With high DPI support disabled:
`3.3480  WARNING         User requested fullscreen with size [3200 1800], but screen is actually [1829, 1029]. Using actual size`
```python
from psychopy import prefs
prefs.hardware['highDPI'] = False
visual.ImageStim(win, image)
````
With high DPI support enabled:
```python
from psychopy import prefs
prefs.hardware['highDPI'] = True …
```
=> Add high DPI support for visual stimuli.

psychopy/sound/backend_pyo.py
The methods to get input/output sound devices info in the pyo backend
rely on a parsing of the output of `pyo.pa_list_devices()`. It splits
the fields (name, host api index, latency, default sr) by splitting
on commas. This is fragile as the name can contain commas (e.g.
"Logitech USB Headset: Audio (hw:1,0)"), which leads to `IndexError:
list index out of range` error.
`pyo` provides a method [`pa_get_devices_infos()`](https://github.com/belangeo/pyo/blob/274ed61d6664d44d23416957e781b8afbb559589/src/engine/pyomodule.c#L139) that returns 2
dictionaries for input and output devices, almost exactly in the
expected format as returned by the current implementation of
`_query_devices()`. The only differences are in the fields values: no
units ("Hz", "s"), do not split the name to exclude the …
=> FF: Make pyo parsing of devices more robust

psychopy/visual/textbox2/fontmanager.py
Textboxes were randomly presenting in bold sometimes as Arial Black (and similar fonts) were being identified as non-bold, so bold=False would pick the first one of these fonts returned by the system. BF commit is a quick fix to prevent random bolding, ENH commit extends this to create a more specific and robust method of translating from bold True/False to font weight keywords
=> BF+ENH: Textbox random bold bug

psychopy/app/builder/dialogs/paramCtrls.py
was causing issues when specifying strings with a US mac keyboard
=> BF: Replace unescaped curly quotes in code

psychopy/experiment/components/_base.py, psychopy/experiment/components/grating/__init__.py, psychopy/localization/__init__.py
This PR exposes the [contrast parameter](https://www.psychopy.org/api/visual/gratingstim.html#psychopy.visual.GratingStim.contrast) for visual GratigStim in the Builder UI. 
I modeled it after the Opacity parameter. Ran tests and did not see any errors related to this commit.
=> NF: add contrast parameter to visual grating component in builder UI

psychopy/app/builder/dialogs/__init__.py
Until we've implemented inputType dropdowns
=> BF: Temporarily comment out spinners and use textCtrl instead

psychopy/experiment/experiment.xsd
I think this is what's crashing Travis for every pull request - looks like an older version of the experiment schema which doesn't have the new inputTypes / valTypes in got pulled in somehow
=> BF: Update experiment schema

psychopy/visual/window.py
This adds a new `getContentScalingFactor` method and `contentScalingFactor` property to `Window`. This will give the scaling factor required to convert between framebuffer and client coordinates when using HiDPI displays including the retina type. This can be used to remove all the retina specific code in the future since the scale factor will be reported by the window regardless of platform, no special provisions will be needed for MacOS.
Somewhat addresses #3460
=> NF: Added `getContentScalingFactor` to `Window`

psychopy/app/builder/dialogs/__init__.py, psychopy/experiment/components/_base.py, psychopy/experiment/components/grating/__init__.py, psychopy/experiment/components/image/__init__.py, psychopy/experiment/components/keyboard/__init__.py, psychopy/experiment/components/polygon/__init__.py, psychopy/experiment/components/slider/__init__.py, psychopy/experiment/components/text/__init__.py, psychopy/experiment/components/textbox/__init__.py
Range of changes:
- ordering: Data tab now comes later (after Component-specific tabs)
- fonts: set default font to be Arial not Open Sans so users don't start
with a warning
- Slider:
- size was default of 0,0 so didn't appear by default
- Ticks, Labels and Granularity are Basic params
- Moved several components into the Basic tab for their type
(e.g. allowedKeys is a basic property of keyboard)
=> RF: changed/fixes to component param defaults

setup.cfg
- Related to / closes #3429, pyglet 1.4.x is used on win and linux, pyglet 1.5.x is used on macos as it is needed for big sur.
- added packaging dependency, does not seem to get included sometimes (some systems?)
- added pyobj dependency for macos - atleast when using anaconda this must be installed or a objc lib version error occurs.
- added python-xlib for linux install, needed by iohub
- added tobii-research package if python <= 3.6
- added ujson package (used by iohub if present)
=> setup.cfg dependency cleanup

psychopy/app/utils.py
simpler to keep them as the exact filenames (prettyname function still exists for use elsewhere if needed)
=> ENH: Unlink prettyname function from demo names

psychopy/experiment/components/ratingScale/__init__.py
Fix these issues:
1. list of "Marker type" parameter is empty.
2. While "Size" parameter of the RatingScale must be a single number, Builder outputs the value as a list.  For example, setting "1.0" to "Size" results in "size=[1.0]" in the complied code.
I'm not sure my fix for issue 2 is the best way.
=> FF: fix for "Marker type" and "Size" of RatingScale component

psychopy/visual/window.py
In commit d347908333 window creates _currentEditableRef=None
but then returns it as if already a weakref resulting in
NoneType not callable error
=> BF: Fixed case where _currentEditableRef=None

docs/source/api/color.rst, psychopy/visual/circle.py, psychopy/visual/line.py, psychopy/visual/pie.py, psychopy/visual/polygon.py, psychopy/visual/rect.py, psychopy/visual/shape.py
@TEParsons Added a file for the `colors` module. Should automatically pickup all the docstrings once they are added. Also fixed the references to the color class in the visual stimuli docs.
=> DOCS: Added stub for colors module documentation. 

psychopy/demos/coder/stimuli/textbox_editable.py, psychopy/visual/textbox2/textbox2.py, psychopy/visual/window.py
BF: Changing textbox.editable at runtime was not supported.
BF: Do not add editable to window editables list if editable.editable == False
RF: textbox2.hasFocus setter now updates window editable focus if necessary
=> BF: Misc. TextBox2 window focus fixes

psychopy/visual/textbox/__init__.py
BF: Textbox started to fail because colors.isValidColor no longer returns True for 'valid' rgb255 or rgb tuples.
=> BF: Fixed exception in textbox stim caused by change to colors.isValidColor behaviour

psychopy/visual/textbox/fontmanager.py, psychopy/visual/textbox2/fontmanager.py, setup.cfg
BF: Both textbox and textbox2 fontmanager.addFontDirectory() was not working.
BF: textbox MonospaceFontAtlas.saveGlyphBitmap() was broken (was using now non existant scipy function)
ADD: Added python-vlc to setup.cfg package dependency list, fixes #3486
=> Fix fontmanager.addFontDirectory and update to setup.cfg

psychopy/app/coder/coder.py
On Windows 10, printing files including non-ASCII characters from the Coder results in corrupted output or unhandled exception:
```
File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\app\coder\coder.py", line 2190, in filePrint
text = open(docName, 'r').read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 29: illegal multibyte sequence
```
Here is a minimal sample file of causing the above exception.
```
#coding: utf-8
font_name = 'ＭＳ 明朝'
```
To avoid this issue, files should be opened by `codecs.open()`.
=> FF: Coder can't print files including non-ASCII characters

psychopy/app/_psychopyApp.py
Have author names in list format to make it easier to edit. Anyone who made over 1000 lines of changes based on "insights" is now there. People who don't have their full names listed are denoted as `name [@github.com]`.
=> RF: Change how authors are added to the about box. Updated list.

psychopy/app/_psychopyApp.py
Setting the sys.excepthook really needs to happen at the end of the
loading of the app (after onInit() ) or it could prevent the log file
reporting any crash tracebacks
I've added 2 logging.flush() calls but these are *probably* nto needed
=> BF: logging of app traceback in last load.log

psychopy/app/builder/dialogs/paramCtrls.py
This means that e.g. color and table params will undergo the same monospace font setting as str params, rather than doing the same "if startswith($)" type thing several times in different places
=> ENH: Link monospace font setting to universal validator

psychopy/visual/textbox2/fontmanager.py
… (removing the possibility that it could search a huge amount of files if the experiment file is somewhere silly)
=> BF: Remove "" from OSX search paths, should mean fontmanager doesn't look in the experiment folder for fonts

psychopy/demos/coder/iohub/delaytest/run.py, psychopy/demos/coder/stimuli/textBoxStim/textbox_glyph_placement.py
ADD: added back TextBox text glyph placement demo 9removed by mistake?)
RF: iohub delay test demo macos fix (drawing matplotlib graph was causing my macbookpro display to go completely black, requiring hard restart, now just print results ;) ).
=> small iohub delay test change and added back TextBox text placement demo

psychopy/visual/shape.py
as Color objects have their own alpha values, if you set them after setting opacity then these override the object's opacity (whereas the object's opacity should override the Color objects'), fixes #3494
=> BF: Set opacity /after/ setting colors for shape stim

psychopy/colors.py, psychopy/tests/test_all_visual/test_color.py, psychopy/tests/test_tools/test_colorspacetools.py, psychopy/tools/colorspacetools.py
Commit renames `Color.srgbTF` to `Color.srgb` and removes the `Rec709` attribute that people would rarely use. Added tests for most of the `colorspacetools` functions to increase coverage and to ensure they keep working correctly. Made some superficial formatting changes to neaten the code in the `colors` module.
=> RF/FF/TESTS: Renamed color class attributes and added `colorspacetools` test 
