- psychopy/demos/coder/experiment control/TrialHandler.py
Also indicate that dataframe is returned
> include some extraInfo, saveAsWideText

- psychopy/demos/coder/experiment control/experimentHandler.py
I found it easy to get confused about what experimentHandler was saving, this makes it clearer
> slight clarification of what experimentHandler does

- .travis.yml
> install pandas via apt-get -- must be coming from neurodebian

- .travis.yml
- psychopy/event.py
adjust travis.yml file (-qq)
enable mouse.setPos
> mouse.setPos() works on pyglet

- psychopy/demos/coder/iohub/serial/pstbox.py
- psychopy/demos/coder/stimuli/MovieStim2TimingTest.py
- psychopy/iohub/devices/serial/default_pstbox.yaml
- psychopy/iohub/devices/serial/supported_config_settings.yaml
- psychopy/iohub/devices/serial/supported_config_settings_pstbox.yaml
Care of @hoechenberger:
* PST response box now automatically starts processing device events. 
* pstbox.py demo script cleaned up.
> iohub pstbox device cleanup

- psychopy/contrib/psi.py
- psychopy/data.py
Modified "data.py" to include new PsiHandler class
Added "psi.py" to handle back end operations of PsiHandler
Modeled after the QuestHandler methods
> NF: PSI adaptive psychophysical method

- psychopy/app/builder/builder.py
As noticed by @kohlman in #799, ISI components disappear when they have variable start or duration (from code)
This makes it hard to see, edit, or delete them, which is not ideal. (You have to set an estimated duration.)
Fix: Always display something, add '???' to display name to flag as non-literal timing. Maybe there's a better
way to signal that (different fill color?)
Another possible approach: Auto-provide estimated start and duration if no explicit values, and draw accordingly.
> ENH: ensure static (ISI) component is always drawn; closes #799

- iohub_docs/iohub/api_and_manual/device_details/eyetracker_interface/Tobii_Implementation_Notes.rst
- all the limitations and to-do's listed are done, so removed them.
> Updated Tobii eye tracker iohub interface doc page

- psychopy/app/builder/experiment.py
- fixes my case
- not sure about all other possible cases
- more discussion might be good before pulling this is? seems ok to me even if other work is also needed
> BF: move routineTimer.reset() to end of routine; fixes #822

- psychopy/app/builder/components/mouse.py
issue reported on users list, this fixed it
> BF: mouse component could crash when saving data if no responses

- psychopy/tests/test_data/test_ExperimentHandler.py
- psychopy/tools/filetools.py
This closes #846.
The issue was reported on the user mailing list: https://groups.google.com/d/msg/psychopy-users/IqEpwGF--BI/nD2oDf0A_HsJ
It was also discussed on the dev list: https://groups.google.com/d/msg/psychopy-dev/YB3pQlbdr5o/_Xiw0UHqOSYJ
> BF: Fix file saving with unicode conditions

- docs/source/api/preferences.rst
- docs/source/api/sound.rst
- docs/source/general/prefs.rst
- new file:   docs/source/api/preferences.rst: page for preferences module
- modified:   docs/source/api/sound.rst: added link to preferences docu
- modified:   docs/source/general/prefs.rst: made labels conform to labels in preferences file
> DOC: Added API page for preferences module - plus minor updates

- psychopy/gamma.py
use tuple-ized Mac version info to createGammaRamp
> bf-gamma-mac-ver

- .travis.yml
- psychopy/info.py
- psychopy/tests/test_all_visual/test_gamma.py
- psychopy/tests/test_all_visual/test_projections_interactive.py
- psychopy/tests/test_data/test_TrialHandler.py
- psychopy/tests/test_hardware/test_CRS_BitsSharp.py
- psychopy/tests/test_hardware/test_CRS_bitsShaders.py
- less logging
- better set-up (update pip, use sudo -H, pyglet 1.2.2)
> TESTS: travis tweaks

- docs/source/coder/codeLogging.rst
argument "mode" is now called "filemode"
> DOCS: Corrected documentation in codeLogging.rst

- psychopy/sound.py
otherwise can have very cryptic tracebacks, catch everything
> BF: catch bad file names etc in soundPyo

- psychopy/app/builder/experiment.py
- psychopy/locale_setup.py
- issue discovered by @flipphillips, might be conda-only?
- setting locale avoids python crashing
- doing PR just for discussion: worth pulling now just in case, or wait to see how wide-spread an issue it is?
- adds ~80ms (for the import), seems worth avoiding if not really needed
> ENH: proactive fix for Mac 10.10.3 LC_ALL issue

- psychopy/data.py
and then do pandas.read_csv
Should fix an issue that was posted to the users list April ~15, 2015
> BF: open conditions.csv with universal newlines

- psychopy/iohub/util/fix_encoding.py
Should mitigate resetting of possible customizations of stdout, stderr etc
Closes #907
> BF: hack-for-a-hack avoid reload(sys) to call setdefaultencoding

- psychopy/platform_specific/win32.py
> BF: Fix AttributeError on Win32 rush() setup fail

- psychopy/visual/__init__.py
Shows of second order gratings
> 	ENH: Demo script for EnvelopeGrating stim 

- psychopy/hardware/crs/shaders.py
- psychopy/tests/test_misc/test_event.py
also reinstated a test for the mouse.pressedIn() function
> BF: mono++ shader for CRS Bits needs blue=0.0

- psychopy/demos/coder/experiment control/experimentHandler.py
- psychopy/info.py
To address issue 904 https://github.com/psychopy/psychopy/issues/904
> runTimeInfo wasn't recording gammaGrid, linearizeMethod

- psychopy/visual/polygon.py
setRadius() sets vertices after calc, setEdges() should too
> BF: polygon.setEdges() should set vertices; closes #946

- psychopy/demos/builder/word_naming/conditions.csv
- psychopy/demos/builder/word_naming/word_naming.psyexp
- psychopy/voicekey/__init__.py
- psychopy/voicekey/demo_vks.py
- psychopy/voicekey/labjack_vks.py
- psychopy/voicekey/parallel_vks.py
- psychopy/voicekey/signal.py
- psychopy/voicekey/vk_tools.py
- can work well but not thoroughly tested
- basic word naming demo included (Builder)
- much more documentation is needed
> NF: voicekey, with vocal onset & offset RT

- psychopy/info.py
- python process memory is useful for tracing memory leaks, could be done in tests for example
- depends on psutil package, which now comes with PsychoPy anyway
> NF: memory info tools for system and current python process

- psychopy/app/builder/components/_base.py
- psychopy/demos/builder/word_naming/word_naming.psyexp
- psychopy/demos/coder/experiment control/runtimeInfo.py
- psychopy/info.py
- psychopy/tests/test_misc/test_microphone.py
- psychopy/visual/ratingscale.py
an explicitly requested duration for a tone was being ignored, leading to default duration 0.5s
being used, which made 9 or 10 audible clicks during a 5s tone.
(see users list query 9/29/2015)
> several small fixes and doc

- docs/source/api/visual/ratingscale.rst
- psychopy/sound.py
Torsten Huenger spotted this and provided a fix
> BF: sound pygame _setSndFromFile

- psychopy/tests/test_misc/memory_usage.py
- many tests fail at present; not suitable for travis-ci, use command line
- tries to cover all classes used during experiments (Window, visual stim, sounds, mouse), might have missed a couple
- only creates instances of each class, not use them in any way. (Usage could possible result in mem leaks not detected here.)
- try to do twice: with minimal parameters, and with more resource-intensive params
> TESTS: memory leak tests

- psychopy/data.py
- psychopy/tests/test_data/test_stairs.py
Jon's error. Shouldn't have pulled this in just yet - tests are not yet working
> Revert "[WIP] ENH: Improve staircase test coverage, fix QUEST"

- psychopy/data.py
`StairHandler._checkArguments()`  used to emit `logging.error`s in case  invalid or insufficient arguments were encountered. However, in these cases we cannot continue, so it's better to raise an exception.
> RF: `StairHandler._checkArguments()` raises if arguments are invalid

- psychopy/tools/wizard.py
- psychopy/visual/__init__.py
implicit was not working, so I followed the same style as the others
> FF: use absolute import for visual.TextBox

- psychopy/__init__.py
- psychopy/app/builder/experiment.py
- psychopy/preferences/preferences.py
The XML fix restores the ability to load .psyexp files having advancedParams (including BART and mental rotation). This might be a FF instead of BF.
> 3 small fixes

- psychopy/visual/movie3.py
> BF: Further fix to the loading movies with no audio in MovieStim3

- psychopy/demos/coder/experiment control/TrialHandler.py
`importTrialTypes()` is deprecated and `importConditions()` should be used.
Thanks!
> ENH: Update source comment in TrialHandler demo

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/localizedStrings.py
- psychopy/app/builder/validators.py
class CodeSnippetValidator checks python syntax, checks for self-reference
> RF: check syntax in code snippets; closes #1132

- createInitFile.py
- psychopy/CHANGELOG.txt
- psychopy/__init__.py
- psychopy/app/_psychopyApp.py
- psychopy/app/builder/components/keyboard.py
- psychopy/app/builder/components/settings.py
- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/experiment.py
- psychopy/tests/test_app/test_builder/componsTemplate.txt
- psychopy/tests/test_app/test_builder/test_components.py
- psychopy/tools/versionchooser.py
also add helper functions in versionchooser:
- ensureMinimal
- allow useVersion(major.minor), (major), or ('latest')
> NF: new Builder feature - useVersion exp setting; closes #1130

- psychopy/CHANGELOG.txt
to credit Frank Papenmeier for glPopAttrib fix (as well as Bryan Cort)
> DOCS: updated changelog

- psychopy/tests/test_all_visual/test_all_stimuli.py
- requirements.txt
@jeremygray I *think* this started breaking without any changes
to the code (so is probably a change in the travis gfx card) but let me
know if there's any change at your end
Also tried an alternative to installing wxpython_phoenix in pip requirements
> TESTS: relaxed test for ratingscale (was failing on travis)

- psychopy/app/projects.py
- psychopy/app/wxIDs.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
- psychopy/preferences/generateSpec.py
Added substantial development allowing sync of folders with Open Science Framework
> ENH: Feature projects

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/validators.py
Loop dialog needs to provide params and paramCtrls (combined across loop options) for validator to check
> FF: loop dialog not closing. Fixes #1170

- docs/source/api/gui.rst
- docs/source/api/hardware/labjack.rst
- psychopy/iohub/devices/__init__.py
also fixed some docs issues in hardware imports for linux
> BF: iohub devices not loading on ubuntu with older psutils

- docs/source/coder/tutorial1.rst
- docs/source/coder/tutorial2.rst
new server doesn't allow access to python files on the server so
point to the github copy instead
> DOCS: fix permissions errors downloading py files form psychopy.org

- psychopy/app/builder/components/_base.py
- psychopy/app/builder/components/keyboard/__init__.py
- psychopy/app/builder/experiment.py
> FF: Fix syntax errors and missing routine end in JavaScript output

- psychopy/tools/wizard.py
`BenchmarkWizard.__init__()` calls superclass's (i.e. ConfigWizard's) `__init__()`, which opens Configuration Wizard Window.
> FF: Configuration Wizard is opened before Benchmark Wizard is opened. (issue #1203)

- docs/source/about/credits.rst
- psychopy/CHANGELOG.txt
> DOC: Fix typos in changelog for 1.84 and credits

- psychojs/js/psychojs/core.js
- psychojs/js/psychojs/data.js
- psychojs/js/psychojs/events.js
- psychojs/js/psychojs/gui.js
- psychojs/js/psychojs/io.js
- psychojs/js/psychojs/logging.js
- psychojs/js/psychojs/main.js
- psychojs/js/psychojs/scheduler.js
- psychojs/js/psychojs/util.js
- psychojs/js/psychojs/visual.js
- psychojs/server.php
> various new features, bug fixes, and more documentation

- psychopy/app/builder/components/keyboard/__init__.py
> fix indentation for no response scoring

- .mailmap
after this git shortlog is better:
$> git shortlog -sn | head
3131	Jonathan Peirce
1380	Jeremy R Gray
534	Sol Simpson
175	Jonas Lindeløv
149	Hiroyuki Sogo
117	Philipp Wiesemann
93	Yaroslav Halchenko
76	Richard Höchenberger
31	Erik Kastman
25	isolver
...
> Rudimentary mailmap to bring all jons and jeremys together

- psychopy/app/coder/coder.py
wx was getting a conflicting ID in certain values from wx.NewId() so
need to move away from that. wx.NewId() has been deprecated in 3.0.3
for this very reason :-/
> BF: app crashing loading some of the demos

- docs/source/demos/face.py
- docs/source/demos/plaid.py
- psychopy/visual/window.py
Use of RGB-parameter has been DEPRECATED since v1.60.05
> Doc: substituted rgb by color

- psychopy/iohub/client/__init__.py
> BF: Error in tracker.runSetupProcedure()

- docs/source/coder/codeLogging.rst
- psychopy/logging.py
> Minor typos

- psychopy/app/builder/components/settings/__init__.py
- psychopy/app/builder/experiment.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
- psychopy/preferences/generateSpec.py
The resources are populated by any valid file paths in Component params and loops (conditions files) but valid paths *within* conditions files are not currently detected
> WIP: PsychoJS exports by Builder now including resources folders

- psychojs/js/psychojs/scheduler.js
- psychojs/js/psychojs/visual.js
- psychopy/app/builder/experiment.py
Nested loop outputs from builder now working
> fixes for PsychoJS

- psychopy/constants.py
- psychopy/sound/backend_sounddevice.py
sounddevice is another portaudio option but pure python, supporting py3 and better maintained than pysoundcard.
This implementation sets up an appropriate stream as soon as the sound is created but plays zeros until the sound is played (whereas in the other backends so far we've been creating the stream at the moment we play() ). This seems to have better timing than the existing solutions (although some of them could use the same approach if we reworked them).
Not yet implemented:
- sound from array (so movie3 won't work using this yet)
- loops etc
There are also likely to be some bugs, but the future is bright!
> ENH: New sound option sounddevice

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
copy with right-click on component and then paste using exp menu
or using Ctrl-Alt-V
> ENH: added option to copy/paste a component with same param settings

- psychopy/data.py
Just some tiny doc and a single coding style modification.
> DOC/RF: Small QUEST improvements

- psychojs/js/psychojs/visual.js
This commit fixes 2 issues:
- units is no longer ignored in BaseVisualStim constructor
- norm units fixed
> Psychojs fixes for usage of units

- psychojs/js/psychojs/visual.js
Just added the color attribute to Window.
> Window color attribute

- psychojs/js/psychojs/main.js
Using http is a problem for institutions that require a full https stack
> BF: call ioinfo.io using https not http

- psychopy/event.py
- psychopy/tests/test_misc/test_event.py
Restructure `event.clearEvents()` a little bit to make the code more intelligible, and add more tests.
> RF, TEST: event.clearEvents()

- psychopy/logging.py
First step to better and more explicit handling of deprecation cycles. See also #1397.
> NF: Add DEPRECATION log level

- psychopy/app/builder/components/keyboard/__init__.py
Fix the JS code written to index.html for end of a routine so
that it checks to see if it really was a non-response before
evaluating if the non-response was the correct answer.
This fixes a problem where normal correct responses
are not written to the data file
> Fix JS code for checking of correct non-response

- psychopy/app/builder/components/__init__.py
As noted in https://discourse.psychopy.org/t/some-notes-from-making-an-online-study/2496
> BF: html sounds/images that were 'constant' did not have str quotes

- psychopy/web.py
I don't know if this will be useful but still I did it ;)
Signed-off-by: Michał Oszczak <mimioszczak@gmail.com>
> BF/ENH:Switched httplib to httplib2 since httplib is outdated.

- createInitFile.py
- psychopy/__init__.py
- setup.py
Fixes bugs that broke `pip install` on Python 3.
> FIX: pip install on python3

- psychopy/visual/noise.py
Modification to recently added noise stimulus class to remove ambigous 'coloured' noise term and integrate the desired fucntionality as a skew to the spectrum used as the starting point for filtered noise. Setting NoiseFilerOrder to 0 will turn off the filter leaving just the skew (just another kind of filtering after all) setting noiseFractalPower to 0 will produce an flat inital spectrum. 'White' noise is retained as a fast route to unfiltered spectra.
> ENH: Integrates 'coloured' noise into filtered noise

- psychopy/iohub/devices/mcu/iosync/arduino_sketch/ioSyncArduinoMega.ino
added sketch for running ioSync on Arduino Mega
enables Arduino Mega to work with ioSync
for those who do not have a Teensy3
tested ioSync <---> Arduino, works
but beware as ioHub <--> mcu does not work correctly (MCU.__init__ never starts up), but that is apart from this commit
> [NF] added sketch for running ioSync on Arduino Mega

- psychopy/iohub/devices/mouse/linux2.py
Discussed on the old mailing list (https://groups.google.com/forum/#!topic/psychopy-dev/LUna_gm5YG4) but not committed.
Re-encountered recently at https://discourse.psychopy.org/t/issue-with-iohub-on-linux/2741
> BF: Use xlib in iohub on Linux.

- psychopy/app/builder/components/parallelOut/__init__.py
Related to issue #1458.
I think this is the right place to fix this.
Feedback will be appreciated.
> [BF] Added status to u3 in builder

- psychopy/app/coder/coder.py
I made a quick workaround for the issue I raised in #1472
> fixed issue with coder view minimized in Windows

- psychopy/demos/coder/input/latencyFromTone.py
- psychopy/microphone.py
- psychopy/sound/__init__.py
Fixes the error:
AttributeError: 'NoneType' object has no attribute 'setSamplingRate'
> BF: refactoring of sound libs had broken the microphone

- psychopy/core.py
- psychopy/info.py
- psychopy/tests/test_misc/test_core.py
- psychopy/tests/test_misc/test_event.py
- psychopy/visual/image.py
currently 53 fails, 434 passes on my mac
> RF: fixing tests (mostly string issues) for PY3

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/dialogs/dlgsConditions.py
- psychopy/app/coder/coder.py
- psychopy/gui/wxgui.py
- psychopy/iohub/util/dialogs.py
- psychopy/monitors/MonitorCenter.py
- psychopy/visual/window.py
event binding and a couple of changed locations for classes (About dlg and wx.SAVE)
> RF: further fixes for wx4.0

- psychopy/app/builder/components/polygon/__init__.py
- psychopy/app/builder/experiment.py
The code compiled for "cross" wasn't correct
> Fixes to new Polygon shapes in Builder

- psychopy/tests/test_all_visual/test_all_stimuli.py
- psychopy/tests/test_all_visual/test_contains_overlaps.py
- psychopy/visual/helpers.py
- psychopy/visual/line.py
> NF: Add `overlaps()` method for Line stimulus

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/app/builder/validators.py
it doesn't need to be rigidly attached to the frame (and easier to
make screengrabs if it isn't!)
> ENH: give the loop dialog parent=None

- psychopy/demos/coder/experiment control/TrialHandler.py
> DOC: Clean up TrialHandler demo

- psychopy/monitors/calibTools.py
- psychopy/tests/test_app/conftest.py
- psychopy/tests/test_app/test_builder/componsTemplate.txt
- psychopy/tests/test_app/test_builder/test_Experiment.py
- psychopy/tests/test_app/test_builder/test_components.py
- psychopy/tests/test_data/test_StairHandlers.py
- psychopy/tests/test_monitors/test_monitors.py
Some of my last PRs managed to break Travis testing – and we didn't realize, because Travis was not working properly at the time of merging. Other tests apparently had been broken all along… This PR fixes the problems.
> TESTS: Fix tests

- .mailmap
- AUTHORS.md
- gen_authors.py
Got in touch with "theodleif" and included their real name. Also added email addresses of those that did not specify their name (were previously dropped as "unknown")
> DOC: Some more updates to .mailmap

- .mailmap
- AUTHORS.md
Finally! I've tracked down all real names belonging to the "anonymous" email addresses in the git log.
> DOC: Updating authors

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/components/__init__.py
- psychopy/app/builder/dialogs/dlgsConditions.py
- psychopy/app/builder/flow.py
- psychopy/app/builder/validators.py
- psychopy/app/coder/introspect.py
- psychopy/app/connections.py
- psychopy/app/dialogs.py
- psychopy/app/localization/__init__.py
- psychopy/app/preferencesDlg.py
- psychopy/gui/wxgui.py
- psychopy/iohub/util/dialogs.py
- psychopy/tests/test_app/test_builder/genComponsTemplate.py
- psychopy/tests/test_app/test_builder/test_components.py
- psychopy/tools/wizard.py
I have refactored [my previous PR](https://github.com/psychopy/psychopy/pull/1580) and dropped the `StrictVersion` version checks in favour of `pkg_resources.parse_version` comparisons.
> BF/RF: #1578 wx version checks

- psychopy/hardware/bbtk/__init__.py
inWaiting -> in_waiting
sendBreak -> send_break
This should really be applied elsewhere too
> ENH: BBTK support for future pyserial commands

- psychopy/hardware/serialdevice.py
- psychopy/visual/windowwarp.py
- setupApp.py
As per discussion for [static code analysis](https://discourse.psychopy.org/t/static-code-analysis/3369) this is the first obvious thing that it came up with.
> BF: raise should have an Exception and not str / NotImplemented

- psychopy/data/staircase.py
- psychopy/tests/test_data/test_StairHandlers.py
- psychopy/tools/attributetools.py
Another static code analysis PR.
> BF: Redundant assignment

- psychopy/app/builder/builder.py
- psychopy/iohub/datastore/util.py
This PR fixes some alerts reported by lgtm.com: https://lgtm.com/projects/g/psychopy/psychopy/alerts/
It'd be good if someone could verify whether my change to builder.py was indeed the right thing to do.
> Fix a few lgtm.com alerts

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/preferencesDlg.py
- psychopy/app/stdOutRich.py
- psychopy/sound/backend_pyo.py
The change in stdOutRich was a strange one but it seems wx4 didn't like
the \t character when writing strings :-/
> FF: fixes for Python3 string compatibility

- psychopy/iohub/datastore/__init__.py
- psychopy/iohub/datastore/util.py
Using [lgtm.com]( https://lgtm.com/projects/g/psychopy/psychopy/alerts/?mode=tree&severity=error&rule=4860085)
> BF: Syntax errors in datastore

- psychopy/app/builder/builder.py
Component Dialogs would not open at all
> FF: fixed problem with component dialogs in new wx4-compatible builder

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- psychopy/app/builder/components/static/__init__.py
- psychopy/app/builder/experiment.py
- psychopy/app/coder/coder.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
- requirements_travis.txt
- setup.py
This includes:
- fix to Coder comment-toggle from David
- fix to Static Components from Jon
- change to setup.py due to failing Travis suite
> Various fixes to Builder and Coder

- psychopy/experiment/components/ratingScale/__init__.py
- psychopy/visual/ratingscale.py
> BF: Fixes markerExpansion duplication & 'glow' marker PatchStim bug in ratingScale

- psychopy/app/dialogs.py
- psychopy/hardware/bbtk/__init__.py
Other fixes include removing conversion of thresh vals to string.
> BF: Fixes comparison of ASCII and character.

- psychopy/visual/helpers.py
- psychopy/visual/window.py
Adds hex colorspace to window, and corrects the RGB input in helpers.py to give accurate hex2rgb255 color. Fixes #1695
> BF: Enables hex win color. Fixes #1695

- psychopy/app/builder/dialogs/dlgsConditions.py
- psychopy/app/coder/coder.py
- psychopy/app/coder/introspect.py
- psychopy/compatibility.py
- psychopy/contrib/http/benchmark_report.py
- psychopy/data/base.py
- psychopy/data/experiment.py
- psychopy/data/staircase.py
- psychopy/data/utils.py
- psychopy/experiment/_experiment.py
- psychopy/experiment/exports.py
- psychopy/experiment/loops.py
- psychopy/experiment/params.py
- psychopy/hardware/crs/bits.py
- psychopy/microphone.py
- psychopy/monitors/calibTools.py
- psychopy/tests/runPytest.py
- psychopy/tools/filetools.py
- psychopy/visual/vlc.py
- psychopy/web.py
> Remove install_aliases() to fix automatic import of "test.py" issue

- psychopy/experiment/_experiment.py
- psychopy/experiment/compileScript.py
...leading to an IndentationError when launching script from psychopy<1.90
> Fix to old mouse components and also added compileScript script to psychopy/experiment

- psychopy/visual/backends/glfwbackend.py
Added some GLFW backend specific docs, making additional features discoverable to help with testing.
> DOC: Better GLFW backend documentation.

- CONTRIBUTING.md
Some small fixes to contributing.md
> DOC: fix typos in CONTRIBUTING.md

- psychopy/hardware/crs/bits.py
- psychopy/tests/test_all_visual/test_gamma.py
- psychopy/visual/backends/gamma.py
- psychopy/visual/backends/pygamebackend.py
- psychopy/visual/backends/pygletbackend.py
- psychopy/visual/window.py
This is a version of #1714, updated with feedback.
Not yet tested on Mac or Windows.
> RFC: move gamma responsibility to each backend (updated)

- psychopy/visual/backends/glfwbackend.py
Added code to set the window position and swap interval. Added some documentation for how to use swapInterval correctly for good timing across multiple monitors.
> EN: Misc GLFW window features and docs

- psychopy/visual/ratingscale.py
Added the code fixing the tesselation (adding verts was causing incorrect rendering)
Cherry-picked @dvbridges fix to the RatingScale reset function
> Couple of quick fixes

- psychopy/app/_psychopyApp.py
- psychopy/app/coder/coder.py
- psychopy/experiment/compileScript.py
removed the __pycache__ folder from coder>demos
> docs and demos

- psychopy/app/coder/coder.py
It was looking for the _ at the start of the absolute path, not the
folder name
> FF: the recent change to catch __pycache__ from demos didn't catch it

- psychopy/visual/backends/glfwbackend.py
Removed loading the icon for use with GLFW windows, doesn't seem to work on some installations. Will re-add it when I find a good solution for loading package files.
> BF: Fixed icon loading causing some installs to crash.

- setup.py
Defeats the purpose of that operation
> BF: do not generate psychojs zip upon "clean"

- .travis.yml
- docs/source/installation.rst
Currently getting SSL errors with travis under the system python
installation.
Also cleared up formatting error in docs for anaconda installation
> TESTS & DOCS: try adding pip install requests[security] early

- psychopy/localization/__init__.py
> BF: Fixes layout problem with RTL languages by resetting to default.

- psychopy/tests/test_app/test_builder/componsTemplate.txt
- psychopy/tests/test_app/test_builder/genComponsTemplate.py
- psychopy/tests/test_app/test_builder/test_components.py
In Python 3, the encode function returns type bytes and the write function requires str not bytes. In Python 2 the encode function returns type str, thus no error is raised. Removing the encode function resolves issue. Fixes #1844
> BF: Fixes Py3 compatibility problem with genComponsTemplate.

- psychopy/tools/colorspacetools.py
Added function 'cielch2rgb' which converts CIE L*C*h* to RGB.
> NF: Added CIE L*C*h* converter to colorspacetools.

- psychopy/CHANGELOG.txt
> DOCS: [CI SKIP]

- docs/source/api/visual.rst
- docs/source/index.rst
- psychopy/experiment/components/slider/__init__.py
- psychopy/tests/test_all_visual/test_all_stimuli.py
- psychopy/visual/slider.py
Not sure yet what the change could have been but suddenly RMS=7.5
> fixes and tests

- psychopy/visual/movie3.py
> BF: MovieStim3 didn't stop playing the audio

- psychopy/hardware/crs/bits.py
- psychopy/projects/pavlovia.py
- psychopy/visual/backends/glfwbackend.py
- psychopy/visual/backends/pygamebackend.py
The former is not actually an Exception and would generate its own error!
> Minor: replaced NotImplemented with NotImplementedError

- docs/source/api/visual/rift.rst
Added directives to document most of the attributes of the Rift class.
> DOCS: Initial commit of Oculus Rift docs.

- psychopy/visual/movie3.py
> BF: fix segmentation fault caused by self._unload()

- docs/source/api/tools/gltools.rst
- psychopy/tools/gltools.py
Added a documentation page for gltools. Refactored drawVertexbuffers to use explicit arguments for additional buffers.
> DOCS/RF: glTools

- psychopy/tools/gltools.py
Added Vertex Array Objects (VAO) related functions and datatypes to gltools. This is in response to poor-performance when using gltools to render 3D models in the Oculus headset. VAOs resulted in a very large performance boost (larger than I expected).
> NF: Added VAO support to gltools

- psychopy/tools/stereotools.py
Initial commit of **stereotools**, which are a collection of functions for working with stereoscopic displays.
> NF: Initial commit of STEREOTOOLS

- psychopy/tools/coordinatetools.py
The function converts from Cartesian to polar coordinates, the function name was wrong in the docstring.
> DOC: Fixed error in docstring (wrong function name).

- psychopy/tests/test_psychojs/test_compile.py
The new tests check whether the html path is returned from the _getHtmlPath method. Also tests export prefs in Experiment Settings.
>  TEST: Adds tests to test_psychojs

- psychopy/tools/monitorunittools.py
Just a small error in the docstring (function description).
> DOC: Fixed error in docstring (wrong function description).

- psychopy/visual/backends/glfwbackend.py
Some misc fixes to the GLFW backend regarding window sizing and positioning, it wasn't working correctly in some cases. Changed variable naming conventions to match the rest of PsychoPy.
> BF/RF: GLFW backend window position and size fixes.

- psychopy/visual/backends/glfwbackend.py
Fixes an issue where the windows 'jumps' across the screen when created. Some code clean-ups.
> RF: Minor GLFW backend tweaks

- psychopy/experiment/components/settings/JS_setupExp.tmpl
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/flow.py
Note, studyID is not a parameter and at this point is always undefined. One option is to remove studyID and allow user to complete this in experiment settings.
> ENH: Adds redirectURL for psychoJS.

- psychopy/experiment/components/mouse/__init__.py
Fixes #2019
If accepted, the JS script will be fixed to match the python script
> BF: Proposed fix to allow continuous mouse tracking for every frame

- .travis.yml
- psychopy/app/builder/validators.py
- psychopy/tests/test_app/test_builder/componsTemplate.txt
- psychopy/tests/test_hardware/test_CRS_bitsShaders.py
- psychopy/visual/movie3.py
- psychopy/visual/window.py
Various steps:
- moving to trusty
- fixed a rendering pipeline buglet with an unmatched glPopAttrib
- fixed a bug with readBuffers(buffer='back') when using an FBO
> Fixes to video and tests

- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/app/coder/codeEditorBase.py
- psychopy/app/coder/coder.py
The code component needed better commenting and smart indenting for JS code.
The refactor brings common attributes and methods for Coder and code component and puts them into a new base class.
The toggleCommentLines and smartIdentThisLine methods support code type from the code component, but will always be set to python for Coder.
> ENH/RF: Refactor of code component and coder with base class

- psychopy/tests/test_all_visual/test_form.py
- psychopy/visual/form.py
- psychopy/visual/text.py
Also includes warning removal for deprecated pyglet function, as this will be useful for further tests made with this branch. Warning removal should be identical to Master. Also amendments to tests based on Form fix.
>  BF: Some layout fixes for Form where vert and horiz labels would overlap

- docs/source/installation.rst
Docs currently say Python 3 is not supported. Have reversed to say that 3.6 is preferred, while 2.7 remains supported. Also made minor typographical changes.
> DOC: Update to indicate 3.6 is supported.

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- conda/environment-3.7.yml
- travis/10_install_system_dependencies.sh
- travis/20_install_system_python.sh
- Install flac from `conda-forge`
- ffmpeg is installed via `conda`, no need to use `apt`
> TESTS: Small improvements

- psychopy/experiment/components/movie/__init__.py
Awaiting response from AP re: errors on Chrome and FireFox
> NF: Adds JS movieStim compiler code.

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- conda/environment-3.7.yml
- requirements_dev.txt
> TESTS: Pin pytest version to <4.1

- psychopy/experiment/components/keyboard/__init__.py
- psychopy/experiment/components/slider/__init__.py
- psychopy/experiment/components/text/__init__.py
Adds minor formatting change to text component.
> BF: Updates to JS Slider code. JS Slider now runs online.

- psychopy/iohub/devices/keyboard/win32.py
- psychopy/iohub/server.py
- setup.cfg
> PKG: Add `pyWinhook` to package requirements, add iohub support

- docs/source/developers/menuitem.rst
- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/builder/flow.py
- psychopy/app/coder/coder.py
- psychopy/app/pavlovia_ui/toolbar.py
- psychopy/contrib/psi.py
- psychopy/monitors/MonitorCenter.py
- psychopy/tests/test_misc/test_core.py
- psychopy/visual/movie2.py
Will rebase once #2199 has been merged.
> RF: Remove some deprecation warnings

- psychopy/experiment/components/keyboard/__init__.py
Go/no-go tasks weren't working as a result
> BF: JS outputs from Builder not detecting non-response correctly

- psychopy/app/coder/coder.py
> BF: Fixes encoding error when compiling script with PsychoPy Py 3

- psychopy/app/pavlovia_ui/project.py
Create it from the start (so we don't have to resize) and populate with
"Ready to sync." Then set status to "Synchronizing..." when the sync
actually starts.
> BF: pavlovia project details better sync panel handling

- psychopy/experiment/components/settings/__init__.py
> BF: Fixes file and exp name mismatch causing online studies to fail

- psychopy/data/utils.py
This fix allows .xlsm files to be loaded as conditions files in PsychoPy.
Older versions of openpyxl allowed cell contents to be accessed using the
coordinates of a cell e.g., 'A1`, however from 2.0, cell contents are
accessed using row, col coordinates with a starting index of 1. This fix
also checks for openpyxl versions < 2.0, to determine how to read cells.
Fixes #2309
> BF: Allow .xlsm files to be read using importConditions()

- psychopy/iohub/devices/daq/hw/mc/__init__.py
- psychopy/iohub/removed/util/variableProvider.py
- psychopy/iohub/server.py
> BF: xrange not available in Python 3

- psychopy/demos/coder/hardware/labjack_u3.py
> BF: Fixes import error on labjack demo

- psychopy/app/builder/builder.py
- psychopy/app/coder/coder.py
> RF: Remove Application Preferences toolbar button, move Experiment Settings button

- psychopy/hardware/crs/colorcal.py
- psychopy/monitors/MonitorCenter.py
Fixes multiple problems with MonitorCenter.py calling obsolete functions and colorcal.py not converting str to byte and vice versa.
> BF: MonitorCenter and ColorCal

- psychopy/experiment/components/static/__init__.py
- psychopy/tests/data/test_static_component_script.psyexp
- psychopy/tests/test_scripts/test_static_component_compile.py
> BF: Writes custom code for StaticComponent

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- conda/environment-3.7.yml
- setup.cfg
> BF: Recent update in FreeType 2.10.0 breaks text_box test

- psychopy/hardware/keyboard.py
- psychopy/iohub/devices/pyXHook.py
keyboard buffers were being cleared on each device index.
iohub keyboard P3 code issues on Linux
> BF: keyboard.Keyboard buffer iohub linux P3 keyboard

- docs/source/coder/codeStimuli.rst
Let me know if this is OK, and I can look into a few more of the tutorials.
> Used attributeSetter, PEP8'ed some code, and removed unnecessary clock

- psychopy/experiment/_experiment.py
- psychopy/experiment/components/settings/JS_htmlHeader.tmpl
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/flow.py
- psychopy/experiment/loops.py
- psychopy/experiment/routine.py
- psychopy/tests/data/correctScript/js/correctCodeComponent.js
- psychopy/tests/data/correctScript/js/correctImageComponent.js
- psychopy/tests/data/correctScript/js/correctKeyboardComponent.js
- psychopy/tests/data/correctScript/js/correctMouseComponent.js
- psychopy/tests/data/correctScript/js/correctMovieComponent.js
- psychopy/tests/data/correctScript/js/correctPolygonComponent.js
- psychopy/tests/data/correctScript/js/correctSliderComponent.js
- psychopy/tests/data/correctScript/js/correctSoundComponent.js
- psychopy/tests/data/correctScript/js/correctTextComponent.js
Version number should only be written if Use version is not empty, or
latest.
>  FF: Add absolute paths to HTML/JS and change how version number used 

- psychopy/sound/backend_sounddevice.py
If no rate is given we should check whether a stream already exists
> Better default samplerate for synthesized sounds on SoundDevice

- psychopy/app/connections/sendusage.py
- psychopy/app/connections/updates.py
- psychopy/app/pavlovia_ui/toolbar.py
Also, swithc to using subdomains for run.pavlovia.org
> BF: tweaks to some URLs (e.g. usage should be http for now)

- psychopy/demos/coder/iohub/iodatastore/event2txt.py
- psychopy/iohub/datastore/__init__.py
- psychopy/iohub/datastore/util.py
Fixed ioHubDelayTest/run.py demo and some P3 issues in iohub datastore _reading_
>  BF: iohub datastore file reading utilities / demo

- psychopy/experiment/components/movie/__init__.py
JS MovieStim will not initialise without a video, and so creating a movie
object with a variable name replaced with an undefined type, when variables
are used, will not work. This fix follows the Python code and creates the
movie object in experimentInit if constant is used, else creates the
movie object at beginning of each routine if vars are used.
> BF: Create JS videostim objects on each routine for looping variables

- docs/source/api/tools/mathtools.rst
- psychopy/tests/test_tools/test_mathtools.py
- psychopy/tools/mathtools.py
Here are some more mathtools functions. I squashed a bunch of commits and added some docs.
* Matrix concatenation
* Quaternion inverse and conversion between axis/angle format.
* Pose to matrix conversion.
* Fast matrix application over an array of points.
> NF: Additional 'mathtools' functions

- psychopy/tests/test_all_visual/test_all_stimuli.py
Addes test for stimuli with envelope gratings where the modultor is rasied to a power.
> TESTS: Adds test for envelope grating with power

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- conda/environment-3.7.yml
- setup.cfg
> PKG: Remove superfluous cffi dependency

- conda/environment-2.7.yml
- conda/environment-3.6.yml
- conda/environment-3.7.yml
Revert this once GH-2518 has been resolved.
> TESTS: Pin pyglet to >=1.3, <1.4

- psychopy/demos/coder/stimuli/colorPalette.py
This demo shows users how to create a color palette and select
colors as HSV using sliders.
> NF: Adds a color palette demo to Coder.

- psychopy/experiment/components/keyboard/__init__.py
Keyboard now created at beginning of experiment, and the keys/rt params
are reset on each routine.
> NF: Changes to JS and Py keyboard

- psychopy/clock.py
- psychopy/core.py
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/components/sound/__init__.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
- psychopy/sound/_base.py
- psychopy/sound/backend_ptb.py
- psychopy/sound/backend_pygame.py
- psychopy/sound/backend_pyo.py
- psychopy/sound/backend_pysound.py
- psychopy/sound/backend_sounddevice.py
- psychopy/tests/test_all_visual/test_winFlipTiming.py
- psychopy/tests/test_app/test_builder/test_Experiment.py
- psychopy/visual/window.py
Various fixes, most notably the ability to pre-schedule a sound to play on win.flip()
> Better precision in PTB sound component from Builder

- docs/source/download.rst
> DOCS: added info about ubuntu libs for Psychtoolbox

- psychopy/event.py
- psychopy/visual/backends/pygletbackend.py
Fix allows psychopy to use Pyglet version 1.3 and 1.4. Not sure if I caught all the issues but the demos seem to work fine.
> BF: Pygelt 1.3 and 1.4 compatibility

- psychopy/event.py
- psychopy/visual/backends/pygletbackend.py
- psychopy/visual/text.py
Some dual compatibility fixes for Pygelt 1.3 and 1.4, used suggestions from the bug report. Made changes to events and text stim. On my system, it appears the text scales differently between 1.3 and 1.4, not sure why. Otherwise things appear to be working.
> RF: Pyglet 1.4 support fixes

- docs/source/api/tools/gltools.rst
- psychopy/tests/test_tools/test_mathtools.py
- psychopy/tools/gltools.py
- psychopy/tools/mathtools.py
- psychopy/visual/aperture.py
- psychopy/visual/backends/glfwbackend.py
- psychopy/visual/backends/pygamebackend.py
- psychopy/visual/backends/pygletbackend.py
- psychopy/visual/rift.py
- psychopy/visual/textbox/__init__.py
- psychopy/visual/window.py
Adds the ability to create 3D boxes to `gltools`. Also splits `createPlane` into `createPlane` and `createMeshGrid`. `createMeshGrid` is more specialized for creating distortion meshes for display warping, they shouldn't really be used interchangeably under most uses.
> NF: Viewport rendering, OpenGL state flags, new shapes for GL tools.

- psychopy/app/builder/builder.py
> ENH: Grey out icon when component disabled.

- psychopy/visual/dot.py
Sampling for circular dot fields is not deterministic, as points are sampled randomly until a condition is met. This patch changes the sampling algorithm so that sampling completes in a fixed amount of time. This might require updating the tests related to `DotStim`.
> EN: Faster sampling method for uniform circular dot fields.

- psychopy/experiment/loops.py
I don't have time to add a test, but I think it would be good to have one.
> BF: Builder wouldn't respect selected "switch method" in MultiStairs

- psychopy/experiment/_experiment.py
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/flow.py
- psychopy/experiment/loops.py
- psychopy/experiment/py2js.py
- psychopy/experiment/routine.py
- Adds trial snapshot to routines in loops
- Adds nested function to all routine functions, not just those with loops
- Correctly sets function args in flowScheduler
- Finds and declares vars in nested functions
- Makes spacing between functions consistent between functions with and
without variable declarations.
- Fixes isEntryEmpty typo
> ENH: Updates to JS compiler

- docs/source/api/tools/mathtools.rst
- psychopy/demos/coder/misc/rigidBodyTransform.py
- psychopy/demos/coder/stimuli/stim3d.py
- psychopy/tools/mathtools.py
- psychopy/visual/stim3d.py
- psychopy/visual/window.py
Setting the depth mask is handled automatically now. Also the draw3d attribute wont set any OpenGL flags that are already in the correct setting.
> RF: Removed requirement for manually setting the depth mask.

- docs/source/api/tools/mathtools.rst
- psychopy/tools/mathtools.py
- psychopy/visual/stim3d.py
Added functions which compute intersections of rays with spheres and axis-aligned bounding boxes needed for 3D interactive graphics.
> NF: Added raypicking for spheres and axis-aligned bounding boxes

- psychopy/experiment/components/_base.py
- psychopy/experiment/components/keyboard/__init__.py
- psychopy/experiment/components/settings/JS_htmlHeader.tmpl
- psychopy/experiment/components/settings/JS_setupExp.tmpl
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/components/text/__init__.py
- psychopy/experiment/flow.py
- psychopy/experiment/loops.py
- psychopy/experiment/routine.py
- psychopy/scripts/psyexpCompile.py
- psychopy/tests/test_app/test_builder/test_compileJS.py
Based on APs Stroop code. These fixes are for 3.2.5 onwards. Without 3.2.5 used explicitly,
it will not run in IE, and there are some issues with the GUI layout in
normal browsers.
> BF: Updates to JS Code

- psychopy/experiment/components/keyboard/__init__.py
This fix adapts the keyboard code for the new keyboard component, allowing multiple keypresses to be stored so that first or last keypresses can be accessed from a list.
Waiting on #2686 before amending JS code.
> BF: Updates to Python keyboard code.

- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/flow.py
- psychopy/experiment/loops.py
- psychopy/experiment/routine.py
Also RF by removing redundant JS resource write code.
> BF: Writes End Experiment code component to JS

- psychopy/experiment/loops.py
The code will now compile correctly in this instance, but the code will
not run correctly. This new behaviour matches the PsychoPy trialHandler.
> BF: set nReps as undefined if passed None

- psychopy/visual/stim3d.py
Same a last PR but Travis CI support said to re-attempt.
> FF: Corrected issue with `normalMatrix`

- psychopy/tests/test_tools/test_mathtools.py
- psychopy/tools/mathtools.py
I wrote some improved tests for some functions in `mathtools` to identify issues. Aiming for 100% coverage on those functions given how important they are for 3D rendering and other things.
The tests all validate if various inputs work, but also if the results makes sense under a variety of use cases. I also tried to include testing for how these functions handle edge cases.
> TESTS: Improved tests and coverage for `mathtools`

- .travis.yml
> TESTS: Drop pyglet 1.3 tests on Py3.7, Py3.8

- psychopy/contrib/quest.py
- psychopy/data/staircase.py
Compare https://github.com/Psychtoolbox-3/Psychtoolbox-3/commit/58724686575596da4b6891b5f63889ba9fb90098#diff-4765c75dd74f532c217f00a20df97837
> DOC: QUEST documentation fixes

- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/experiment/components/code/__init__.py
- psychopy/experiment/py2js_transpiler.py
- psychopy/tests/test_app/test_builder/componsTemplate.txt
- psychopy/tests/test_scripts/test_py2js_transpiler.py
- requirements_travis.txt
- setup.cfg
- travis/environment-3.6.yml
- travis/environment-3.7.yml
- travis/environment-3.8.yml
Translates code on change of code type, translate, and when code comp
closed using "OK" button (when translate set to auto).
Also:
- Metapensiero only supports Py 3.5+
- Py2 auto-translate provides user with msg - metapensiero required
- Adds test for transpiler
> ENH: Adds auto Py to JS translation for code components

- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/app/coder/codeEditorBase.py
This fix corrects code specific commenting in code component.
Also fixes new key error raised when code type is "Auto->JS".
> BF: Fixes code commenting in code components

- psychopy/app/builder/builder.py
- psychopy/app/pavlovia_ui/project.py
WIP: Still needs:
- Block SaveAs on Desktop for Coder
- Block create project on Desktop
> BF: Block SaveAs to Desktop folder

- psychopy/visual/backends/pygletbackend.py
replaced self.screen with win.screen; otherwise errors occurred line 130: no attribute to 'screen'
> fixed(?) potential typo: self.screen

- psychopy/visual/rect.py
> BF: Rect resizing after initialization.

- psychopy/app/builder/dialogs/dlgsCode.py
- Translates Python to JS on EVT_KEY_UP event, if Code Type is Auto->JS.
- Sets JS code box to read only, if Code Type is Auto->JS.
- Only gives overwrite warning if
- User was in manual code mode
- User has added new code to the JS, which would be overwritten
- Warning now only given once, rather than on every code box that has changes
- If overwrite is cancelled, previous code type is set in menu
- Refactor of onCodeChoice method
> ENH: Enhancements to code component auto-translate

- psychopy/app/builder/dialogs/dlgsCode.py
This fix will only set code type to "Auto->JS" when code box is created
if metapensiero is installed, else if falls back onto "Both". A dialog is
used to warn if the user tries to use "Auto->JS", and then their choice
is reversed when the dialog is closed. This stops existing method, where
comments are added to the users code.
> BF: uses dlg to warn about metapensiero, rather than using code comments

- psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/eyetracker.py
Fixed what looks like incomplete method code cleanup. ;(
> BF: eyelink runSetupProcedure error.

- psychopy/app/preferencesDlg.py
- psychopy/sound/__init__.py
- psychopy/sound/backend_ptb.py
Fixes to the use of the PTB backend with different hardware devices being available
(previously just taking the default device)
> Ptb audio fixes

- psychopy/alerts/alerttools.py
This caused failure to compile script.
> FF: Stripping text field was causing error when field was None.

- psychopy/app/coder/coder.py
- psychopy/app/coder/fileBrowser.py
- psychopy/demos/coder/misc/rigidBodyTransform.py
Removes modification date string to fix translation issues.
> FF: Remove modification date data.

- .gitignore
- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/experiment/_experiment.py
- psychopy/experiment/components/code/__init__.py
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/flow.py
- psychopy/experiment/routine.py
Also some commenting and bug fixes necessary for this to work
> NF: New tab for before experiment on code component

- docs/source/developers/repository.rst
- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/experiment/components/code/__init__.py
Removed instruction to pull req to master
> Updated documentation

- psychopy/demos/coder/stimuli/textbox_editable.py
- psychopy/visual/backends/pygletbackend.py
- psychopy/visual/shaders.py
- psychopy/visual/textbox2/__init__.py
- psychopy/visual/textbox2/demoTextbox3.py
- psychopy/visual/textbox2/fontmanager.py
- psychopy/visual/textbox2/textbox2.py
- psychopy/visual/window.py
Needs a fair bit of polishing:
- alginment isn't quite right
- dynamic expanding of the bounding box isn't working
- spaces behave strangely (I handle it as a non-existent character but the way I did that means the caret doesn' move when you press space!)
- I'm sure we'll find key sequences that don't work right yet
But many things do work:
- can type an accented character and it appears (e.g. AltGr+e gets an accented é)
- moving with the cursor keys does navigate multi-line text
- delete and backspace work as expected
- all rendering and layout is done on the fly within frame refresh (although the font glyphs have to be uploaded)
> TextBox2 working (roughly) with editable text inputs and tab between boxes

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/coder/coder.py
now checks that parameter is in list before attempting to assign, defaults to fist choice in list if absent
> BF: Issue #2855

- psychopy/app/runner/runner.py
Compare files in Runner by path as well as filename to solve Issue ##2893
> Fix for Issue #2893

- psychopy/app/builder/builder.py
Then need to adjust width of columns to handle potentially different sizes
of buttons (depending on label width?)
> ENH: add labels to icons in Components Panel

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/dialogs/dlgsCode.py
- psychopy/app/coder/coder.py
- psychopy/app/coder/styling.py
- psychopy/app/coder/themes/GitHub.json
- psychopy/app/coder/themes/Monokai.json
- psychopy/app/coder/themes/PsychopyDark.json
- psychopy/app/coder/themes/PsychopyLight.json
- psychopy/app/coder/themes/VSDark.json
- psychopy/app/coder/themes/VSLight.json
- psychopy/app/coder/themes/WimDark.json
- psychopy/app/coder/themes/WimLight.json
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
Fixed:
#2900
#2897
Also updating theme format to include spec for caret, selection & app (darkmode/lightmode). App still requires a restart to apply app theme.
> Implementing feedback from Reskin

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/coder/coder.py
- psychopy/app/runner/runner.py
- psychopy/app/runner/scriptProcess.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
defaults to False, so runner is used
> NF: Added option to skip runner and go straight to running file

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/runner/runner.py
- psychopy/experiment/components/form/__init__.py
- psychopy/tests/test_app/test_runner/test_RunnerFrame.py
Make sure it :
- allows local debug of remote projects (whether or not they have a remote proj yet)
- is brought to front correctly
> Fixes for Runner view

- psychopy/app/builder/builder.py
- psychopy/app/coder/coder.py
- psychopy/app/runner/runner.py
- psychopy/app/runner/scriptProcess.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
Addresses #2815
Needs a loading spinner, so don't pull in just yet
> Option to skip runner 

- psychopy/app/coder/coder.py
1. Autocomplete uses current value in prefs.
2. Calltips close when brackets are matched.
Addresses some issues in #2944
> RF/NF: Autocomplete 

- psychopy/app/themes/_themes.py
also swtiched to using Path() objects for ease
> FF: ThemeSwitcher loading of files should only try to load json files

- psychopy/app/_psychopyApp.py
- psychopy/app/builder/__init__.py
- psychopy/app/builder/builder.py
- psychopy/app/coder/__init__.py
- psychopy/app/coder/coder.py
- psychopy/app/runner/__init__.py
- psychopy/app/runner/runner.py
- psychopy/app/utils.py
Adding a Window menu for switching between frames
> Frame toggle

- psychopy/app/builder/builder.py
- psychopy/app/coder/codeEditorBase.py
- psychopy/app/coder/coder.py
- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
> BF: Correctly report caret position at end of document.

- psychopy/app/builder/builder.py
- psychopy/app/themes/ContrastDark.json
- psychopy/app/themes/ContrastLight.json
- psychopy/app/themes/app/contrast_black.json
- psychopy/app/themes/app/contrast_white.json
Added high-contrast colour schemes
> Accessibility

- psychopy/app/builder/dialogs/__init__.py
- psychopy/experiment/_experiment.py
- psychopy/experiment/components/settings/__init__.py
- psychopy/experiment/params.py
- psychopy/tests/test_app/test_builder/componsTemplate.txt
Not integrated with anything else yet (might be worth leaving this open until the end of the day, I just wanted to run it by Travis to check that the presence of a new param won't break it)
> Additional Resources Field

- psychopy/app/builder/dialogs/__init__.py
- psychopy/experiment/components/form/__init__.py
- psychopy/visual/form.py
- psychopy/visual/slider.py
Merging now just so changes are available if you work on this over the weekend
> Form styling

- psychopy/visual/textbox2/textbox2.py
These are useful for Builder and for setting with log=False
> FF: added additional methods for setting TextBox variables e.g. setText

- psychopy/__init__.py
- psychopy/app/_psychopyApp.py
- psychopy/app/builder/builder.py
- psychopy/app/coder/coder.py
- psychopy/visual/backends/__init__.py
It's a big change to include just before a release, but we want it to be
here ready to be enabled again in future
> FF: temporarily disable plugins code

- psychopy/app/idle.py
- psychopy/app/pavlovia_ui/menu.py
Answer: it isn't but this idea to delay the log-in to pavlovia is still probably the right thing to do!
> RF: checking if the mac startup delay is the call to setUser

- psychopy/preferences/Darwin.spec
- psychopy/preferences/FreeBSD.spec
- psychopy/preferences/Linux.spec
- psychopy/preferences/Windows.spec
- psychopy/preferences/baseNoArch.spec
Removing/fixing unused/broken options from prefs menu. Submitting pull req as I go so Travis can catch any unforeseen errors.
> Ceanup prefs

- psychopy/app/preferencesDlg.py
Sorry for careless mistake, this fixes syntax error in https://github.com/psychopy/psychopy/pull/3080
> FF: fix missing comma

- psychopy/tools/wizard.py
> DOCS: typo in URL from benchmark wizard

- psychopy/experiment/components/form/__init__.py
Don't try and reinvent the wheel here - let's reuse the code from
BaseVisualComponent which has detailed start/stop info
To use BaseVisualComponent we need to remove a few of the common visual
params though, like color, ori, units
> BF: better handling of start/stop times for Form by relying on BaseVisual

- psychopy/experiment/components/_base.py
- psychopy/experiment/components/aperture/__init__.py
- psychopy/experiment/components/dots/__init__.py
Bit by bit updating the component code writing functions to use f-strings rather than % formatting
> F-String Params

- docs/source/builder/components/aperture.rst
- docs/source/builder/components/brush.rst
- docs/source/builder/components/cedrusResponseBox.rst
- docs/source/builder/components/code.rst
- docs/source/builder/components/dots.rst
- docs/source/builder/components/emotiv_marking.rst
- docs/source/builder/components/form.rst
- docs/source/builder/components/grating.rst
- docs/source/builder/components/image.rst
- docs/source/builder/components/ioLabs.rst
- docs/source/builder/components/joyButtons.rst
- docs/source/builder/components/joystick.rst
- docs/source/builder/components/keyboard.rst
- docs/source/builder/components/microphone.rst
- docs/source/builder/components/mouse.rst
- docs/source/builder/components/movie.rst
- docs/source/builder/components/notes.txt
- docs/source/builder/components/parallelout.rst
- docs/source/builder/components/polygon.rst
- docs/source/builder/components/pump.rst
- docs/source/builder/components/ratingscale.rst
- docs/source/builder/components/slider.rst
- docs/source/builder/components/sound.rst
- docs/source/builder/components/static.rst
- docs/source/builder/components/text.rst
- docs/source/builder/components/variable.rst
- docs/themes/psychopy_bootstrap/static/psychopy.css
Update and refactor documentation (inc. adding Text/Textbox docs)
> Documentation

- psychopy/app/runner/scriptProcess.py
Also make sure that we unbind the whileRunning Idle() task by bringing
that call forwards slightly
> BF: don't poll() if script process has disappeared

- psychopy/experiment/components/settings/JS_htmlHeader.tmpl
> ENH: Update SheetJS to latest version 0.16.7

- psychopy/app/dialogs.py
- psychopy/experiment/_experiment.py
- psychopy/experiment/routine.py
- psychopy/tests/data/CodeComponent_eachtab.psyexp
- psychopy/tests/test_scripts/test_psyexpCompile.py
Submitting PR to test whether changes to compiling tests work
> Testing the tests

- psychopy/app/_psychopyApp.py
> Runner Print Fix

- psychopy/app/coder/coder.py
> BF: Fixes shell raising an error dialog

- psychopy/data/experiment.py
> ENH: Error when attempting to write blank data to a long text file

- psychopy/experiment/components/code/__init__.py
Displays syntax errors in Code elements in the task runner's Alerts panel.
> Code integrity check

- psychopy/app/builder/dialogs/__init__.py
> BF: Use relative paths for resource files

- psychopy/experiment/routine.py
> FF: codes for initializing status of components were not output

- psychopy/app/coder/coder.py
Addresses #3202 
Adds line wrapping by word to open editors when the menu item is checked. This doesn't write to a preference and must be re-enabled every time PsychoPy starts.
> EN: Line wrapping.

- docs/source/api/data.rst
Added automatic documentation to data.rst for TrialHandlerExt (oddball designs)
> DOC: Update data.rst to include TrialHandlerExt

- docs/source/builder/flow.rst
- psychopy/data/utils.py
- psychopy/tests/test_data/test_utils.py
A fix for [issue #3256](https://github.com/psychopy/psychopy/issues/3256)
> BF: Fix issue #3256

- psychopy/alerts/alertsCatalogue/4315.yaml
- psychopy/alerts/alertsCatalogue/alertCategories.yaml
- psychopy/alerts/alerttools.py
- psychopy/experiment/components/_base.py
- psychopy/tests/test_scripts/test_psyexpCompile.py
Still need to add JS parsing, but want to check whether it works with Travis first
> ENH: Alert for incorrect use of $

- docs/source/about/contributing.rst
- docs/source/api/iohub/device/keyboard.rst
- docs/source/api/iohub/starting.rst
- docs/source/builder/blocksCounterbalance.rst
- docs/source/conf.py
- docs/source/developers/addingdocumentation.rst
- docs/source/developers/repository.rst
- docs/source/general/timing/millisecondPrecision.rst
> DOCS: fixes to pdf formatting in particular (switch to xetex)

- psychopy/app/builder/builder.py
> BF: Allow mouse wheel scrolling in Routine canvas

- psychopy/demos/coder/stimuli/textbox_editable.py
- psychopy/visual/textbox2/textbox2.py
Also updated the demo to be more clear about some of TextBox2 features
> BF: fixes to differences between PyOpenGL.GL and pyglet.gl

- psychopy/demos/builder/anchor/README.md
- psychopy/demos/builder/anchor/anchorDemo.psyexp
Demo to show how stimulus anchoring works - a little ahead of the curve as only TextBox has an actual anchor parameter, but I'd like to add it to all visual stim eventually
> NF: Anchoring demo

- psychopy/app/builder/builder.py
Will need `markdown_it` adding to requirements, unless we already have a different potential markdown parser installed?
> NF: Add markdown parser for README files

- psychopy/data/utils.py
- psychopy/tests/test_data/test_utils.py
only use to open xls files and use openpyxl for everything else
> FF: Depreciate xlrd as it is no longer supporting xlsx files

- psychopy/app/builder/builder.py
- psychopy/app/coder/coder.py
Modified the menus in Coder to include the "Reset preferences" item found only in coder. Also tried to tweak the AUI manager to behave consistently between both parts of the app. Addresses #3417
> FF: Consistent menus

- psychopy/experiment/components/settings/JS_htmlHeader.tmpl
> experiment/settings/JS_htmlHeader: tweak howler version

- psychopy/app/builder/dialogs/paramCtrls.py
- psychopy/colors.py
for when Color is used purely for validation and its value doesn't matter
> ENH: Add option to specify that colorSpace is not needed

- psychopy/app/coder/coder.py
> BF: Fixed error when closing tabs in editor view.

- psychopy/monitors/calibTools.py
Modified version of PR 3343 by @tirkarthi which fixes #3340.
> BF: Fixed encoding bug on Python 3.9 

- psychopy/experiment/params.py
> FF: Only add one level of escape to newline characters

- psychopy/colors.py
- psychopy/demos/coder/stimuli/textbox_editable.py
- psychopy/visual/basevisual.py
- psychopy/visual/textbox2/textbox2.py
- psychopy/visual/window.py
> Fixed TextBox2 editing issue

- psychopy/experiment/components/button/__init__.py
- psychopy/visual/button.py
Now creates columns for:
number of clicks
times each click began
times each click ended
and adds options to control which clicks are stored (all, first, last, none) and what times are relative to (same as Mouse)
> BF: Button component storing times

- psychopy/app/builder/dialogs/__init__.py
- psychopy/colors.py
- psychopy/visual/textbox2/textbox2.py
These were being shown when experiments were perfectly valid
> ENH: Fixing some annoying warning messages

- psychopy/experiment/components/_base.py
- psychopy/experiment/components/text/__init__.py
Two commits together fix #3514
> BF: Update tooltips and inputTypes

- docs/source/general/colours.rst
- psychopy/colors.py
Better handling of invalid color strings and some handy subgroups of spaces
> BF/ENH: Minor fixes to Color class

- psychopy/app/coder/coder.py
- setup.cfg
Fixes #3427 which was an error caused by a significant API change to Jedi. Also updated the required version used for packaging to the version where these breaking changes first appeared (0.16).
> BF: Fix error when autocomplete is invoked.

- psychopy/app/colorpicker/__init__.py
- psychopy/app/colorpicker/pages.py
After fixing the rounding error elsewhere this morning it introduced another issue which affects how the output is produced and displayed.
> FF: Fixed incorrect rounding being used for rgba255.

- psychopy/experiment/components/_base.py
- psychopy/experiment/components/button/__init__.py
- psychopy/experiment/components/dots/__init__.py
- psychopy/experiment/components/textbox/__init__.py
- psychopy/tests/test_all_visual/test_slider.py
- psychopy/visual/basevisual.py
- psychopy/visual/button.py
- psychopy/visual/circle.py
- psychopy/visual/dot.py
- psychopy/visual/grating.py
- psychopy/visual/image.py
- psychopy/visual/line.py
- psychopy/visual/polygon.py
- psychopy/visual/rect.py
- psychopy/visual/shape.py
- psychopy/visual/textbox2/textbox2.py
> BF: Previous opacity fix was causing all stimuli to default to opaque

- psychopy/app/builder/dialogs/__init__.py
- psychopy/app/builder/dialogs/paramCtrls.py
- psychopy/experiment/components/slider/__init__.py
- psychopy/visual/slider.py
@peircej I've done this in two commits so that we can discuss the changes to Slider and cherry pick them out if they don't make sense, but following discussions with @tpronk I think this split is the way to go. Will raise at standups today so we can all chip in, just pushing out now to check Travis.
> NF: Add new type of ParamCtrl for multiple choice and use this to add "adjustments" param to slider
